# Generated by Django 5.2.17 on 2026-09-25 05:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('default_useful_life_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('default_depreciation_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('RBM', 'Reducing Balance Method'), ('UOP', 'Units of Production'), ('SYD', "Sum of Years' Digits")], default='SLM', max_length=3)),
                ('capitalization_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=128)),
                ('model_number', models.CharField(blank=True, max_length=128)),
                ('manufacturer', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_CAPITALIZATION', 'Pending Capitalization'), ('ACTIVE', 'Active'), ('IN_MAINTENANCE', 'In Maintenance'), ('TRANSFERRED', 'Transferred'), ('IMPAIRED', 'Impaired'), ('DISPOSED', 'Disposed')], default='DRAFT', max_length=32)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('capitalization_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('useful_life_months', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('RBM', 'Reducing Balance Method'), ('UOP', 'Units of Production'), ('SYD', "Sum of Years' Digits")], default='SLM', max_length=3)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_book_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organizations.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'ordering': ('asset_tag',),
            },
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['organization', 'is_active'], name='asset_cat_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_asset_category_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_asset_category_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('default_useful_life_months__gt', 0)), name='asset_category_life_positive'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.CheckConstraint(condition=models.Q(('capitalization_threshold__gte', 0)), name='asset_category_threshold_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'status'], name='asset_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'category'], name='asset_org_category_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'department'], name='asset_org_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'location'], name='asset_org_location_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'acquisition_date'], name='asset_org_acq_date_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'manufacturer'], name='asset_org_mfr_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'serial_number'], name='asset_org_serial_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('organization', 'asset_tag'), name='uniq_asset_tag_per_org'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('asset_tag', ''), _negated=True), name='asset_tag_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_cost__gte', 0)), name='asset_purchase_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('residual_value__gte', 0)), name='asset_residual_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('residual_value__lte', models.F('purchase_cost'))), name='asset_residual_lte_cost'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('useful_life_months__isnull', True), ('useful_life_months__gt', 0), _connector='OR'), name='asset_life_positive_if_set'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('current_book_value__gte', 0)), name='asset_book_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('accumulated_depreciation__gte', 0)), name='asset_accum_depr_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('capitalization_date__isnull', True), ('acquisition_date__isnull', True), ('capitalization_date__gte', models.F('acquisition_date')), _connector='OR'), name='asset_capitalization_not_before_acquisition'),
        ),
    ]
