# Generated by Django 5.2.17 on 2026-09-25 06:46

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=128)),
                ('acquisition_date', models.DateField()),
                ('capitalization_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian naira'), ('USD', 'US dollar'), ('GBP', 'Pound sterling'), ('EUR', 'Euro'), ('ZAR', 'South African rand'), ('GHS', 'Ghanaian cedi'), ('KES', 'Kenyan shilling'), ('XOF', 'West African CFA franc'), ('XAF', 'Central African CFA franc'), ('AED', 'UAE dirham'), ('SAR', 'Saudi riyal'), ('CAD', 'Canadian dollar'), ('AUD', 'Australian dollar'), ('CHF', 'Swiss franc'), ('CNY', 'Chinese yuan'), ('JPY', 'Japanese yen'), ('INR', 'Indian rupee')], default='NGN', max_length=3)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('installation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('civil_works_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('other_capitalizable_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CAPITALIZED', 'Capitalized')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acquisition', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_acquisitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisitions', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_acquisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-acquisition_date', '-created_at'),
                'indexes': [models.Index(fields=['organization', 'status'], name='acq_org_status_idx'), models.Index(fields=['organization', 'acquisition_date'], name='acq_org_acqdate_idx'), models.Index(fields=['organization', 'capitalization_date'], name='acq_org_capdate_idx'), models.Index(fields=['organization', 'invoice_number'], name='acq_org_invoice_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='acq_purchase_nonnegative'), models.CheckConstraint(condition=models.Q(('freight_cost__gte', 0)), name='acq_freight_nonnegative'), models.CheckConstraint(condition=models.Q(('installation_cost__gte', 0)), name='acq_install_nonnegative'), models.CheckConstraint(condition=models.Q(('civil_works_cost__gte', 0)), name='acq_civil_nonnegative'), models.CheckConstraint(condition=models.Q(('other_capitalizable_cost__gte', 0)), name='acq_other_nonnegative'), models.CheckConstraint(condition=models.Q(('total_cost__gt', 0)), name='acq_total_positive'), models.CheckConstraint(condition=models.Q(('total_cost', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('purchase_price'), '+', models.F('freight_cost')), '+', models.F('installation_cost')), '+', models.F('civil_works_cost')), '+', models.F('other_capitalizable_cost')))), name='acq_total_matches_components'), models.CheckConstraint(condition=models.Q(('currency__in', ['NGN', 'USD', 'GBP', 'EUR', 'ZAR', 'GHS', 'KES', 'XOF', 'XAF', 'AED', 'SAR', 'CAD', 'AUD', 'CHF', 'CNY', 'JPY', 'INR'])), name='acq_currency_supported'), models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'CAPITALIZED'])), name='acq_status_supported'), models.CheckConstraint(condition=models.Q(('capitalization_date__isnull', True), ('capitalization_date__gte', models.F('acquisition_date')), _connector='OR'), name='acq_capdate_after_acqdate')],
            },
        ),
    ]
