# Generated by Django 5.2.17 on 2026-09-25 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_acquisition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquisition",
            name="civil_works_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="acquisition",
            name="freight_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="acquisition",
            name="installation_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="acquisition",
            name="other_capitalizable_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="acquisition",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
