# Generated by Django 5.2.17 on 2026-09-25 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_acquisition_civil_works_cost_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='available_for_use_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('available_for_use_date__isnull', True), ('capitalization_date__isnull', True), ('available_for_use_date__gte', models.F('capitalization_date')), _connector='OR'), name='asset_available_after_capitalization'),
        ),
    ]
