# Generated by Django 5.2.17 on 2026-09-26 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_available_for_use_date_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('condition__in', ['GOOD', 'FAIR', 'DAMAGED', 'CRITICAL', 'UNKNOWN'])), name='asset_condition_valid'),
        ),
    ]
