# Generated by Django 5.2.17 on 2026-09-25 12:45

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_available_for_use_date_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disposal_date', models.DateField()),
                ('disposal_method', models.CharField(choices=[('SALE', 'Sale'), ('SCRAP', 'Scrap'), ('DONATION', 'Donation'), ('WRITE_OFF', 'Write-off'), ('TRANSFER_OUT', 'Transfer out')], max_length=12)),
                ('reason', models.TextField()),
                ('proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian naira'), ('USD', 'US dollar'), ('GBP', 'Pound sterling'), ('EUR', 'Euro'), ('ZAR', 'South African rand'), ('GHS', 'Ghanaian cedi'), ('KES', 'Kenyan shilling'), ('XOF', 'West African CFA franc'), ('XAF', 'Central African CFA franc'), ('AED', 'UAE dirham'), ('SAR', 'Saudi riyal'), ('CAD', 'Canadian dollar'), ('AUD', 'Australian dollar'), ('CHF', 'Swiss franc'), ('CNY', 'Chinese yuan'), ('JPY', 'Japanese yen'), ('INR', 'Indian rupee')], max_length=3)),
                ('capitalized_cost_at_disposal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('accumulated_depreciation_at_disposal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('carrying_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gain_or_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='assets.asset')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='organizations.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals_requested', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disposals_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-disposal_date', '-created_at'),
                'indexes': [models.Index(fields=['organization', 'status', 'disposal_date'], name='disposal_org_status_date_idx'), models.Index(fields=['organization', 'asset'], name='disposal_org_asset_idx'), models.Index(fields=['organization', 'disposal_method', 'disposal_date'], name='disposal_method_date_idx'), models.Index(fields=['organization', 'requested_by'], name='disposal_org_requester_idx'), models.Index(fields=['organization', 'approved_by'], name='disposal_org_approver_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('DRAFT', 'PENDING_APPROVAL', 'APPROVED'))), fields=('asset',), name='uniq_open_disposal_asset'), models.UniqueConstraint(condition=models.Q(('status', 'COMPLETED')), fields=('asset',), name='uniq_completed_disposal_asset'), models.CheckConstraint(condition=models.Q(('proceeds__gte', 0)), name='disposal_proceeds_nonnegative'), models.CheckConstraint(condition=models.Q(('disposal_method__in', ['SALE', 'SCRAP', 'DONATION', 'WRITE_OFF', 'TRANSFER_OUT'])), name='disposal_method_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED'])), name='disposal_status_valid'), models.CheckConstraint(condition=models.Q(('currency__in', ['NGN', 'USD', 'GBP', 'EUR', 'ZAR', 'GHS', 'KES', 'XOF', 'XAF', 'AED', 'SAR', 'CAD', 'AUD', 'CHF', 'CNY', 'JPY', 'INR'])), name='disposal_currency_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('APPROVED', 'COMPLETED')), _negated=True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='disposal_separation_of_duties'), models.CheckConstraint(condition=models.Q(models.Q(('accumulated_depreciation_at_disposal__isnull', True), ('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('capitalized_cost_at_disposal__isnull', True), ('carrying_amount__isnull', True), ('completed_at__isnull', True), ('gain_or_loss__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'DRAFT'), ('submitted_at__isnull', True), ('submitted_by__isnull', True)), models.Q(('accumulated_depreciation_at_disposal__isnull', True), ('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('capitalized_cost_at_disposal__isnull', True), ('carrying_amount__isnull', True), ('completed_at__isnull', True), ('gain_or_loss__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'PENDING_APPROVAL'), ('submitted_at__isnull', False), ('submitted_by__isnull', False)), models.Q(('accumulated_depreciation_at_disposal__isnull', True), ('approved_at__isnull', False), ('approved_by__isnull', False), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('capitalized_cost_at_disposal__isnull', True), ('carrying_amount__isnull', True), ('completed_at__isnull', True), ('gain_or_loss__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'APPROVED'), ('submitted_at__isnull', False), ('submitted_by__isnull', False)), models.Q(('accumulated_depreciation_at_disposal__isnull', True), ('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('capitalized_cost_at_disposal__isnull', True), ('carrying_amount__isnull', True), ('completed_at__isnull', True), ('gain_or_loss__isnull', True), ('rejected_at__isnull', False), ('rejected_by__isnull', False), ('status', 'REJECTED'), ('submitted_at__isnull', False)), models.Q(('accumulated_depreciation_at_disposal__isnull', True), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('capitalized_cost_at_disposal__isnull', True), ('carrying_amount__isnull', True), ('completed_at__isnull', True), ('gain_or_loss__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'CANCELLED')), models.Q(('accumulated_depreciation_at_disposal__isnull', False), ('approved_at__isnull', False), ('approved_by__isnull', False), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('capitalized_cost_at_disposal__isnull', False), ('carrying_amount__isnull', False), ('completed_at__isnull', False), ('gain_or_loss__isnull', False), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'COMPLETED'), ('submitted_at__isnull', False)), _connector='OR'), name='disposal_workflow_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), models.Q(('capitalized_cost_at_disposal__gte', 0), ('accumulated_depreciation_at_disposal__gte', 0), ('carrying_amount__gte', 0), ('accumulated_depreciation_at_disposal__lte', models.F('capitalized_cost_at_disposal')), ('carrying_amount', django.db.models.expressions.CombinedExpression(models.F('capitalized_cost_at_disposal'), '-', models.F('accumulated_depreciation_at_disposal'))), ('gain_or_loss', django.db.models.expressions.CombinedExpression(models.F('proceeds'), '-', models.F('carrying_amount')))), _connector='OR'), name='disposal_snapshot_matches'), models.CheckConstraint(condition=models.Q(('submitted_at__isnull', True), ('submitted_at__gte', models.F('created_at')), _connector='OR'), name='disposal_submit_after_create'), models.CheckConstraint(condition=models.Q(('approved_at__isnull', True), ('approved_at__gte', models.F('submitted_at')), _connector='OR'), name='disposal_approve_after_submit'), models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('approved_at')), _connector='OR'), name='disposal_complete_after_approve'), models.CheckConstraint(condition=models.Q(('rejected_at__isnull', True), ('rejected_at__gte', models.F('submitted_at')), _connector='OR'), name='disposal_reject_after_submit'), models.CheckConstraint(condition=models.Q(('cancelled_at__isnull', True), ('cancelled_at__gte', models.F('created_at')), _connector='OR'), name='disposal_cancel_after_create')],
            },
        ),
    ]
