# Generated by Django 5.2.17 on 2026-09-25 07:40

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_available_for_use_date_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_accounting_periods', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_periods', to='organizations.organization')),
            ],
            options={
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('SLM', 'Straight Line Method'), ('RBM', 'Reducing Balance Method'), ('UOP', 'Units of Production'), ('SYD', "Sum of Years' Digits")], max_length=3)),
                ('capitalized_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('depreciable_base', models.DecimalField(decimal_places=2, max_digits=20)),
                ('residual_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('useful_life_months', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('periodic_depreciation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Complete')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedule', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedules', to='organizations.organization')),
            ],
            options={
                'ordering': ('asset__asset_tag',),
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_book_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closing_book_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='depreciation.accountingperiod')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='assets.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='organizations.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='depreciation.depreciationschedule')),
            ],
            options={
                'ordering': ('accounting_period__year', 'accounting_period__month', 'asset__asset_tag'),
            },
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'month'), name='uniq_period_per_org'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='period_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1900)), name='period_year_valid'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED'])), name='period_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status', 'OPEN')), models.Q(('closed_at__isnull', False), ('status', 'CLOSED')), _connector='OR'), name='period_closure_consistent'),
        ),
        migrations.AddIndex(
            model_name='depreciationschedule',
            index=models.Index(fields=['organization', 'status'], name='depr_sched_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('depreciable_base__gte', 0)), name='sched_base_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('capitalized_cost__gt', 0)), name='sched_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('depreciable_base', django.db.models.expressions.CombinedExpression(models.F('capitalized_cost'), '-', models.F('residual_value')))), name='sched_base_matches_cost'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('residual_value__gte', 0)), name='sched_residual_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('useful_life_months__gt', 0)), name='sched_life_positive'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('periodic_depreciation__gte', 0)), name='sched_periodic_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='sched_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('method', 'SLM')), name='sched_method_slm'),
        ),
        migrations.AddIndex(
            model_name='depreciationentry',
            index=models.Index(fields=['organization', 'accounting_period'], name='depr_entry_org_period_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationentry',
            index=models.Index(fields=['organization', 'asset'], name='depr_entry_org_asset_idx'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.UniqueConstraint(fields=('organization', 'asset', 'accounting_period'), name='uniq_asset_depreciation_period'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('opening_book_value__gte', 0)), name='entry_opening_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('depreciation_amount__gte', 0)), name='entry_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('accumulated_depreciation__gte', 0)), name='entry_accum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('closing_book_value__gte', 0)), name='entry_closing_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='depreciationentry',
            constraint=models.CheckConstraint(condition=models.Q(('closing_book_value', django.db.models.expressions.CombinedExpression(models.F('opening_book_value'), '-', models.F('depreciation_amount')))), name='entry_rollforward_matches'),
        ),
    ]
