# Generated by Django 5.2.17 on 2026-09-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_available_for_use_date_and_more'),
        ('depreciation', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'COMPLETE'])), name='sched_status_valid'),
        ),
    ]
