# Generated by Django 5.2.17 on 2026-09-25 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation', '0002_depreciationschedule_sched_status_valid'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountingperiod',
            name='period_year_valid',
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1900), ('year__lte', 9999)), name='period_year_valid'),
        ),
    ]
