# Generated by Django 5.2.17 on 2026-09-25 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation', '0003_remove_accountingperiod_period_year_valid_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountingperiod',
            name='period_closure_consistent',
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('closed_by__isnull', True), ('status', 'OPEN')), models.Q(('closed_at__isnull', False), ('closed_by__isnull', False), ('status', 'CLOSED')), _connector='OR'), name='period_closure_consistent'),
        ),
    ]
