# Generated by Django 5.2.17 on 2026-09-28 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation', '0004_remove_accountingperiod_period_closure_consistent_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='depreciationentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepreciationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateField()),
                ('source', models.CharField(choices=[('SCHEDULED', 'Scheduled')], default='SCHEDULED', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('schedules_considered', models.PositiveIntegerField(default=0)),
                ('assets_considered', models.PositiveIntegerField(default=0)),
                ('entries_posted', models.PositiveIntegerField(default=0)),
                ('total_depreciation_posted', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('failure_class', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_runs', to='depreciation.accountingperiod')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_runs', to='organizations.organization')),
            ],
            options={
                'ordering': ('-scheduled_for', 'organization_id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'SCHEDULED')), fields=('organization', 'scheduled_for'), name='uniq_scheduled_depr_run_org_window'), models.CheckConstraint(condition=models.Q(('scheduled_for__day', 1)), name='depr_run_month_window_first_day'), models.CheckConstraint(condition=models.Q(('source__in', ['SCHEDULED'])), name='depr_run_source_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING', 'COMPLETED', 'FAILED'])), name='depr_run_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('failed_at__isnull', True), ('started_at__isnull', True), ('status', 'PENDING')), models.Q(('completed_at__isnull', True), ('failed_at__isnull', True), ('started_at__isnull', False), ('status', 'RUNNING')), models.Q(('completed_at__isnull', False), ('failed_at__isnull', True), ('started_at__isnull', False), ('status', 'COMPLETED')), models.Q(('failed_at__isnull', False), ('status', 'FAILED')), _connector='OR'), name='depr_run_timestamps_consistent'), models.CheckConstraint(condition=models.Q(('total_depreciation_posted__gte', 0)), name='depr_run_total_nonnegative')],
            },
        ),
    ]
