"""Celery Beat policy for monthly depreciation."""

MONTHLY_DEPRECIATION_SCHEDULE_ID = "monthly-depreciation-posting"
MONTHLY_DEPRECIATION_SCHEDULE_DAY = 1
MONTHLY_DEPRECIATION_SCHEDULE_HOUR = 2
MONTHLY_DEPRECIATION_SCHEDULE_MINUTE = 0
