import { describe,expect,it,vi } from 'vitest';
import { ApiClient } from './apiClient';
import { ApiError } from './apiError';
import { DjangoAssuranceRepository } from './assuranceRepository';
import { parseAssuranceFinding,parseAssuranceOccurrence,parseAssuranceRun } from './assuranceDtos';

const id='11111111-1111-4111-8111-111111111111',org='22222222-2222-4222-8222-222222222222',asset='33333333-3333-4333-8333-333333333333',at='2026-10-05T10:00:00Z';
const run={id,organization_id:org,run_type:'FULL',status:'COMPLETED',verification_campaign_id:null,stale_after_days:365,scheduled_for:null,started_at:at,completed_at:at,started_by_email:'manager@example.test',completed_by_email:'manager@example.test',assets_evaluated:2,findings_generated:1,findings_open:1,findings_resolved:0,failure_message:'',execution_phase:'DONE',captured_at:at,sealed_at:at,executor_version:1,input_schema_version:1,population_count:2,unit_count:1,units_completed:1,created_at:at,updated_at:at};
const occurrence={id:org,assurance_run:id,detected_at:at,expected_value:'100.00',observed_value:'80.00',description:'Book value does not reconcile'};
const finding={id,organization_id:org,assurance_run:id,last_detected_run:id,asset,asset_tag:'AF-1',asset_name:'Pump',physical_verification:null,department_name:'Operations',location_name:'Plant',identity_key:`asset:${asset}`,finding_type:'BOOK_VALUE_EXCEPTION',severity:'HIGH',status:'OPEN',source:'ASSET_MASTER',expected_value:'100.00',observed_value:'80.00',description:'Book value does not reconcile',occurrence_count:1,first_detected_at:at,last_detected_at:at,resolved_at:null,resolved_by_email:null,resolution_notes:'',occurrences:[occurrence],created_at:at,updated_at:at};
const ok=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
describe('F8 assurance contracts',()=>{
 it('parses authoritative run lifecycle, sealed inputs and execution progress',()=>expect(parseAssuranceRun(run)).toMatchObject({status:'COMPLETED',phase:'DONE',populationCount:2,unitCount:1,unitsCompleted:1,executorVersion:1,inputSchemaVersion:1}));
 it('rejects unknown states, malformed counters, impossible partial states and unsafe failure payload fields',()=>{for(const bad of [{...run,status:'DONE'},{...run,units_completed:2},{...run,status:'RUNNING',completed_at:at},{...run,execution_phase:'CANDIDATES'},{...run,organization_id:'bad'}])expect(()=>parseAssuranceRun(bad)).toThrow(ApiError);});
 it('parses only public finding values and immutable occurrence snapshots',()=>expect(parseAssuranceFinding(finding)).toMatchObject({type:'BOOK_VALUE_EXCEPTION',severity:'HIGH',status:'OPEN',occurrenceCount:1,occurrences:[{assuranceRunId:id,observedValue:'80.00'}]}));
 it('accepts an asset finding linked to the physical observation that exposed it',()=>expect(parseAssuranceFinding({...finding,physical_verification:id}).physicalVerificationId).toBe(id));
 it('rejects unknown finding enums, malformed occurrence IDs and inconsistent terminal resolution',()=>{for(const bad of [{...finding,finding_type:'INTERNAL_CANDIDATE'},{...finding,severity:'URGENT'},{...finding,status:'RESOLVED'},{...finding,occurrences:[{...occurrence,id:'bad'}]}])expect(()=>parseAssuranceFinding(bad)).toThrow(ApiError);expect(()=>parseAssuranceOccurrence({...occurrence,assurance_run:'bad'})).toThrow(ApiError);});
 it('uses the public findings boundary and actual filters/actions without replay',async()=>{const fetcher=vi.fn<typeof fetch>();fetcher.mockResolvedValue(ok({count:1,next:null,previous:null,results:[finding]}));const api=new ApiClient('/api/v1',fetcher);api.session={accessToken:'test',generation:1,refresh:async()=>{},invalidate:()=>{}};const repo=new DjangoAssuranceRepository(api);const result=await repo.findings({page:1,pageSize:25,finding_type:'BOOK_VALUE_EXCEPTION',asset,ordering:'-last_detected_at'});expect(result.results[0].type).toBe('BOOK_VALUE_EXCEPTION');const url=new URL(String(fetcher.mock.calls[0][0]),'https://local');expect(url.pathname).toBe('/api/v1/assurance/findings/');expect(url.searchParams.get('asset')).toBe(asset);fetcher.mockResolvedValueOnce(ok({...finding,status:'UNDER_REVIEW'}));await repo.findingAction(id,'review');expect(String(fetcher.mock.calls.at(-1)?.[0])).toContain(`/assurance/findings/${id}/review/`);expect(fetcher).toHaveBeenCalledTimes(2);expect(()=>parseAssuranceFinding({...finding,is_candidate:true})).not.toThrow();});
 it('creates runs then invokes a separate execute action; mutation transport is not retried',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValueOnce(ok({...run,status:'PENDING',started_at:null,completed_at:null,execution_phase:'CAPTURE',captured_at:null,sealed_at:null,assets_evaluated:0,findings_generated:0,findings_open:0,findings_resolved:0,population_count:0,unit_count:0,units_completed:0},201)).mockResolvedValueOnce(ok({...run,status:'RUNNING',completed_at:null,execution_phase:'EVALUATE'}));const api=new ApiClient('/api/v1',fetcher);api.session={accessToken:'test',generation:1,refresh:async()=>{},invalidate:()=>{}};const repo=new DjangoAssuranceRepository(api);await repo.createRun({run_type:'FULL',stale_after_days:365});await repo.executeRun(id);expect(fetcher).toHaveBeenCalledTimes(2);expect(String(fetcher.mock.calls[0][0])).toContain('/assurance/runs/');expect(JSON.parse(String(fetcher.mock.calls[0][1]?.body))).toEqual({run_type:'FULL',stale_after_days:365});expect(String(fetcher.mock.calls[1][0])).toContain(`/assurance/runs/${id}/execute/`);});
 it('does not send asset mutation data when resolving an assurance finding',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(ok({...finding,status:'RESOLVED',resolved_at:at,resolved_by_email:'manager@example.test',resolution_notes:'Reviewed'}));const api=new ApiClient('/api/v1',fetcher);api.session={accessToken:'test',generation:1,refresh:async()=>{},invalidate:()=>{}};await new DjangoAssuranceRepository(api).findingAction(id,'resolve','Reviewed');const request=fetcher.mock.calls[0][1];expect(JSON.parse(String(request?.body))).toEqual({resolution_notes:'Reviewed'});expect(Object.keys(JSON.parse(String(request?.body))).some(key=>['asset','location','department','status','purchase_cost'].includes(key))).toBe(false);});
});
