import { describe,expect,it,vi } from 'vitest';
import { ApiClient } from './apiClient';
import { ApiError } from './apiError';
import { parseDisposal,parseDisposalPage,formatDisposalMoney } from './disposalDtos';
import { DjangoDisposalRepository } from './disposalRepository';
import { disposalMutationRetry } from './disposalMutations';

const asset='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';const id='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const raw={id,organization_id:asset,asset_id:asset,asset_tag:'A-1',asset_name:'Pump',department_name:null,location_name:'Plant',disposal_date:'2026-09-21',disposal_method:'SALE',reason:'Retired',proceeds:'400.00',currency:'NGN',capitalized_cost_at_disposal:'1000.00',accumulated_depreciation_at_disposal:'700.00',carrying_amount:'300.00',gain_or_loss:'100.00',status:'COMPLETED',requested_by_email:'requester@example.test',submitted_by_email:'requester@example.test',submitted_at:'2026-09-20T10:00:00Z',approved_by_email:'reviewer@example.test',approved_at:'2026-09-20T11:00:00Z',rejected_by:null,rejected_at:null,cancelled_by:null,cancelled_at:null,completed_at:'2026-09-21T10:00:00Z',created_at:'2026-09-20T09:00:00Z',updated_at:'2026-09-21T10:00:00Z'};
const response=(data:unknown)=>new Response(JSON.stringify(data),{status:200,headers:{'Content-Type':'application/json'}});
const setup=(fetcher:typeof fetch)=>{const api=new ApiClient('/api/v1',fetcher);api.session={accessToken:'token',generation:1,refresh:async()=>{},invalidate:()=>{}};return new DjangoDisposalRepository(api);};

describe('F6 disposal DTO and repository contracts',()=>{
  it('preserves exact proceeds and signed gain/loss decimal strings and nullable data',()=>{const row=parseDisposal(raw);expect(row).toMatchObject({proceeds:'400.00',carryingAmount:'300.00',gainOrLoss:'100.00',departmentName:null,rejectedBy:null});expect(parseDisposal({...raw,proceeds:'0.00',gain_or_loss:'-300.00'}).gainOrLoss).toBe('-300.00');expect(formatDisposalMoney('-123456789012345678.90')).toBe('-123,456,789,012,345,678.90');});
  it.each([{...raw,status:'IN_REVIEW'},{...raw,disposal_method:'AUCTION'},{...raw,proceeds:400},{...raw,gain_or_loss:'NaN'},{...raw,disposal_date:'2026-02-31'},{...raw,approved_by_email:7}])('rejects unknown enums and malformed successful responses',value=>expect(()=>parseDisposal(value)).toThrow(ApiError));
  it('validates paginated disposal responses',()=>{expect(parseDisposalPage({count:1,next:null,previous:null,results:[raw]}).results).toHaveLength(1);expect(()=>parseDisposalPage({count:-1,next:null,previous:null,results:[]})).toThrow(ApiError);});
  it('rejects a completed record without the backend accounting snapshot',()=>expect(()=>parseDisposal({...raw,carrying_amount:null})).toThrow(ApiError));
  it('uses supported list filters and actual domain action endpoints',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValueOnce(response({count:0,next:null,previous:null,results:[]})).mockResolvedValueOnce(response(raw));const repo=setup(fetcher);await repo.list({page:2,pageSize:25,asset,status:'COMPLETED',disposal_method:'SALE',search:'pump',ordering:'-disposal_date'});await repo.complete(id);expect(fetcher.mock.calls[0][0]).toContain('status=COMPLETED');expect(fetcher.mock.calls[1][0]).toBe('/api/v1/assets/disposals/'+id+'/complete/');expect(fetcher.mock.calls[1][1]?.method).toBe('POST');});
  it('uses named workflow actions and never retries mutations automatically',async()=>{const fetcher=vi.fn<typeof fetch>().mockImplementation(async()=>response(raw));const repo=setup(fetcher);await repo.submit(id);await repo.approve(id);await repo.reject(id,'reason');await repo.cancel(id,'');expect(fetcher.mock.calls.map(call=>call[0])).toEqual([`/api/v1/assets/disposals/${id}/submit/`,`/api/v1/assets/disposals/${id}/approve/`,`/api/v1/assets/disposals/${id}/reject/`,`/api/v1/assets/disposals/${id}/cancel/`]);expect(JSON.parse(String(fetcher.mock.calls[2][1]?.body))).toEqual({reason:'reason'});expect(disposalMutationRetry).toBe(false);});
  it('submits only backend request fields and never posts carrying or gain/loss values',async()=>{const draft={...raw,status:'DRAFT',capitalized_cost_at_disposal:null,accumulated_depreciation_at_disposal:null,carrying_amount:null,gain_or_loss:null,submitted_at:null,submitted_by_email:null,approved_at:null,approved_by_email:null,completed_at:null};const fetcher=vi.fn<typeof fetch>().mockResolvedValue(response(draft));const repo=setup(fetcher);await repo.create({asset_id:asset,disposal_date:'2026-09-21',disposal_method:'SALE',reason:'Retired',proceeds:'0.00'});expect(JSON.parse(String(fetcher.mock.calls[0][1]?.body))).toEqual({asset_id:asset,disposal_date:'2026-09-21',disposal_method:'SALE',reason:'Retired',proceeds:'0.00'});expect(String(fetcher.mock.calls[0][1]?.body)).not.toMatch(/carrying_amount|gain_or_loss|accumulated_depreciation/);});
  it('rejects invalid proceeds before a request and validates UUID paths',async()=>{const fetcher=vi.fn<typeof fetch>();const repo=setup(fetcher);await expect(repo.create({asset_id:asset,disposal_date:'2026-09-21',disposal_method:'SALE',reason:'X',proceeds:'-1.00'})).rejects.toMatchObject({kind:'validation'});await expect(repo.complete('asset-1')).rejects.toMatchObject({kind:'validation'});expect(fetcher).not.toHaveBeenCalled();});
});
