import {describe,it,expect,vi} from 'vitest';
import {ApiClient} from './apiClient';
import {ApiError} from './apiError';
import {DjangoMaintenanceRepository} from './maintenanceRepository';
import {formatMaintenanceMoney,parseCost,parsePlan,parseRecord,parseWorkOrder} from './maintenanceDtos';
import {QueryClient} from '@tanstack/react-query';
import {invalidateMaintenance,maintenanceKeys} from './maintenanceQueries';

const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333'];
const order={id:ids[0],organization_id:ids[2],work_order_number:'WO-000001',asset_id:ids[1],asset_tag:'EQ-1',maintenance_type:'CORRECTIVE',priority:'HIGH',status:'IN_PROGRESS',description:'Repair',diagnosis:'Bearing noise',resolution:'',requested_by_email:'manager@example.test',assigned_to_id:null,assigned_to_email:null,due_date:null,opened_at:'2026-04-01T12:00:00Z',started_at:'2026-04-01T13:00:00Z',completed_at:null,cancelled_at:null,completion_notes:''};
const cost={id:ids[2],organization_id:ids[1],work_order_id:ids[0],work_order_number:'WO-000001',cost_type:'PARTS',description:'Seal',quantity:'2.500',unit_cost:'123456789012345678.90',total_cost:'308641972530864197.25',vendor_reference:'INV-9',incurred_at:'2026-04-01T12:00:00Z',created_by_email:'manager@example.test'};
describe('F5 maintenance contract',()=>{
 it('maps real work-order status/type and nullable fields',()=>{expect(parseWorkOrder(order)).toMatchObject({number:'WO-000001',status:'IN_PROGRESS',assignedToId:null,dueDate:null,resolution:''});});
 it('preserves exact cost decimal strings',()=>{expect(parseCost(cost)).toMatchObject({quantity:'2.500',unitCost:'123456789012345678.90',totalCost:'308641972530864197.25'});});
 it('accepts and formats the backend 22-digit total-cost domain without Number conversion',()=>{const total='1234567890123456789012.34';expect(parseCost({...cost,total_cost:total}).totalCost).toBe(total);expect(formatMaintenanceMoney(total)).toBe('1,234,567,890,123,456,789,012.34');expect(()=>parseCost({...cost,quantity:'1234567890.000'})).toThrow(ApiError);});
 it('maps plan and immutable completion record',()=>{expect(parsePlan({id:ids[0],organization_id:ids[1],asset_id:ids[2],asset_tag:'EQ',maintenance_type:'PREVENTIVE',frequency_value:3,frequency_unit:'MONTHS',next_due_date:'2026-07-01',active:true,instructions:'Inspect',created_by_email:'x@y.test',created_at:'now',updated_at:'now'}).frequencyUnit).toBe('MONTHS');expect(parseRecord({id:ids[0],organization_id:ids[1],asset:ids[2],asset_tag:'EQ',work_order:ids[1],work_order_number:'WO-1',maintenance_date:'2026-04-01',maintenance_type:'CORRECTIVE',summary:'Fixed',total_cost:'0.00',downtime_minutes:null,performed_by_email:null,created_at:'now'})).toMatchObject({totalCost:'0.00',performedBy:null});});
 it('invalidates only affected maintenance areas and lifecycle asset scope',async()=>{const client=new QueryClient();const invalidate=vi.spyOn(client,'invalidateQueries').mockResolvedValue();await invalidateMaintenance(client,7,3,['costs']);expect(invalidate).toHaveBeenCalledTimes(1);expect(invalidate).toHaveBeenLastCalledWith({queryKey:[...maintenanceKeys.scope(7,3),'costs']});invalidate.mockClear();await invalidateMaintenance(client,7,3,['work-orders','records'],ids[1]);expect(invalidate).toHaveBeenCalledTimes(3);expect(invalidate).toHaveBeenCalledWith({queryKey:[...maintenanceKeys.scope(7,3),'work-orders']});expect(invalidate).toHaveBeenCalledWith({queryKey:[...maintenanceKeys.scope(7,3),'records']});expect(invalidate).toHaveBeenCalledWith({queryKey:['django',7,3,'assets']});client.clear();});
 it('requests the actual server filters and selected pagination page',async()=>{const fetcher=vi.fn(async(_url:string)=>new Response(JSON.stringify({count:0,next:null,previous:null,results:[]}),{status:200,headers:{'content-type':'application/json'}}));const api=new ApiClient('https://assetflow.test',fetcher as typeof fetch);api.session={accessToken:'smoke-token',generation:1,refresh:async()=>{},invalidate:()=>{}};const repo=new DjangoMaintenanceRepository(api);const page=await repo.workOrders({page:2,pageSize:25,asset:ids[1],status:'IN_PROGRESS',maintenance_type:'CORRECTIVE',priority:'HIGH',search:'bearing',ordering:'-opened_at'});expect(page.count).toBe(0);const url=new URL(String(fetcher.mock.calls[0][0]));expect(Object.fromEntries(url.searchParams)).toMatchObject({page:'2',page_size:'25',asset:ids[1],status:'IN_PROGRESS',maintenance_type:'CORRECTIVE',priority:'HIGH',search:'bearing',ordering:'-opened_at'});});
 it('rejects unknown status, unknown type, malformed IDs and malformed decimal contracts',()=>{expect(()=>parseWorkOrder({...order,status:'OVERDUE'})).toThrow(ApiError);expect(()=>parseWorkOrder({...order,maintenance_type:'TUNE_UP'})).toThrow(ApiError);expect(()=>parseCost({...cost,total_cost:12.5})).toThrow(ApiError);expect(()=>parsePlan({id:'bad'})).toThrow(ApiError);});
 it('sends decimal strings unchanged and uses backend completion action',async()=>{const fetcher=vi.fn(async(_url:string,_init?:RequestInit)=>new Response(JSON.stringify(cost),{status:201,headers:{'content-type':'application/json'}}));const api=new ApiClient('https://assetflow.test',fetcher as typeof fetch);api.session={accessToken:'smoke-token',generation:1,refresh:async()=>{},invalidate:()=>{}};const repo=new DjangoMaintenanceRepository(api);await repo.createCost({work_order_id:ids[0],cost_type:'PARTS',description:'Seal',quantity:'2.500',unit_cost:'123456789012345678.90',vendor_reference:'INV-9',incurred_at:'2026-04-01T12:00:00Z'});const body=JSON.parse(String(fetcher.mock.calls[0][1]?.body));expect(body.quantity).toBe('2.500');expect(body.unit_cost).toBe('123456789012345678.90');
 const result={work_order:order,maintenance_record:{id:ids[2],organization_id:ids[1],asset:ids[1],asset_tag:'EQ-1',work_order:ids[0],work_order_number:'WO-000001',maintenance_date:'2026-04-01',maintenance_type:'CORRECTIVE',summary:'Done',total_cost:'308641972530864197.25',downtime_minutes:null,performed_by_email:null,created_at:'now'}};fetcher.mockResolvedValueOnce(new Response(JSON.stringify(result),{status:200,headers:{'content-type':'application/json'}}));await repo.complete(ids[0],{resolution:'Done',completion_notes:'',downtime_minutes:null,maintenance_date:'2026-04-01'});expect(fetcher.mock.calls[1][0]).toContain('/assets/work-orders/'+ids[0]+'/complete/');});
});
