import { ApiError, isRecord } from './apiError';
import { uuidPattern } from './assetDtos';

export const maintenanceTypes = ['PREVENTIVE','CORRECTIVE','INSPECTION','EMERGENCY'] as const;
export const workOrderPriorities = ['LOW','MEDIUM','HIGH','CRITICAL'] as const;
export const workOrderStatuses = ['OPEN','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED'] as const;
export const maintenanceCostTypes = ['LABOR','PARTS','SERVICE','OTHER'] as const;
export interface WorkOrder { id:string; organizationId:string; number:string; assetId:string; assetTag:string; type:typeof maintenanceTypes[number]; priority:typeof workOrderPriorities[number]; status:typeof workOrderStatuses[number]; description:string; diagnosis:string; resolution:string; requestedBy:string; assignedToId:number|null; assignedTo:string|null; dueDate:string|null; openedAt:string; startedAt:string|null; completedAt:string|null; cancelledAt:string|null; completionNotes:string }
export interface MaintenancePlan { id:string; organizationId:string; assetId:string; assetTag:string; type:typeof maintenanceTypes[number]; frequencyValue:number; frequencyUnit:'DAYS'|'WEEKS'|'MONTHS'; nextDueDate:string; active:boolean; instructions:string; createdBy:string; createdAt:string }
export interface MaintenanceCost { id:string; organizationId:string; workOrderId:string; workOrderNumber:string; type:typeof maintenanceCostTypes[number]; description:string; quantity:string; unitCost:string; totalCost:string; vendorReference:string; incurredAt:string; createdBy:string }
export interface MaintenanceRecord { id:string; organizationId:string; assetId:string; assetTag:string; workOrderId:string; workOrderNumber:string; date:string; type:typeof maintenanceTypes[number]; summary:string; totalCost:string; downtimeMinutes:number|null; performedBy:string|null; createdAt:string }
export interface Page<T>{count:number;next:string|null;previous:string|null;results:T[]}
const fail=():never=>{throw new ApiError('contract','The maintenance API response does not match the expected AssetFlow format.');};
const str=(v:unknown):string=>typeof v==='string'?v:fail();
const id=(v:unknown):string=>{const x=str(v);return uuidPattern.test(x)?x:fail();};
const nullableStr=(v:unknown):string|null=>v===null?null:str(v);
const nullableId=(v:unknown):number|null=>v===null?null:typeof v==='number'&&Number.isSafeInteger(v)&&v>0?v:fail();
const en=<T extends string>(v:unknown, choices:readonly T[]):T=>typeof v==='string'&&choices.includes(v as T)?v as T:fail();
const decimal=(v:unknown,places=2,whole=18):string=>typeof v==='string'&&new RegExp(`^\\d{1,${whole}}\\.\\d{${places}}$`).test(v)?v:fail();
const date=(v:unknown):string=>{const x=str(v);return /^\d{4}-\d{2}-\d{2}$/.test(x)?x:fail();};
export function parseWorkOrder(v:unknown):WorkOrder{if(!isRecord(v))return fail();return{id:id(v.id),organizationId:id(v.organization_id),number:str(v.work_order_number),assetId:id(v.asset_id),assetTag:str(v.asset_tag),type:en(v.maintenance_type,maintenanceTypes),priority:en(v.priority,workOrderPriorities),status:en(v.status,workOrderStatuses),description:str(v.description),diagnosis:str(v.diagnosis),resolution:str(v.resolution),requestedBy:str(v.requested_by_email),assignedToId:nullableId(v.assigned_to_id),assignedTo:nullableStr(v.assigned_to_email),dueDate:v.due_date===null?null:date(v.due_date),openedAt:str(v.opened_at),startedAt:nullableStr(v.started_at),completedAt:nullableStr(v.completed_at),cancelledAt:nullableStr(v.cancelled_at),completionNotes:str(v.completion_notes)};}
export function parsePlan(v:unknown):MaintenancePlan{if(!isRecord(v))return fail();return{id:id(v.id),organizationId:id(v.organization_id),assetId:id(v.asset_id),assetTag:str(v.asset_tag),type:en(v.maintenance_type,maintenanceTypes),frequencyValue:typeof v.frequency_value==='number'&&Number.isSafeInteger(v.frequency_value)&&v.frequency_value>0?v.frequency_value:fail(),frequencyUnit:en(v.frequency_unit,['DAYS','WEEKS','MONTHS'] as const),nextDueDate:date(v.next_due_date),active:typeof v.active==='boolean'?v.active:fail(),instructions:str(v.instructions),createdBy:str(v.created_by_email),createdAt:str(v.created_at)};}
export function parseCost(v:unknown):MaintenanceCost{if(!isRecord(v))return fail();return{id:id(v.id),organizationId:id(v.organization_id),workOrderId:id(v.work_order_id),workOrderNumber:str(v.work_order_number),type:en(v.cost_type,maintenanceCostTypes),description:str(v.description),quantity:decimal(v.quantity,3,9),unitCost:decimal(v.unit_cost),totalCost:decimal(v.total_cost,2,22),vendorReference:str(v.vendor_reference),incurredAt:str(v.incurred_at),createdBy:str(v.created_by_email)};}
export function parseRecord(v:unknown):MaintenanceRecord{if(!isRecord(v))return fail();return{id:id(v.id),organizationId:id(v.organization_id),assetId:id(v.asset),assetTag:str(v.asset_tag),workOrderId:id(v.work_order),workOrderNumber:str(v.work_order_number),date:date(v.maintenance_date),type:en(v.maintenance_type,maintenanceTypes),summary:str(v.summary),totalCost:decimal(v.total_cost,2,22),downtimeMinutes:v.downtime_minutes===null?null:typeof v.downtime_minutes==='number'&&Number.isInteger(v.downtime_minutes)&&v.downtime_minutes>=0?v.downtime_minutes:fail(),performedBy:nullableStr(v.performed_by_email),createdAt:str(v.created_at)};}
export function parseMaintenancePage<T>(v:unknown,parse:(row:unknown)=>T):Page<T>{if(!isRecord(v)||typeof v.count!=='number'||!Number.isSafeInteger(v.count)||v.count<0||!Array.isArray(v.results)||(v.next!==null&&typeof v.next!=='string')||(v.previous!==null&&typeof v.previous!=='string'))return fail();return{count:v.count,next:v.next,previous:v.previous,results:v.results.map(parse)};}
export function formatMaintenanceMoney(value:string):string{if(!/^\d{1,22}\.\d{2}$/.test(value))return fail();const[whole,fraction]=value.split('.');return `${whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')}.${fraction}`;}
