import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../auth/AuthProvider';
import { assetKeys } from './assetQueries';
import { maintenanceRepository } from './runtime';

export const maintenanceKeys={scope:(userId:number|undefined,generation:number)=>['django',userId,generation,'maintenance'] as const,orders:(userId:number|undefined,generation:number,filters:object)=>[...maintenanceKeys.scope(userId,generation),'work-orders',filters] as const,plans:(userId:number|undefined,generation:number,filters:object)=>[...maintenanceKeys.scope(userId,generation),'plans',filters] as const,costs:(userId:number|undefined,generation:number,filters:object)=>[...maintenanceKeys.scope(userId,generation),'costs',filters] as const,records:(userId:number|undefined,generation:number,filters:object)=>[...maintenanceKeys.scope(userId,generation),'records',filters] as const};
export function useMaintenanceOrders(filters:{page:number;pageSize:number;asset?:string;status?:string;maintenance_type?:string;priority?:string;search?:string;ordering?:string},enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:maintenanceKeys.orders(user?.id,generation,filters),queryFn:({signal})=>maintenanceRepository.workOrders(filters,signal),enabled:!!user&&enabled});}
export function useMaintenancePlans(filters:{asset?:string;active?:boolean},enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:maintenanceKeys.plans(user?.id,generation,filters),queryFn:({signal})=>maintenanceRepository.plans(filters,signal),enabled:!!user&&enabled});}
export function useMaintenanceCosts(filters:{work_order?:string},enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:maintenanceKeys.costs(user?.id,generation,filters),queryFn:({signal})=>maintenanceRepository.costs(filters,signal),enabled:!!user&&enabled});}
export function useMaintenanceRecords(filters:{asset?:string},enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:maintenanceKeys.records(user?.id,generation,filters),queryFn:({signal})=>maintenanceRepository.records(filters,signal),enabled:!!user&&enabled});}
export type MaintenanceArea='work-orders'|'plans'|'costs'|'records';
export async function invalidateMaintenance(client:ReturnType<typeof useQueryClient>,userId:number|undefined,generation:number,areas:MaintenanceArea[],assetId?:string){await Promise.all([...areas.map(area=>client.invalidateQueries({queryKey:[...maintenanceKeys.scope(userId,generation),area]})),...(assetId?[client.invalidateQueries({queryKey:assetKeys.scope(userId,generation)})]:[])]);}
