import { ApiError, isRecord } from './apiError';
import { PageDto, parsePageDto, uuidPattern } from './assetDtos';

function invalid(): never { throw new ApiError('contract', 'The movement API response did not match the expected AssetFlow format.'); }
function text(value: unknown): string { return typeof value === 'string' ? value : invalid(); }
function nullable(value: unknown): string | null { return value === null ? null : text(value); }
function uuid(value: unknown): string { const result = text(value); return uuidPattern.test(result) ? result : invalid(); }
function iso(value: unknown): string { const result = text(value); return Number.isNaN(Date.parse(result)) ? invalid() : result; }

export interface AssignmentDto { id:string; organization_id:string; asset_id:string; asset_tag:string; asset_name:string; assigned_to_id:number|null; assigned_to_email:string|null; department_id:string|null; department_name:string|null; location_id:string|null; location_name:string|null; assigned_at:string; returned_at:string|null; returned_by_email:string|null; notes:string; created_by_email:string; created_at:string; updated_at:string }
export interface AssignmentRecord { id:string; organizationId:string; assetId:string; assetTag:string; assetName:string; custodianId:number|null; custodianEmail:string|null; departmentId:string|null; departmentName:string|null; locationId:string|null; locationName:string|null; assignedAt:string; returnedAt:string|null; returnedByEmail:string|null; notes:string; createdByEmail:string; createdAt:string; updatedAt:string }
export function parseAssignmentDto(value: unknown): AssignmentDto {
  if (!isRecord(value)) return invalid();
  const assigned = value.assigned_to_id === null ? null : typeof value.assigned_to_id === 'number' && Number.isSafeInteger(value.assigned_to_id) && value.assigned_to_id > 0 ? value.assigned_to_id : invalid();
  const department = value.department_id === null ? null : uuid(value.department_id);
  const location = value.location_id === null ? null : uuid(value.location_id);
  const result: AssignmentDto = { id:uuid(value.id), organization_id:uuid(value.organization_id), asset_id:uuid(value.asset_id), asset_tag:text(value.asset_tag), asset_name:text(value.asset_name), assigned_to_id:assigned, assigned_to_email:nullable(value.assigned_to_email), department_id:department, department_name:nullable(value.department_name), location_id:location, location_name:nullable(value.location_name), assigned_at:iso(value.assigned_at), returned_at:value.returned_at === null ? null : iso(value.returned_at), returned_by_email:nullable(value.returned_by_email), notes:text(value.notes), created_by_email:text(value.created_by_email), created_at:iso(value.created_at), updated_at:iso(value.updated_at) };
  if (!!department !== !!result.department_name || !!location !== !!result.location_name || !!assigned !== !!result.assigned_to_email) return invalid();
  return result;
}
export function mapAssignmentDto(dto: AssignmentDto): AssignmentRecord { return { id:dto.id, organizationId:dto.organization_id, assetId:dto.asset_id, assetTag:dto.asset_tag, assetName:dto.asset_name, custodianId:dto.assigned_to_id, custodianEmail:dto.assigned_to_email, departmentId:dto.department_id, departmentName:dto.department_name, locationId:dto.location_id, locationName:dto.location_name, assignedAt:dto.assigned_at, returnedAt:dto.returned_at, returnedByEmail:dto.returned_by_email, notes:dto.notes, createdByEmail:dto.created_by_email, createdAt:dto.created_at, updatedAt:dto.updated_at }; }
export interface TransferDto { id:string; organization_id:string; asset_id:string; asset_tag:string; asset_name:string; from_department_id:string|null; from_department_name:string|null; from_location_id:string|null; from_location_name:string|null; to_department_id:string|null; to_department_name:string|null; to_location_id:string|null; to_location_name:string|null; requested_by_email:string; approved_by_email:string|null; completed_by_email:string|null; rejected_by_email:string|null; cancelled_by_email:string|null; requested_at:string; approved_at:string|null; completed_at:string|null; rejected_at:string|null; cancelled_at:string|null; status:string; reason:string; notes:string }
export type TransferStatus='REQUESTED'|'APPROVED'|'COMPLETED'|'REJECTED'|'CANCELLED';
export interface TransferRecord { id:string; organizationId:string; assetId:string; assetTag:string; assetName:string; fromDepartmentId:string|null; fromDepartmentName:string|null; fromLocationId:string|null; fromLocationName:string|null; toDepartmentId:string|null; toDepartmentName:string|null; toLocationId:string|null; toLocationName:string|null; requestedByEmail:string; approvedByEmail:string|null; completedByEmail:string|null; rejectedByEmail:string|null; cancelledByEmail:string|null; requestedAt:string; approvedAt:string|null; completedAt:string|null; rejectedAt:string|null; cancelledAt:string|null; status:TransferStatus; reason:string; notes:string }
const transferStatuses:TransferStatus[]=['REQUESTED','APPROVED','COMPLETED','REJECTED','CANCELLED'];
export function parseTransferDto(value: unknown): TransferDto {
  if (!isRecord(value) || typeof value.status !== 'string' || !transferStatuses.includes(value.status as TransferStatus)) return invalid();
  for (const [idKey,nameKey] of [['from_department_id','from_department_name'],['from_location_id','from_location_name'],['to_department_id','to_department_name'],['to_location_id','to_location_name']] as const) {
    if ((value[idKey] === null) !== (value[nameKey] === null)) return invalid();
  }
  const timestamp=(key:string) => value[key] === null ? null : iso(value[key]);
  const result:TransferDto = { id:uuid(value.id), organization_id:uuid(value.organization_id), asset_id:uuid(value.asset_id), asset_tag:text(value.asset_tag), asset_name:text(value.asset_name), from_department_id:value.from_department_id===null?null:uuid(value.from_department_id), from_department_name:nullable(value.from_department_name), from_location_id:value.from_location_id===null?null:uuid(value.from_location_id), from_location_name:nullable(value.from_location_name), to_department_id:value.to_department_id===null?null:uuid(value.to_department_id), to_department_name:nullable(value.to_department_name), to_location_id:value.to_location_id===null?null:uuid(value.to_location_id), to_location_name:nullable(value.to_location_name), requested_by_email:text(value.requested_by_email), approved_by_email:nullable(value.approved_by_email), completed_by_email:nullable(value.completed_by_email), rejected_by_email:nullable(value.rejected_by_email), cancelled_by_email:nullable(value.cancelled_by_email), requested_at:iso(value.requested_at), approved_at:timestamp('approved_at'), completed_at:timestamp('completed_at'), rejected_at:timestamp('rejected_at'), cancelled_at:timestamp('cancelled_at'), status:value.status, reason:text(value.reason), notes:text(value.notes) };
  if (result.status === 'REQUESTED' && (result.approved_at || result.completed_at || result.rejected_at || result.cancelled_at)
    || result.status === 'APPROVED' && (!result.approved_at || result.completed_at || result.rejected_at || result.cancelled_at)
    || result.status === 'COMPLETED' && (!result.approved_at || !result.completed_at || result.rejected_at || result.cancelled_at)
    || result.status === 'REJECTED' && (!result.rejected_at || result.approved_at || result.completed_at || result.cancelled_at)
    || result.status === 'CANCELLED' && (!result.cancelled_at || result.approved_at || result.completed_at || result.rejected_at)) return invalid();
  return result;
}
export function mapTransferDto(dto:TransferDto):TransferRecord { return { id:dto.id,organizationId:dto.organization_id,assetId:dto.asset_id,assetTag:dto.asset_tag,assetName:dto.asset_name,fromDepartmentId:dto.from_department_id,fromDepartmentName:dto.from_department_name,fromLocationId:dto.from_location_id,fromLocationName:dto.from_location_name,toDepartmentId:dto.to_department_id,toDepartmentName:dto.to_department_name,toLocationId:dto.to_location_id,toLocationName:dto.to_location_name,requestedByEmail:dto.requested_by_email,approvedByEmail:dto.approved_by_email,completedByEmail:dto.completed_by_email,rejectedByEmail:dto.rejected_by_email,cancelledByEmail:dto.cancelled_by_email,requestedAt:dto.requested_at,approvedAt:dto.approved_at,completedAt:dto.completed_at,rejectedAt:dto.rejected_at,cancelledAt:dto.cancelled_at,status:dto.status as TransferStatus,reason:dto.reason,notes:dto.notes }; }
export interface CustodianDto { id:number; email:string; role:string; department_id:string|null; department_name:string|null }
export interface CustodianRecord { id:number; email:string; role:string; departmentId:string|null; departmentName:string|null }
export function parseCustodianDto(value:unknown):CustodianRecord { if(!isRecord(value)||typeof value.id!=='number'||!Number.isSafeInteger(value.id)||value.id<=0) return invalid(); const department=value.department_id===null?null:uuid(value.department_id);const departmentName=nullable(value.department_name);if((department===null)!==(departmentName===null))return invalid();const role=text(value.role);if(!['ADMIN','ASSET_MANAGER','ACCOUNTANT','DEPARTMENT_MANAGER','EMPLOYEE'].includes(role))return invalid();return { id:value.id,email:text(value.email),role,departmentId:department,departmentName }; }
export function parseMovementPage<T>(value:unknown, parse:(row:unknown)=>T):PageDto<T> { return parsePageDto(value,parse); }
