import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import {useRef,useState} from 'react';
import { useAuth } from '../auth/AuthProvider';
import { ApiError } from './apiError';
import { organizationAdminRepository,queryClient } from './runtime';
import { AdminFilters,UserFilters } from './organizationAdminRepository';
import {movementKeys} from './movementQueries';

export const organizationAdminKeys={scope:(id:number|undefined,generation:number)=>['django',id,generation,'organization-admin'] as const};
export function useAdminDepartments(filters:AdminFilters,enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:[...organizationAdminKeys.scope(user?.id,generation),'departments',filters],queryFn:({signal})=>organizationAdminRepository.departments(filters,signal),enabled:!!user&&enabled});}
export function useAdminLocations(filters:AdminFilters,enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:[...organizationAdminKeys.scope(user?.id,generation),'locations',filters],queryFn:({signal})=>organizationAdminRepository.locations(filters,signal),enabled:!!user&&enabled});}
export function useAdminUsers(filters:UserFilters,enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:[...organizationAdminKeys.scope(user?.id,generation),'users',filters],queryFn:({signal})=>organizationAdminRepository.users(filters,signal),enabled:!!user&&enabled});}
export function useOrganizationAdminAction(){const{user,generation,isCurrent}=useAuth();const client=useQueryClient();const mutation=useMutation<unknown,Error,{action:()=>Promise<unknown>;invalidateCustodians:boolean}>({retry:false,mutationFn:async({action})=>{if(!isCurrent(generation))throw new ApiError('authentication','Your session has ended. Please sign in again.');const result=await action();if(!isCurrent(generation))throw new ApiError('authentication','Your session has ended. Please sign in again.');return result;},onSettled:async(_data,_error,variables)=>{if(isCurrent(generation)&&user?.id!==undefined)await Promise.all([client.invalidateQueries({queryKey:organizationAdminKeys.scope(user.id,generation)}),client.invalidateQueries({queryKey:['django',user.id,generation,'references']}),...(variables?.invalidateCustodians?[client.invalidateQueries({queryKey:[...movementKeys.scope(user.id,generation),'custodians']})]:[])]);}});return{pending:mutation.isPending,run:<T,>(action:()=>Promise<T>,invalidateCustodians=false)=>mutation.mutateAsync({action,invalidateCustodians}).then(value=>value as T)};}
export function useEphemeralAdminAction(){const{user,generation,isCurrent}=useAuth();const client=useQueryClient();const[ pending,setPending]=useState(false);const lock=useRef(false);return{pending,run:async<T,>(action:()=>Promise<T>,invalidateCustodians=false)=>{if(lock.current)throw new ApiError('conflict','An organization change is already in progress.');if(!isCurrent(generation))throw new ApiError('authentication','Your session has ended. Please sign in again.');lock.current=true;setPending(true);try{const result=await action();if(!isCurrent(generation))throw new ApiError('authentication','Your session has ended. Please sign in again.');return result;}finally{lock.current=false;setPending(false);if(isCurrent(generation)&&user?.id!==undefined)await Promise.all([client.invalidateQueries({queryKey:organizationAdminKeys.scope(user.id,generation)}),client.invalidateQueries({queryKey:['django',user.id,generation,'references']}),...(invalidateCustodians?[client.invalidateQueries({queryKey:[...movementKeys.scope(user.id,generation),'custodians']})]:[])]);}}};}
export async function refreshOrganizationAdmin(userId:number,generation:number){await queryClient.invalidateQueries({queryKey:organizationAdminKeys.scope(userId,generation)});}
