import {describe,expect,it,vi} from 'vitest';
import {ApiClient} from './apiClient';
import {ApiError} from './apiError';
import {DjangoReportRepository} from './reportRepository';
import {parseReportCatalog,parseReportExport,parseReportPage,parseReportSnapshot,parseSnapshotRow} from './reportDtos';

const id='11111111-1111-4111-8111-111111111111',key='22222222-2222-4222-8222-222222222222',at='2026-10-06T10:00:00Z';
const snapshot={id,report_type:'asset_register',parameters:{search:'F9'},scope_department_id:null,status:'COMPLETED',requested_at:at,started_at:at,as_of:at,generated_at:at,failed_at:null,row_count:1,summary:{row_count:1,total_purchase_cost:'9007199254740993.10'},schema_version:1,failure_class:'',failure_message:''};
const exported={id:key,source_snapshot_id:id,format:'CSV',idempotency_key:key,schema_version:1,status:'COMPLETED',requested_at:at,started_at:at,completed_at:at,failed_at:null,expires_at:'2026-11-06T10:00:00Z',expired_at:null,row_count:1,byte_size:3,sha256:'a'.repeat(64),failure_class:'',failure_message:''};
const ok=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
function client(fetcher:typeof fetch){const api=new ApiClient('/api/v1',fetcher);api.session={accessToken:'test-token',generation:4,refresh:async()=>{},invalidate:()=>{}};return api;}

describe('F9 reporting DTO boundary',()=>{
 it('parses the complete catalog and rejects unknown identifiers, filters and duplicate columns',()=>{const row={report_type:'asset_register',label:'Asset register',result_url:'/api/v1/reports/asset_register/',snapshot_supported:true,columns:['id','purchase_cost'],filters:['search']};const rows=parseReportCatalog([row]);expect(rows[0]).toMatchObject({id:'asset_register',label:'Asset register',columns:['id','purchase_cost']});expect(()=>parseReportCatalog([{...row,report_type:'future_report',result_url:'/'}])).toThrow(ApiError);expect(()=>parseReportCatalog([{...row,filters:['magic']}])).toThrow(ApiError);expect(()=>parseReportCatalog([{...row,columns:['id','id']}])).toThrow(ApiError);});
 it('validates live rows while preserving large decimal text exactly and nested JSON safely',()=>{expect(parseReportPage({count:1,next:null,previous:null,results:[{purchase_cost:'9007199254740993.10',active:true,metadata:{tags:['ok']}}]}).results[0].purchase_cost).toBe('9007199254740993.10');expect(()=>parseReportPage({count:1,next:null,previous:null,results:[{purchase_cost:9007199254740993}]})).toThrow(ApiError);expect(()=>parseReportPage({count:1,next:null,previous:null,results:[{unsafe:()=>1}]})).toThrow(ApiError);});
 it('parses request time, capture time, frozen parameters and snapshot rows',()=>{expect(parseReportSnapshot(snapshot)).toMatchObject({status:'COMPLETED',asOf:at,schemaVersion:1,parameters:{search:'F9'}});expect(parseSnapshotRow({ordinal:1,source_id:id,payload:{purchase_cost:'1.00'}}).payload.purchase_cost).toBe('1.00');for(const bad of [{...snapshot,id:'bad'},{...snapshot,status:'DONE'},{...snapshot,row_count:-1},{...snapshot,as_of:'yesterday'},{...snapshot,schema_version:0},{...snapshot,status:'QUEUED',started_at:at}])expect(()=>parseReportSnapshot(bad)).toThrow(ApiError);});
 it('keeps unknown positive versions explicit and rejects malformed export integrity/state data',()=>{expect(parseReportSnapshot({...snapshot,schema_version:99}).schemaVersion).toBe(99);expect(parseReportExport({...exported,schema_version:99}).schemaVersion).toBe(99);for(const bad of [{...exported,sha256:'broken'},{...exported,byte_size:0},{...exported,status:'UNKNOWN'},{...exported,source_snapshot_id:'bad'},{...exported,status:'QUEUED',completed_at:null,started_at:null}])expect(()=>parseReportExport(bad)).toThrow(ApiError);});
 it('uses server catalog, live report and snapshot endpoints and never constructs export rows',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(ok({count:1,next:null,previous:null,results:[{purchase_cost:'10.10'}]}));const repo=new DjangoReportRepository(client(fetcher));await repo.report('asset_register',{page:1,pageSize:25,search:'A-1'});expect(String(fetcher.mock.calls[0][0])).toContain('/reports/asset_register/');expect(new URL(String(fetcher.mock.calls[0][0]),'http://localhost').searchParams.get('search')).toBe('A-1');fetcher.mockResolvedValueOnce(ok(snapshot,202));await repo.createSnapshot({report_type:'asset_register',filters:{},idempotency_key:key});expect(JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body))).toEqual({report_type:'asset_register',filters:{},idempotency_key:key});fetcher.mockResolvedValueOnce(ok(exported,202));await repo.createExport({source_snapshot_id:id,format:'CSV',idempotency_key:key});expect(JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body))).toEqual({source_snapshot_id:id,format:'CSV',idempotency_key:key});expect(fetcher.mock.calls.some(call=>String(call[0]).includes('/exports/render'))).toBe(false);});
 it('downloads only through the authenticated private API path and fences a changed session',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response('abc',{status:200,headers:{'Content-Disposition':'attachment; filename="report.csv"','Content-Type':'text/csv'}}));const api=client(fetcher);const response=await api.download(`/report-exports/${key}/download/`);expect(await response.blob.text()).toBe('abc');expect(response.contentDisposition).toContain('report.csv');expect(new Headers(fetcher.mock.calls[0][1]?.headers).get('Authorization')).toBe('Bearer test-token');expect(String(fetcher.mock.calls[0][0])).not.toMatch(/storage|media|bucket/i);let staleApi:ApiClient;const staleFetch=vi.fn<typeof fetch>().mockImplementation(async()=>{staleApi.session!.generation++;return new Response('late');});staleApi=client(staleFetch);await expect(staleApi.download(`/report-exports/${key}/download/`)).rejects.toMatchObject({kind:'authentication'});});
 it('does not retry unauthorized downloads automatically or accept public storage URLs',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(ok({detail:'denied'},403));const repo=new DjangoReportRepository(client(fetcher));await expect(repo.downloadExport(id)).rejects.toBeInstanceOf(ApiError);expect(fetcher).toHaveBeenCalledTimes(1);await expect(repo.downloadExport('https://bucket.invalid/key')).rejects.toBeInstanceOf(ApiError);expect(fetcher).toHaveBeenCalledTimes(1);});
});
