import { ApiError, isRecord } from './apiError';
import { uuidPattern } from './assetDtos';

export const reportTypes=['asset_register','acquisitions','depreciation','accounting_periods','assignments','transfers','work_orders','maintenance_costs','maintenance_records','disposals','verification_campaigns','verification_records','verification_exceptions','assurance_runs','assurance_findings','assurance_occurrences','lifecycle_history'] as const;
export const snapshotStatuses=['QUEUED','RUNNING','COMPLETED','FAILED'] as const;
export const exportStatuses=['QUEUED','RUNNING','COMPLETED','FAILED','EXPIRED'] as const;
const reportFilters=['department','status','date_from','date_to','asset_tag','search'] as const;
export type ReportType=typeof reportTypes[number];
export type SafeReportValue=string|number|boolean|null|SafeReportValue[]|{[key:string]:SafeReportValue};
export interface ReportDefinition{id:ReportType;label:string;resultUrl:string;snapshotSupported:boolean;columns:string[];filters:string[]}
export interface ReportPage{count:number;next:string|null;previous:string|null;results:Record<string,SafeReportValue>[]}
export interface ReportSnapshot{id:string;reportType:ReportType;parameters:Record<string,string>;scopeDepartmentId:string|null;status:typeof snapshotStatuses[number];requestedAt:string;startedAt:string|null;asOf:string|null;generatedAt:string|null;failedAt:string|null;rowCount:number;summary:Record<string,SafeReportValue>;schemaVersion:number;failureClass:string;failureMessage:string}
export interface ReportSnapshotRow{ordinal:number;sourceId:string;payload:Record<string,SafeReportValue>}
export interface ReportExport{id:string;sourceSnapshotId:string;format:'CSV'|'JSON';idempotencyKey:string;schemaVersion:number;status:typeof exportStatuses[number];requestedAt:string;startedAt:string|null;completedAt:string|null;failedAt:string|null;expiresAt:string;expiredAt:string|null;rowCount:number;byteSize:number|null;sha256:string;failureClass:string;failureMessage:string}
export interface Page<T>{count:number;next:string|null;previous:string|null;results:T[]}
const fail=():never=>{throw new ApiError('contract','The reporting API response does not match the expected AssetFlow format.');};
const string=(v:unknown):string=>typeof v==='string'?v:fail();
const uuid=(v:unknown):string=>{const x=string(v);return uuidPattern.test(x)?x:fail();};
const nullableUuid=(v:unknown):string|null=>v===null?null:uuid(v);
const time=(v:unknown):string=>{const x=string(v);return Number.isNaN(Date.parse(x))?fail():x;};
const nullableTime=(v:unknown):string|null=>v===null?null:time(v);
const nat=(v:unknown):number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0?v:fail();
const positive=(v:unknown):number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>0?v:fail();
const option=<T extends string>(v:unknown,values:readonly T[]):T=>typeof v==='string'&&values.includes(v as T)?v as T:fail();
function safeValue(v:unknown,depth=0,key=''):SafeReportValue{if(depth>8)return fail();if(v===null||typeof v==='string'||typeof v==='boolean')return v;if(typeof v==='number'&&Number.isFinite(v)&&!/(?:cost|value|amount|price|proceeds|depreciation|quantity|gain|loss|carrying|unit_cost)/i.test(key))return v;if(Array.isArray(v))return v.map(x=>safeValue(x,depth+1,key));if(isRecord(v)){const result:Record<string,SafeReportValue>={};for(const [name,value]of Object.entries(v))result[name]=safeValue(value,depth+1,name);return result;}return fail();}
function safeObject(v:unknown):Record<string,SafeReportValue>{if(!isRecord(v))return fail();return safeValue(v) as Record<string,SafeReportValue>;}
function page<T>(v:unknown,parse:(v:unknown)=>T):Page<T>{if(!isRecord(v)||!Array.isArray(v.results))return fail();const next=v.next===null?null:string(v.next),previous=v.previous===null?null:string(v.previous);return{count:nat(v.count),next,previous,results:v.results.map(parse)};}
export function parseReportCatalog(v:unknown):ReportDefinition[]{if(!Array.isArray(v))return fail();const seen=new Set<string>();return v.map(row=>{if(!isRecord(row))return fail();const id=option(row.report_type,reportTypes),columns=row.columns,filters=row.filters;if(seen.has(id)||!Array.isArray(columns)||!columns.length||!Array.isArray(filters))return fail();seen.add(id);const resultUrl=string(row.result_url);if(resultUrl!==`/api/v1/reports/${id}/`)return fail();const columnNames=columns.map(string),filterNames=filters.map(value=>option(value,reportFilters));if(new Set(columnNames).size!==columnNames.length||new Set(filterNames).size!==filterNames.length||columnNames.some(name=>!/^[a-z][a-z0-9_]*$/.test(name)))return fail();return{id,label:string(row.label),resultUrl,snapshotSupported:typeof row.snapshot_supported==='boolean'?row.snapshot_supported:fail(),columns:columnNames,filters:filterNames};});}
export function parseReportPage(v:unknown,columns?:string[]):ReportPage{const result=page(v,value=>safeObject(value));if(columns&&result.results.some(row=>JSON.stringify(Object.keys(row))!==JSON.stringify(columns)))return fail();return result;}
export function parseReportSnapshot(v:unknown):ReportSnapshot{if(!isRecord(v))return fail();const parameters=safeObject(v.parameters),summary=safeObject(v.summary);for(const value of Object.values(parameters))if(typeof value!=='string')return fail();const result:ReportSnapshot={id:uuid(v.id),reportType:option(v.report_type,reportTypes),parameters:parameters as Record<string,string>,scopeDepartmentId:nullableUuid(v.scope_department_id),status:option(v.status,snapshotStatuses),requestedAt:time(v.requested_at),startedAt:nullableTime(v.started_at),asOf:nullableTime(v.as_of),generatedAt:nullableTime(v.generated_at),failedAt:nullableTime(v.failed_at),rowCount:nat(v.row_count),summary,schemaVersion:positive(v.schema_version),failureClass:string(v.failure_class),failureMessage:string(v.failure_message)};if(result.status==='QUEUED'&&(result.startedAt||result.asOf||result.generatedAt||result.failedAt))return fail();if(result.status==='RUNNING'&&(!result.startedAt||result.generatedAt||result.failedAt))return fail();if(result.status==='COMPLETED'&&(!result.startedAt||!result.asOf||!result.generatedAt||result.failedAt||result.failureClass))return fail();if(result.status==='FAILED'&&(!result.failedAt||result.generatedAt||!result.failureClass))return fail();return result;}
export function parseSnapshotRow(v:unknown):ReportSnapshotRow{if(!isRecord(v))return fail();const ordinal=positive(v.ordinal);return{ordinal,sourceId:string(v.source_id),payload:safeObject(v.payload)};}
export function parseReportExport(v:unknown):ReportExport{if(!isRecord(v))return fail();const result:ReportExport={id:uuid(v.id),sourceSnapshotId:uuid(v.source_snapshot_id),format:option(v.format,['CSV','JSON'] as const),idempotencyKey:uuid(v.idempotency_key),schemaVersion:positive(v.schema_version),status:option(v.status,exportStatuses),requestedAt:time(v.requested_at),startedAt:nullableTime(v.started_at),completedAt:nullableTime(v.completed_at),failedAt:nullableTime(v.failed_at),expiresAt:time(v.expires_at),expiredAt:nullableTime(v.expired_at),rowCount:nat(v.row_count),byteSize:v.byte_size===null?null:positive(v.byte_size),sha256:string(v.sha256),failureClass:string(v.failure_class),failureMessage:string(v.failure_message)};if(result.status==='QUEUED'&&(result.startedAt||result.completedAt||result.failedAt||result.expiredAt||result.byteSize||result.sha256))return fail();if(result.status==='RUNNING'&&(!result.startedAt||result.completedAt||result.failedAt||result.expiredAt||result.byteSize||result.sha256))return fail();if(result.status==='COMPLETED'&&(!result.startedAt||!result.completedAt||result.failedAt||result.expiredAt||!result.byteSize||! /^[0-9a-f]{64}$/.test(result.sha256)||result.failureClass))return fail();if(result.status==='FAILED'&&(!result.failedAt||result.completedAt||result.expiredAt||result.byteSize||result.sha256||!result.failureClass))return fail();if(result.status==='EXPIRED'&&(!result.completedAt||!result.expiredAt))return fail();return result;}
export const parsePage=<T>(v:unknown,parse:(v:unknown)=>T):Page<T>=>page(v,parse);
