import { useQuery } from '@tanstack/react-query';
import { useAuth } from '../auth/AuthProvider';
import { ReportFilters } from './reportRepository';
import { reportRepository, queryClient } from './runtime';

export const reportKeys={scope:(userId:number|undefined,generation:number)=>['django',userId,generation,'reporting'] as const,catalog:(u:number|undefined,g:number)=>[...reportKeys.scope(u,g),'catalog'] as const,live:(u:number|undefined,g:number,t:string,f:ReportFilters)=>[...reportKeys.scope(u,g),'live',t,f] as const,snapshots:(u:number|undefined,g:number,p:number,s:number)=>[...reportKeys.scope(u,g),'snapshots',p,s] as const,rows:(u:number|undefined,g:number,id:string,p:number,s:number)=>[...reportKeys.scope(u,g),'snapshot-rows',id,p,s] as const,exports:(u:number|undefined,g:number,p:number,s:number)=>[...reportKeys.scope(u,g),'exports',p,s] as const};
export function useReportCatalog(enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:reportKeys.catalog(user?.id,generation),queryFn:({signal})=>reportRepository.catalog(signal),enabled:!!user&&enabled});}
export function useLiveReport(type:string,filters:ReportFilters,enabled=true,columns?:string[]){const{user,generation}=useAuth();return useQuery({queryKey:[...reportKeys.live(user?.id,generation,type,filters),columns],queryFn:({signal})=>reportRepository.report(type,filters,signal,columns),enabled:!!user&&enabled&&!!type});}
export function useReportSnapshots(page:number,pageSize:number,enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:reportKeys.snapshots(user?.id,generation,page,pageSize),queryFn:({signal})=>reportRepository.snapshots(page,pageSize,signal),enabled:!!user&&enabled,refetchInterval:q=>q.state.data?.results.some(x=>x.status==='QUEUED'||x.status==='RUNNING')?4000:false});}
export function useSnapshotRows(id:string,page:number,pageSize:number,enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:reportKeys.rows(user?.id,generation,id,page,pageSize),queryFn:({signal})=>reportRepository.snapshotRows(id,page,pageSize,signal),enabled:!!user&&enabled&&!!id});}
export function useReportExports(page:number,pageSize:number,enabled=true){const{user,generation}=useAuth();return useQuery({queryKey:reportKeys.exports(user?.id,generation,page,pageSize),queryFn:({signal})=>reportRepository.exports(page,pageSize,signal),enabled:!!user&&enabled,refetchInterval:q=>q.state.data?.results.some(x=>x.status==='QUEUED'||x.status==='RUNNING')?4000:false});}
export async function invalidateReports(userId:number,generation:number){await queryClient.invalidateQueries({queryKey:reportKeys.scope(userId,generation)});}
