import { apiClient, queryClient, session } from './authRuntime';
import { DjangoAssetRepository } from './djangoApiBridge';
import { DjangoDepreciationRepository } from './depreciationRepository';
import { DjangoMovementRepository } from './movementRepository';
import { DjangoMaintenanceRepository } from './maintenanceRepository';
import { DjangoDisposalRepository } from './disposalRepository';
import { DjangoVerificationRepository } from './verificationRepository';
import { DjangoAssuranceRepository } from './assuranceRepository';
import { DjangoReportRepository } from './reportRepository';
import { DjangoAuditRepository } from './auditRepository';
import { DjangoOrganizationAdminRepository } from './organizationAdminRepository';
import { DjangoDashboardRepository } from './dashboardRepository';

export { apiClient, queryClient, session };
export const djangoRepository = new DjangoAssetRepository(apiClient);
export const depreciationRepository = new DjangoDepreciationRepository(apiClient);
export const movementRepository = new DjangoMovementRepository(apiClient);
export const maintenanceRepository = new DjangoMaintenanceRepository(apiClient);
export const disposalRepository = new DjangoDisposalRepository(apiClient);
export const verificationRepository = new DjangoVerificationRepository(apiClient);
export const assuranceRepository = new DjangoAssuranceRepository(apiClient);
export const reportRepository = new DjangoReportRepository(apiClient);
export const auditRepository = new DjangoAuditRepository(apiClient);
export const organizationAdminRepository = new DjangoOrganizationAdminRepository(apiClient);
export const dashboardRepository = new DjangoDashboardRepository(apiClient);
