import { describe, expect, it, vi } from 'vitest';
import { ApiClient } from './apiClient';
import { ApiError } from './apiError';
import { DjangoVerificationRepository } from './verificationRepository';
import { parseCampaign, parseObservation, parseVerificationException } from './verificationDtos';

const id='11111111-1111-4111-8111-111111111111',org='22222222-2222-4222-8222-222222222222',asset='33333333-3333-4333-8333-333333333333',at='2026-04-01T12:00:00Z';
const campaign={id,organization_id:org,name:'Stocktake',description:'',status:'DRAFT',scope_type:'DEPARTMENT',department_id:asset,location_id:null,start_date:'2026-04-01',due_date:null,opened_at:null,completed_at:null,created_by_email:'manager@example.test',expected_asset_count:4,verified_asset_count:0,unverified_asset_count:4,exception_count:0,resolved_exception_count:0,verification_percentage:'0.00',created_at:at,updated_at:at};
const observation={id:asset,organization_id:org,campaign_id:id,asset_id:null,asset_tag:null,verified_at:at,verified_by_email:'manager@example.test',result:'UNREGISTERED_ASSET',observed_location_id:null,observed_department_id:null,observed_custodian_id:null,observed_condition:'UNKNOWN',observed_asset_tag:'FOUND-1',observed_description:'Found item',notes:'',exceptions:[{id:org,exception_type:'UNREGISTERED_ASSET',severity:'HIGH',status:'OPEN',description:'Unregistered item'}],created_at:at,updated_at:at};
const exception={id,organization_id:org,campaign_id:org,verification_id:asset,asset_id:null,asset_tag:null,exception_type:'UNREGISTERED_ASSET',severity:'HIGH',status:'OPEN',description:'Item found',assigned_to_id:null,assigned_to_email:null,assigned_at:null,started_at:null,resolution_notes:'',resolution_reference:'',resolved_by_email:null,resolved_at:null,created_at:at,updated_at:at};
const ok=(body:unknown)=>new Response(JSON.stringify(body),{status:200,headers:{'content-type':'application/json'}});
describe('F7 verification contract',()=>{
 it('parses database-authoritative campaign scope, progress and nullable lifecycle dates',()=>expect(parseCampaign(campaign)).toMatchObject({scope:'DEPARTMENT',expected:4,verified:0,percentage:'0.00',dueDate:null,openedAt:null}));
 it('rejects unknown statuses, malformed UUIDs, invalid scope combinations and out-of-range progress',()=>{for(const bad of [{...campaign,status:'PAUSED'},{...campaign,id:'bad'},{...campaign,scope_type:'ORGANIZATION'},{...campaign,verification_percentage:'101.00'}])expect(()=>parseCampaign(bad)).toThrow(ApiError);});
 it('preserves registered versus unregistered observation distinction and real exception dimensions',()=>{expect(parseObservation(observation)).toMatchObject({assetId:null,result:'UNREGISTERED_ASSET',condition:'UNKNOWN',exceptions:[{type:'UNREGISTERED_ASSET',severity:'HIGH'}]});expect(()=>parseObservation({...observation,result:'VERIFIED'})).toThrow(ApiError);expect(parseVerificationException(exception)).toMatchObject({type:'UNREGISTERED_ASSET',status:'OPEN',assignedToId:null,resolvedAt:null});expect(()=>parseVerificationException({...exception,status:'DONE'})).toThrow(ApiError);});
 it('uses actual filters and preserves pagination, campaign transitions and observation wire payload without master-data fields',async()=>{const fetcher=vi.fn<typeof fetch>();fetcher.mockResolvedValue(ok({count:0,next:null,previous:null,results:[]}));const api=new ApiClient('/api/v1',fetcher);api.session={accessToken:'test',generation:1,refresh:async()=>{},invalidate:()=>{}};const repo=new DjangoVerificationRepository(api);await repo.campaigns({page:2,pageSize:25,status:'OPEN',search:'plant'});expect(new URL(String(fetcher.mock.calls[0][0]),'https://x').searchParams.get('status')).toBe('OPEN');fetcher.mockResolvedValueOnce(ok(campaign));await repo.transitionCampaign(id,'start');expect(fetcher.mock.calls.at(-1)?.[0]).toContain(`/verification/campaigns/${id}/start/`);fetcher.mockResolvedValueOnce(ok({...observation,asset_id:asset,asset_tag:'TAG-1',result:'LOCATION_MISMATCH',exceptions:[]}));await repo.createObservation({campaign_id:id,asset_id:asset,observed_asset_tag:'TAG-2',observed_description:'Observed',observed_location_id:org,observed_condition:'GOOD',notes:''});const body=JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body));expect(body).toMatchObject({campaign_id:id,asset_id:asset,observed_location_id:org});expect(Object.keys(body).some(k=>['location','department','status','purchase_cost','asset_tag'].includes(k))).toBe(false);});
 it('sends explicit null for an unregistered record to satisfy the nullable asset contract',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(ok(observation));const api=new ApiClient('/api/v1',fetcher);api.session={accessToken:'test',generation:1,refresh:async()=>{},invalidate:()=>{}};await new DjangoVerificationRepository(api).createObservation({campaign_id:id,observed_asset_tag:'FOUND',observed_description:'Unregistered',observed_condition:'UNKNOWN',notes:''});expect(JSON.parse(String(fetcher.mock.calls[0][1]?.body))).toMatchObject({campaign_id:id,asset_id:null});});
 it('does not retry non-idempotent verification writes',async()=>{let calls=0;const api=new ApiClient('/api/v1',vi.fn(async()=>{calls++;return ok(campaign)}));api.session={accessToken:'test',generation:1,refresh:async()=>{},invalidate:()=>{}};await new DjangoVerificationRepository(api).createCampaign({name:'Stocktake',description:'',scope_type:'ORGANIZATION',start_date:'2026-04-01'});expect(calls).toBe(1);});
});
