# Generated by Django 5.2.17 on 2026-09-25 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=240)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=32)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uniq_location_code_per_org')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uniq_department_code_per_org')],
            },
        ),
    ]
