# Generated by Django 5.2.17 on 2026-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128, unique=True)),
                ('task_name', models.CharField(max_length=240)),
                ('error_type', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPulse',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField()),
            ],
        ),
    ]
