# Generated by Django 5.2.17 on 2026-09-25 15:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_available_for_use_date_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('scope_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('DEPARTMENT', 'Department'), ('LOCATION', 'Location')], max_length=16)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_campaigns', to='organizations.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_campaigns', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_campaigns', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_campaigns_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PhysicalVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(choices=[('VERIFIED', 'Verified'), ('LOCATION_MISMATCH', 'Location mismatch'), ('CUSTODY_MISMATCH', 'Custody mismatch'), ('ASSET_NOT_FOUND', 'Asset not found'), ('TAG_MISSING', 'Tag missing'), ('DAMAGED', 'Damaged'), ('UNREGISTERED_ASSET', 'Unregistered asset'), ('DUPLICATE_TAG', 'Duplicate tag'), ('OTHER_EXCEPTION', 'Other exception')], max_length=24)),
                ('observed_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12)),
                ('observed_asset_tag', models.CharField(blank=True, max_length=64)),
                ('observed_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_verifications', to='assets.asset')),
                ('observed_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_observations', to=settings.AUTH_USER_MODEL)),
                ('observed_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_observations', to='organizations.department')),
                ('observed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_observations', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_verifications', to='organizations.organization')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_verifications', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='verification.verificationcampaign')),
            ],
            options={
                'ordering': ('-verified_at',),
            },
        ),
        migrations.CreateModel(
            name='VerificationException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('LOCATION_MISMATCH', 'Location mismatch'), ('DEPARTMENT_MISMATCH', 'Department mismatch'), ('CUSTODY_MISMATCH', 'Custody mismatch'), ('TAG_MISSING', 'Tag missing'), ('TAG_MISMATCH', 'Tag mismatch'), ('ASSET_NOT_FOUND', 'Asset not found'), ('DAMAGED_ASSET', 'Damaged asset'), ('UNREGISTERED_ASSET', 'Unregistered asset'), ('DUPLICATE_TAG', 'Duplicate tag'), ('LIFECYCLE_MISMATCH', 'Lifecycle mismatch'), ('OTHER', 'Other')], max_length=24)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED', 'Resolved'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='OPEN', max_length=16)),
                ('description', models.TextField()),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolution_reference', models.CharField(blank=True, max_length=200)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_exceptions', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_exceptions_assigned', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='verification.verificationcampaign')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_exceptions', to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verification_exceptions_resolved', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='verification.physicalverification')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VerificationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document'), ('SCAN', 'Scan'), ('NOTE', 'Note'), ('OTHER', 'Other')], max_length=12)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('external_reference', models.CharField(blank=True, max_length=512)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_evidence', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_evidence', to='organizations.organization')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='verification.physicalverification')),
                ('exception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='verification.verificationexception')),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
        migrations.AddIndex(
            model_name='verificationcampaign',
            index=models.Index(fields=['organization', 'status', 'start_date'], name='verify_campaign_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcampaign',
            index=models.Index(fields=['organization', 'department', 'status'], name='verify_campaign_org_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcampaign',
            index=models.Index(fields=['organization', 'location', 'status'], name='verify_campaign_org_loc_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'])), name='verify_campaign_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('scope_type__in', ['ORGANIZATION', 'DEPARTMENT', 'LOCATION'])), name='verify_campaign_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('start_date')), _connector='OR'), name='verify_campaign_due_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationcampaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', True), ('location__isnull', True), ('scope_type', 'ORGANIZATION')), models.Q(('department__isnull', False), ('location__isnull', True), ('scope_type', 'DEPARTMENT')), models.Q(('department__isnull', True), ('location__isnull', False), ('scope_type', 'LOCATION')), _connector='OR'), name='verify_campaign_scope_fields_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationcampaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('opened_at__isnull', True), ('status', 'DRAFT')), models.Q(('completed_at__isnull', True), ('opened_at__isnull', False), ('status__in', ('OPEN', 'IN_PROGRESS'))), models.Q(('completed_at__isnull', False), ('opened_at__isnull', False), ('status', 'COMPLETED')), models.Q(('completed_at__isnull', True), ('status', 'CANCELLED')), _connector='OR'), name='verify_campaign_timestamps_valid'),
        ),
        migrations.AddIndex(
            model_name='physicalverification',
            index=models.Index(fields=['organization', 'campaign', 'result'], name='physical_verify_org_camp_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalverification',
            index=models.Index(fields=['organization', 'asset'], name='physical_verify_org_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalverification',
            index=models.Index(fields=['organization', 'verified_at'], name='physical_verify_org_time_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalverification',
            index=models.Index(fields=['organization', 'observed_asset_tag'], name='physical_verify_org_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='physicalverification',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False)), fields=('campaign', 'asset'), name='uniq_campaign_asset_verification'),
        ),
        migrations.AddConstraint(
            model_name='physicalverification',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ['VERIFIED', 'LOCATION_MISMATCH', 'CUSTODY_MISMATCH', 'ASSET_NOT_FOUND', 'TAG_MISSING', 'DAMAGED', 'UNREGISTERED_ASSET', 'DUPLICATE_TAG', 'OTHER_EXCEPTION'])), name='physical_verify_result_valid'),
        ),
        migrations.AddConstraint(
            model_name='physicalverification',
            constraint=models.CheckConstraint(condition=models.Q(('observed_condition__in', ['GOOD', 'FAIR', 'DAMAGED', 'CRITICAL', 'UNKNOWN'])), name='physical_condition_valid'),
        ),
        migrations.AddConstraint(
            model_name='physicalverification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', True), ('result', 'UNREGISTERED_ASSET')), models.Q(('asset__isnull', False), ('result__in', ['VERIFIED', 'LOCATION_MISMATCH', 'CUSTODY_MISMATCH', 'ASSET_NOT_FOUND', 'TAG_MISSING', 'DAMAGED', 'DUPLICATE_TAG', 'OTHER_EXCEPTION'])), _connector='OR'), name='physical_verify_asset_result_valid'),
        ),
        migrations.AddIndex(
            model_name='verificationexception',
            index=models.Index(fields=['organization', 'campaign', 'status'], name='verify_exc_org_camp_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationexception',
            index=models.Index(fields=['organization', 'asset', 'status'], name='verify_exc_org_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationexception',
            index=models.Index(fields=['organization', 'status', 'severity'], name='verify_exc_org_state_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationexception',
            index=models.Index(fields=['organization', 'assigned_to', 'status'], name='verify_exc_org_user_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationexception',
            index=models.Index(fields=['organization', 'exception_type', 'created_at'], name='verify_exc_org_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationexception',
            constraint=models.UniqueConstraint(fields=('verification', 'exception_type'), name='uniq_verify_exception_type'),
        ),
        migrations.AddConstraint(
            model_name='verificationexception',
            constraint=models.CheckConstraint(condition=models.Q(('exception_type__in', ['LOCATION_MISMATCH', 'DEPARTMENT_MISMATCH', 'CUSTODY_MISMATCH', 'TAG_MISSING', 'TAG_MISMATCH', 'ASSET_NOT_FOUND', 'DAMAGED_ASSET', 'UNREGISTERED_ASSET', 'DUPLICATE_TAG', 'LIFECYCLE_MISMATCH', 'OTHER'])), name='verify_exception_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationexception',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])), name='verify_exception_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationexception',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'UNDER_REVIEW', 'RESOLVED', 'ACCEPTED', 'REJECTED'])), name='verify_exception_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status__in', ('OPEN', 'UNDER_REVIEW'))), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status__in', ('RESOLVED', 'ACCEPTED', 'REJECTED'))), _connector='OR'), name='verify_exception_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationexception',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_at__isnull', True), ('assigned_to__isnull', False), _connector='OR'), name='verify_exception_assign_valid'),
        ),
        migrations.AddIndex(
            model_name='verificationevidence',
            index=models.Index(fields=['organization', 'verification', 'captured_at'], name='verify_evid_org_record_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationevidence',
            index=models.Index(fields=['organization', 'exception'], name='verify_evid_org_exc_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_type__in', ['PHOTO', 'DOCUMENT', 'SCAN', 'NOTE', 'OTHER'])), name='verify_evidence_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_type', 'NOTE'), models.Q(('external_reference', ''), ('storage_key', ''), _negated=True), _connector='OR'), name='verify_evidence_reference_present'),
        ),
    ]
