# Generated by Django 5.2.17 on 2026-09-25 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_available_for_use_date_and_more'),
        ('organizations', '0001_initial'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='physicalverification',
            index=models.Index(fields=['organization', 'observed_department'], name='physical_verify_org_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalverification',
            index=models.Index(fields=['organization', 'observed_location'], name='physical_verify_org_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalverification',
            index=models.Index(fields=['organization', 'observed_custodian'], name='physical_verify_org_user_idx'),
        ),
    ]
