# Generated by Django 5.2.17 on 2026-09-30 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('verification', '0003_remove_physicalverification_physical_verify_result_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verificationevidence',
            name='verify_evidence_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='verificationevidence',
            name='verify_evidence_reference_present',
        ),
        migrations.AddField(
            model_name='verificationevidence',
            name='binary_storage_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='verificationevidence',
            name='byte_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationevidence',
            name='integrity_status',
            field=models.CharField(choices=[('METADATA_ONLY', 'Metadata only'), ('LEGACY_UNVERIFIED', 'Legacy reference not verified'), ('PENDING', 'Upload pending'), ('VERIFIED', 'Stored bytes verified'), ('FAILED', 'Upload failed'), ('CORRUPT', 'Stored bytes failed integrity check')], default='LEGACY_UNVERIFIED', max_length=24),
        ),
        migrations.AddField(
            model_name='verificationevidence',
            name='integrity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationevidence',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='verificationevidence',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationevidence',
            name='evidence_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document'), ('SCAN', 'Scan'), ('NOTE', 'Note')], max_length=12),
        ),
        migrations.AddIndex(
            model_name='verificationevidence',
            index=models.Index(fields=['organization', 'integrity_status', 'created_at'], name='verify_evid_integrity_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_type__in', ['PHOTO', 'DOCUMENT', 'SCAN', 'NOTE'])), name='verify_evidence_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_type', 'NOTE'), models.Q(('binary_storage_key', ''), ('external_reference', ''), ('storage_key', ''), _negated=True), _connector='OR'), name='verify_evidence_reference_present'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('binary_storage_key', ''), _negated=True), fields=('binary_storage_key',), name='verify_evid_binary_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('binary_storage_key__gt', ''), ('byte_size__gt', 0), ('integrity_status__in', ('VERIFIED', 'CORRUPT')), ('integrity_verified_at__isnull', False), ('sha256__regex', '^[0-9a-f]{64}$'), ('uploaded_at__isnull', False)), models.Q(('binary_storage_key__gt', ''), ('byte_size__isnull', True), ('integrity_status', 'PENDING'), ('sha256', '')), models.Q(('integrity_status__in', ('METADATA_ONLY', 'LEGACY_UNVERIFIED', 'FAILED')), ('binary_storage_key', ''), ('byte_size__isnull', True), ('sha256', '')), _connector='OR'), name='verify_evid_integrity_valid'),
        ),
    ]
