# Generated by Django 5.2.17 on 2026-09-25 10:06

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_available_for_use_date_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderSequence',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='organizations.organization')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_order_number', models.CharField(max_length=32)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('INSPECTION', 'Inspection'), ('EMERGENCY', 'Emergency')], max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_assigned', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('INSPECTION', 'Inspection'), ('EMERGENCY', 'Emergency')], max_length=12)),
                ('summary', models.TextField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('downtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='organizations.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records_performed', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_record', to='maintenance.workorder')),
            ],
            options={
                'ordering': ('-maintenance_date',),
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_type', models.CharField(choices=[('LABOR', 'Labor'), ('PARTS', 'Parts'), ('SERVICE', 'Service'), ('OTHER', 'Other')], max_length=8)),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=24)),
                ('vendor_reference', models.CharField(blank=True, max_length=128)),
                ('incurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_costs_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_costs', to='organizations.organization')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='maintenance.workorder')),
            ],
            options={
                'ordering': ('incurred_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('INSPECTION', 'Inspection'), ('EMERGENCY', 'Emergency')], max_length=12)),
                ('frequency_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Frequency must be positive.')])),
                ('frequency_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], max_length=6)),
                ('next_due_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='assets.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='organizations.organization')),
            ],
            options={
                'ordering': ('next_due_date', 'asset__asset_tag'),
                'indexes': [models.Index(fields=['organization', 'asset'], name='maint_plan_org_asset_idx'), models.Index(fields=['organization', 'active', 'next_due_date'], name='maint_plan_due_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('frequency_value__gt', 0)), name='maint_plan_freq_positive'), models.CheckConstraint(condition=models.Q(('maintenance_type__in', ['PREVENTIVE', 'CORRECTIVE', 'INSPECTION', 'EMERGENCY'])), name='maint_plan_type_valid'), models.CheckConstraint(condition=models.Q(('frequency_unit__in', ['DAYS', 'WEEKS', 'MONTHS'])), name='maint_plan_unit_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'asset', 'status'], name='wo_org_asset_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'status', 'due_date'], name='wo_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'maintenance_type', 'opened_at'], name='wo_type_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'assigned_to'], name='wo_org_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('organization', 'work_order_number'), name='uniq_wo_number_org'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('work_order_number', ''), _negated=True), name='wo_number_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_type__in', ['PREVENTIVE', 'CORRECTIVE', 'INSPECTION', 'EMERGENCY'])), name='wo_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])), name='wo_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'])), name='wo_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', True), ('completed_at__isnull', True), ('started_at__isnull', True), ('status', 'OPEN')), models.Q(('assigned_to__isnull', False), ('cancelled_at__isnull', True), ('completed_at__isnull', True), ('started_at__isnull', True), ('status', 'ASSIGNED')), models.Q(('cancelled_at__isnull', True), ('completed_at__isnull', True), ('started_at__isnull', False), ('status', 'IN_PROGRESS')), models.Q(('cancelled_at__isnull', True), ('completed_at__isnull', False), ('started_at__isnull', False), ('status', 'COMPLETED')), models.Q(('cancelled_at__isnull', False), ('completed_at__isnull', True), ('status', 'CANCELLED')), _connector='OR'), name='wo_workflow_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('started_at__gte', models.F('opened_at')), _connector='OR'), name='wo_started_after_open'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='wo_completed_after_start'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(('cancelled_at__isnull', True), ('cancelled_at__gte', models.F('opened_at')), _connector='OR'), name='wo_cancelled_after_open'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['organization', 'asset', 'maintenance_date'], name='maint_record_asset_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['organization', 'maintenance_type', 'maintenance_date'], name='maint_record_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='maint_record_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('maintenance_type__in', ['PREVENTIVE', 'CORRECTIVE', 'INSPECTION', 'EMERGENCY'])), name='maint_record_type_valid'),
        ),
        migrations.AddIndex(
            model_name='maintenancecost',
            index=models.Index(fields=['organization', 'work_order'], name='maint_cost_org_wo_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancecost',
            constraint=models.CheckConstraint(condition=models.Q(('cost_type__in', ['LABOR', 'PARTS', 'SERVICE', 'OTHER'])), name='maint_cost_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='maintenancecost',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='maint_cost_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='maintenancecost',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='maint_cost_unit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='maintenancecost',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_cost')))), name='maint_cost_total_matches'),
        ),
    ]
