# Generated by Django 5.2.17 on 2026-09-25 10:19

import django.db.models.expressions
import django.db.models.functions.math
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maintenancecost',
            name='maint_cost_total_matches',
        ),
        migrations.AddConstraint(
            model_name='maintenancecost',
            constraint=models.CheckConstraint(condition=models.Q(('total_cost', django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_cost')), precision=2))), name='maint_cost_total_matches'),
        ),
    ]
