# Generated by Django 5.2.17 on 2026-09-30 16:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('run_key', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded')], max_length=12)),
                ('attempt_token', models.UUIDField(default=uuid.uuid4)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('source_watermark_at', models.DateTimeField(blank=True, null=True)),
                ('source_watermark_snapshot_id', models.UUIDField(blank=True, null=True)),
                ('source_watermark_ordinal', models.PositiveBigIntegerField(default=0)),
                ('resulting_watermark_at', models.DateTimeField(blank=True, null=True)),
                ('resulting_watermark_snapshot_id', models.UUIDField(blank=True, null=True)),
                ('resulting_watermark_ordinal', models.PositiveBigIntegerField(default=0)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failure_class', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_runs', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('contract_version', models.PositiveSmallIntegerField()),
                ('storage_key', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('row_count', models.PositiveBigIntegerField()),
                ('source_watermark_at', models.DateTimeField(blank=True, null=True)),
                ('source_watermark_snapshot_id', models.UUIDField(blank=True, null=True)),
                ('source_watermark_ordinal', models.PositiveBigIntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_publications', to='organizations.organization')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='analytics.analyticsrun')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('watermark_at', models.DateTimeField(blank=True, null=True)),
                ('watermark_snapshot_id', models.UUIDField(blank=True, null=True)),
                ('watermark_ordinal', models.PositiveBigIntegerField(default=0)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('active_attempt_token', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_checkpoints', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'updated_at'], name='an_checkpoint_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'dataset'), name='analytics_checkpoint_tenant_dataset_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('watermark_at__isnull', True), ('watermark_ordinal', 0), ('watermark_snapshot_id__isnull', True)), models.Q(('watermark_at__isnull', False), ('watermark_snapshot_id__isnull', False)), _connector='OR'), name='analytics_checkpoint_cursor_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='analyticsrun',
            index=models.Index(fields=['organization', 'dataset', 'status'], name='analytics_run_state_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsrun',
            index=models.Index(fields=['started_at', 'status'], name='analytics_run_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsrun',
            constraint=models.UniqueConstraint(fields=('organization', 'dataset', 'run_key'), name='analytics_run_tenant_dataset_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analyticsrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['RUNNING', 'COMPLETED', 'FAILED', 'SUPERSEDED'])), name='analytics_run_status_valid'),
        ),
        migrations.AddIndex(
            model_name='analyticspublication',
            index=models.Index(fields=['organization', 'dataset', 'published_at'], name='analytics_pub_tenant_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticspublication',
            constraint=models.UniqueConstraint(fields=('organization', 'dataset', 'run'), name='analytics_pub_tenant_dataset_run_uniq'),
        ),
        migrations.AddConstraint(
            model_name='analyticspublication',
            constraint=models.CheckConstraint(condition=models.Q(('contract_version__gt', 0)), name='analytics_publication_contract_positive'),
        ),
        migrations.AddConstraint(
            model_name='analyticspublication',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='analytics_publication_hash_valid'),
        ),
    ]
