# Generated by Django 5.2.17 on 2026-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsrun',
            name='full_refresh',
            field=models.BooleanField(default=False),
        ),
    ]
