# Generated by Django 5.2.17 on 2026-10-01 00:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_alter_analyticscheckpoint_dataset_and_more"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuratedProcessingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("processing_key", models.CharField(max_length=64)),
                ("contract_version", models.PositiveSmallIntegerField()),
                ("transform_version", models.PositiveSmallIntegerField()),
                ("source_publications", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("attempt_token", models.UUIDField(default=uuid.uuid4)),
                ("attempt_count", models.PositiveIntegerField(default=1)),
                ("input_manifest_key", models.CharField(blank=True, max_length=512)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("failure_class", models.CharField(blank=True, max_length=100)),
                ("failure_message", models.CharField(blank=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curated_runs",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CuratedPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("manifest_key", models.CharField(max_length=512)),
                ("manifest_sha256", models.CharField(max_length=64)),
                ("manifest_byte_size", models.PositiveBigIntegerField()),
                ("datasets", models.JSONField()),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curated_publications",
                        to="organizations.organization",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication",
                        to="analytics.curatedprocessingrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="curatedprocessingrun",
            index=models.Index(
                fields=["organization", "status"], name="curated_run_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curatedprocessingrun",
            index=models.Index(fields=["started_at", "status"], name="curated_run_started_idx"),
        ),
        migrations.AddConstraint(
            model_name="curatedprocessingrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "processing_key"), name="curated_run_org_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedprocessingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("contract_version", 1)), name="curated_run_contract_v1"
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedprocessingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("transform_version", 1)), name="curated_run_transform_v1"
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedprocessingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["RUNNING", "FAILED", "COMPLETED"])),
                name="curated_run_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedprocessingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("finished_at__isnull", True), ("status", "RUNNING")),
                    models.Q(
                        ("failure_class__gt", ""),
                        ("finished_at__isnull", False),
                        ("status", "FAILED"),
                    ),
                    models.Q(
                        ("failure_class", ""),
                        ("failure_message", ""),
                        ("finished_at__isnull", False),
                        ("status", "COMPLETED"),
                    ),
                    _connector="OR",
                ),
                name="curated_run_state_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedprocessingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("processing_key__regex", "^[0-9a-f]{64}$")),
                name="curated_run_key_sha256",
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedpublication",
            constraint=models.UniqueConstraint(
                fields=("organization", "run"), name="curated_pub_org_run_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("manifest_key__gt", "")), name="curated_pub_manifest_key_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="curatedpublication",
            constraint=models.CheckConstraint(
                condition=models.Q(("manifest_sha256__regex", "^[0-9a-f]{64}$")),
                name="curated_pub_manifest_hash_valid",
            ),
        ),
    ]
