# Generated by Django 5.2.17 on 2026-09-27 08:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0005_asset_condition_asset_asset_condition_valid'),
        ('organizations', '0001_initial'),
        ('verification', '0003_remove_physicalverification_physical_verify_result_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuranceFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(max_length=80)),
                ('finding_type', models.CharField(choices=[('LOCATION_MISMATCH', 'Location mismatch'), ('DEPARTMENT_MISMATCH', 'Department mismatch'), ('CUSTODY_MISMATCH', 'Custody mismatch'), ('MISSING_PHYSICAL_VERIFICATION', 'Missing physical verification'), ('ASSET_NOT_FOUND', 'Asset not found'), ('UNREGISTERED_ASSET', 'Unregistered asset'), ('TAG_MISMATCH', 'Tag mismatch'), ('DUPLICATE_TAG', 'Duplicate tag'), ('CONDITION_EXCEPTION', 'Condition exception'), ('LIFECYCLE_MISMATCH', 'Lifecycle mismatch'), ('DISPOSAL_STATUS_MISMATCH', 'Disposal status mismatch'), ('DEPRECIATION_EXCEPTION', 'Depreciation exception'), ('BOOK_VALUE_EXCEPTION', 'Book value exception'), ('STALE_RECORD', 'Stale record'), ('OPEN_WORKFLOW', 'Open workflow'), ('MISSING_EVIDENCE', 'Missing evidence')], max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('RESOLVED', 'Resolved'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='OPEN', max_length=16)),
                ('source', models.CharField(choices=[('ASSET_MASTER', 'Asset master'), ('PHYSICAL_VERIFICATION', 'Physical verification'), ('DEPRECIATION', 'Depreciation'), ('DISPOSAL', 'Disposal'), ('MAINTENANCE', 'Maintenance'), ('ASSIGNMENT', 'Assignment'), ('TRANSFER', 'Transfer'), ('EVIDENCE', 'Evidence')], max_length=24)),
                ('expected_value', models.TextField(blank=True)),
                ('observed_value', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assurance_findings', to='assets.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_findings', to='organizations.organization')),
                ('physical_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assurance_findings', to='verification.physicalverification')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assurance_findings_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_detected_at', 'asset__asset_tag'),
            },
        ),
        migrations.CreateModel(
            name='AssuranceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('FULL', 'Full'), ('PHYSICAL', 'Physical'), ('FINANCIAL', 'Financial'), ('OPERATIONAL', 'Operational')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('stale_after_days', models.PositiveSmallIntegerField(default=365)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assets_evaluated', models.PositiveIntegerField(default=0)),
                ('findings_generated', models.PositiveIntegerField(default=0)),
                ('findings_open', models.PositiveIntegerField(default=0)),
                ('findings_resolved', models.PositiveIntegerField(default=0)),
                ('failure_message', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assurance_runs_completed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_runs', to='organizations.organization')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_runs_started', to=settings.AUTH_USER_MODEL)),
                ('verification_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assurance_runs', to='verification.verificationcampaign')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssuranceFindingOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_value', models.TextField(blank=True)),
                ('observed_value', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='assurance.assurancefinding')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_occurrences', to='organizations.organization')),
                ('assurance_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_occurrences', to='assurance.assurancerun')),
            ],
            options={
                'ordering': ('detected_at',),
            },
        ),
        migrations.AddField(
            model_name='assurancefinding',
            name='assurance_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='assurance.assurancerun'),
        ),
        migrations.AddField(
            model_name='assurancefinding',
            name='last_detected_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings_last_detected', to='assurance.assurancerun'),
        ),
        migrations.AddIndex(
            model_name='assurancerun',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='assrun_org_state_idx'),
        ),
        migrations.AddIndex(
            model_name='assurancerun',
            index=models.Index(fields=['organization', 'run_type', 'started_at'], name='assrun_org_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.CheckConstraint(condition=models.Q(('run_type__in', ['FULL', 'PHYSICAL', 'FINANCIAL', 'OPERATIONAL'])), name='assurance_run_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'])), name='assurance_run_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.CheckConstraint(condition=models.Q(('stale_after_days__gt', 0)), name='assurance_stale_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('started_at__isnull', True), ('status', 'PENDING')), models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('started_at__isnull', False), ('status', 'RUNNING')), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('started_at__isnull', False), ('status__in', ('COMPLETED', 'FAILED'))), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('status', 'CANCELLED')), _connector='OR'), name='assurance_run_timestamps_valid'),
        ),
        migrations.AddIndex(
            model_name='assurancefindingoccurrence',
            index=models.Index(fields=['organization', 'assurance_run', 'detected_at'], name='assocc_org_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='assurancefindingoccurrence',
            constraint=models.UniqueConstraint(fields=('finding', 'assurance_run'), name='assfinding_run_occurrence_uniq'),
        ),
        migrations.AddIndex(
            model_name='assurancefinding',
            index=models.Index(fields=['organization', 'status', 'severity'], name='assfind_org_state_idx'),
        ),
        migrations.AddIndex(
            model_name='assurancefinding',
            index=models.Index(fields=['organization', 'asset', 'finding_type'], name='assfind_org_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='assurancefinding',
            index=models.Index(fields=['organization', 'assurance_run', 'status'], name='assfind_org_run_idx'),
        ),
        migrations.AddIndex(
            model_name='assurancefinding',
            index=models.Index(fields=['organization', 'source', 'finding_type'], name='assfind_org_src_idx'),
        ),
        migrations.AddConstraint(
            model_name='assurancefinding',
            constraint=models.CheckConstraint(condition=models.Q(('finding_type__in', ['LOCATION_MISMATCH', 'DEPARTMENT_MISMATCH', 'CUSTODY_MISMATCH', 'MISSING_PHYSICAL_VERIFICATION', 'ASSET_NOT_FOUND', 'UNREGISTERED_ASSET', 'TAG_MISMATCH', 'DUPLICATE_TAG', 'CONDITION_EXCEPTION', 'LIFECYCLE_MISMATCH', 'DISPOSAL_STATUS_MISMATCH', 'DEPRECIATION_EXCEPTION', 'BOOK_VALUE_EXCEPTION', 'STALE_RECORD', 'OPEN_WORKFLOW', 'MISSING_EVIDENCE'])), name='assfinding_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancefinding',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'])), name='assfinding_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancefinding',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'UNDER_REVIEW', 'RESOLVED', 'ACCEPTED', 'REJECTED'])), name='assfinding_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancefinding',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['ASSET_MASTER', 'PHYSICAL_VERIFICATION', 'DEPRECIATION', 'DISPOSAL', 'MAINTENANCE', 'ASSIGNMENT', 'TRANSFER', 'EVIDENCE'])), name='assfinding_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancefinding',
            constraint=models.CheckConstraint(condition=models.Q(('occurrence_count__gte', 1)), name='assfinding_occurrences_positive'),
        ),
        migrations.AddConstraint(
            model_name='assurancefinding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True), ('status__in', ('OPEN', 'UNDER_REVIEW'))), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False), ('status__in', ('RESOLVED', 'ACCEPTED', 'REJECTED'))), _connector='OR'), name='assfinding_resolution_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancefinding',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('OPEN', 'UNDER_REVIEW'))), fields=('organization', 'identity_key', 'finding_type'), name='assfinding_active_identity_uniq'),
        ),
    ]
