# Generated by Django 5.2.17 on 2026-09-28 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0001_initial'),
        ('organizations', '0001_initial'),
        ('verification', '0003_remove_physicalverification_physical_verify_result_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assurancerun',
            name='assurance_run_timestamps_valid',
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assurancerun',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assurance_runs_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scheduled_for__isnull', True), ('started_by__isnull', False)), models.Q(('run_type', 'FULL'), ('scheduled_for__isnull', False), ('started_by__isnull', True)), _connector='OR'), name='assrun_schedule_actor_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.UniqueConstraint(condition=models.Q(('scheduled_for__isnull', False)), fields=('organization', 'scheduled_for'), name='assrun_org_sched_day_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('started_at__isnull', True), ('status', 'PENDING')), models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('started_at__isnull', False), ('status', 'RUNNING')), models.Q(('completed_at__isnull', False), ('started_at__isnull', False), ('status__in', ('COMPLETED', 'FAILED')), models.Q(('completed_by__isnull', False), models.Q(('completed_by__isnull', True), ('scheduled_for__isnull', False)), _connector='OR')), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('status', 'CANCELLED')), _connector='OR'), name='assurance_run_timestamps_valid'),
        ),
    ]
