# Generated by Django 5.2.17 on 2026-09-30 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def identify_legacy_runs(apps, schema_editor):
    Run = apps.get_model("assurance", "AssuranceRun")
    Run.objects.using(schema_editor.connection.alias).filter(executor_version=0).update(
        execution_phase="LEGACY"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0002_remove_assurancerun_assurance_run_timestamps_valid_and_more'),
        ('organizations', '0001_initial'),
        ('verification', '0003_remove_physicalverification_physical_verify_result_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuranceRunCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ordinal', models.PositiveIntegerField()),
                ('identity_key', models.CharField(max_length=80)),
                ('finding_type', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceRunInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=12)),
                ('source_id', models.UUIDField()),
                ('asset_id', models.UUIDField(null=True)),
                ('campaign_id', models.UUIDField(null=True)),
                ('normalized_tag', models.TextField(blank=True)),
                ('subject_ordinal', models.PositiveIntegerField(null=True)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceWorkUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('first_subject', models.PositiveIntegerField()),
                ('last_subject', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='execution_phase',
            field=models.CharField(default='CAPTURE', max_length=12),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='executor_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='input_schema_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='population_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='subject_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='unit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='units_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assurancerun',
            name='work_unit_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.CheckConstraint(condition=models.Q(('execution_phase__in', ('LEGACY', 'CAPTURE', 'EVALUATE', 'PUBLISH', 'DONE'))), name='assrun_phase_valid'),
        ),
        migrations.AddConstraint(
            model_name='assurancerun',
            constraint=models.CheckConstraint(condition=models.Q(('units_completed__lte', models.F('unit_count'))), name='assrun_progress_valid'),
        ),
        migrations.AddField(
            model_name='assuranceruncandidate',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='assurance.assurancerun'),
        ),
        migrations.AddField(
            model_name='assuranceruninput',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inputs', to='assurance.assurancerun'),
        ),
        migrations.AddField(
            model_name='assuranceworkunit',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_units', to='assurance.assurancerun'),
        ),
        migrations.AddConstraint(
            model_name='assuranceruncandidate',
            constraint=models.UniqueConstraint(fields=('run', 'identity_key', 'finding_type'), name='asscandidate_identity_uniq'),
        ),
        migrations.AddIndex(
            model_name='assuranceruninput',
            index=models.Index(fields=['run', 'campaign_id', 'normalized_tag'], name='assin_tag_idx'),
        ),
        migrations.AddIndex(
            model_name='assuranceruninput',
            index=models.Index(fields=['run', 'asset_id', 'kind'], name='assin_asset_idx'),
        ),
        migrations.AddConstraint(
            model_name='assuranceruninput',
            constraint=models.UniqueConstraint(fields=('run', 'kind', 'source_id'), name='assin_source_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assuranceruninput',
            constraint=models.UniqueConstraint(fields=('run', 'subject_ordinal'), name='assin_subject_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assuranceruninput',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('ASSET', 'OBSERVATION'))), name='assin_kind_valid'),
        ),
        migrations.AddIndex(
            model_name='assuranceworkunit',
            index=models.Index(fields=['run', 'completed_at', 'ordinal'], name='assunit_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='assuranceworkunit',
            constraint=models.UniqueConstraint(fields=('run', 'ordinal'), name='assunit_ordinal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assuranceworkunit',
            constraint=models.CheckConstraint(condition=models.Q(('first_subject__gte', 1), ('last_subject__gte', models.F('first_subject'))), name='assunit_range_valid'),
        ),
        migrations.RunPython(identify_legacy_runs, migrations.RunPython.noop),
    ]
