import { useEffect, useMemo, useRef, useState } from 'react';
import { useAuth } from '../auth/AuthProvider';
import { ErrorState, LoadingState } from '../components/common/AsyncState';
import { ReportDefinition, ReportExport, ReportSnapshot, SafeReportValue } from '../services/reportDtos';
import { ReportFilters } from '../services/reportRepository';
import { invalidateReports, useLiveReport, useReportCatalog, useReportExports, useReportSnapshots, useSnapshotRows } from '../services/reportQueries';
import { reportRepository } from '../services/runtime';
import { useReferences } from '../services/referenceQueries';
import { ReferenceRecord } from '../services/assetDtos';
import { errorMessage } from '../services/apiError';

const pageSize=25;
const roles=['ADMIN','ASSET_MANAGER','ACCOUNTANT','DEPARTMENT_MANAGER'];
type Tab='live'|'snapshots'|'exports';
interface Intent{signature:string;key:string;userId:number;generation:number;createdAt:number}
function getIntent(current:Intent|null,kind:'snapshot'|'export',signature:string,userId:number,generation:number):Intent{if(current&&current.signature===signature&&current.userId===userId&&current.generation===generation)return current;const storageKey=`assetflow:f9:${kind}:${userId}:${generation}`;try{const saved=window.sessionStorage.getItem(storageKey);if(saved){const value:unknown=JSON.parse(saved);if(value&&typeof value==='object'&&'signature'in value&&'key'in value&&'userId'in value&&'generation'in value&&'createdAt'in value){const row=value as Intent;if(row.signature===signature&&row.userId===userId&&row.generation===generation&&Number.isSafeInteger(row.createdAt)&&Date.now()-row.createdAt<24*60*60*1000&&/^[0-9a-f-]{36}$/i.test(row.key))return row;}}}catch{/* Storage may be unavailable; the in-memory intent still protects this view. */}const intent={signature,key:crypto.randomUUID(),userId,generation,createdAt:Date.now()};try{window.sessionStorage.setItem(storageKey,JSON.stringify(intent));}catch{/* The backend idempotency key remains in memory for this view. */}return intent;}
function clearIntent(kind:'snapshot'|'export',userId:number,generation:number){try{window.sessionStorage.removeItem(`assetflow:f9:${kind}:${userId}:${generation}`);}catch{/* Storage may be unavailable. */}}

export function BackendReportsView(){
 const{user,role,generation,isCurrent}=useAuth();const authorized=roles.includes(role??'');
 const[tab,setTab]=useState<Tab>('live'),[reportType,setReportType]=useState('asset_register'),[filters,setFilters]=useState<Record<string,string>>({}),[page,setPage]=useState(1),[snapshotPage,setSnapshotPage]=useState(1),[exportPage,setExportPage]=useState(1),[rowPage,setRowPage]=useState(1),[selectedSnapshotId,setSelectedSnapshotId]=useState(''),[selectedExportId,setSelectedExportId]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[message,setMessage]=useState('');
 const snapshotIntent=useRef<Intent|null>(null),exportIntent=useRef<Intent|null>(null);
 const catalog=useReportCatalog(authorized),selectedDefinition=catalog.data?.find(item=>item.id===reportType)??catalog.data?.[0];
 const departments=useReferences('departments',authorized&&role!=='DEPARTMENT_MANAGER'&&!!selectedDefinition?.filters.includes('department'));
 const supportedFilters=selectedDefinition?.filters??[];
 const appliedFilters=useMemo(()=>Object.fromEntries(Object.entries(filters).filter(([key,value])=>supportedFilters.includes(key)&&value.trim()).map(([key,value])=>[key,value.trim()])),[filters,supportedFilters]);
 const queryFilters:ReportFilters={page,pageSize,...appliedFilters};
 const live=useLiveReport(selectedDefinition?.id??'',queryFilters,authorized&&tab==='live'&&!!selectedDefinition,selectedDefinition?.columns);
 const snapshots=useReportSnapshots(snapshotPage,pageSize,authorized&&tab==='snapshots');
 const exports=useReportExports(exportPage,pageSize,authorized&&tab==='exports');
 const selectedSnapshot=snapshots.data?.results.find(item=>item.id===selectedSnapshotId);
 const snapshotRows=useSnapshotRows(selectedSnapshotId,rowPage,pageSize,tab==='snapshots'&&selectedSnapshot?.status==='COMPLETED'&&selectedSnapshot?.schemaVersion===1);
 const selectedExport=exports.data?.results.find(item=>item.id===selectedExportId);
 const current=()=>isCurrent(generation);
 useEffect(()=>{if(catalog.data?.length&&!catalog.data.some(item=>item.id===reportType)){setReportType(catalog.data[0].id);setPage(1);}},[catalog.data,reportType]);
 useEffect(()=>{snapshotIntent.current=null;exportIntent.current=null;setUncertain(false);setMessage('');},[user?.id,generation]);
 function changeReport(value:string){setReportType(value);setFilters({});setPage(1);setSelectedSnapshotId('');}
 function setFilter(key:string,value:string){setFilters(old=>({...old,[key]:value}));setPage(1);}
 function signature(value:unknown){return JSON.stringify(value);}
 async function createSnapshot(){if(!selectedDefinition||!user)return;const body={report_type:selectedDefinition.id,filters:appliedFilters};const sig=signature(body);const intent=getIntent(snapshotIntent.current,'snapshot',sig,user.id,generation);snapshotIntent.current=intent;setBusy(true);setMessage('');setUncertain(false);try{const result=await reportRepository.createSnapshot({...body,idempotency_key:intent.key});if(!current())return;snapshotIntent.current=null;clearIntent('snapshot',user.id,generation);setSelectedSnapshotId(result.id);setTab('snapshots');setSnapshotPage(1);setMessage(`Django accepted snapshot ${result.id}. It is captured at request time when generation completes.`);}catch(error){if(!current())return;try{const matches=await findSnapshots(intent,body);if(!current())return;setUncertain(true);setMessage(matches.length?'A matching snapshot appears in history, but Django does not expose requester or idempotency key in this list. Retry will reuse the same key to resolve the exact request.':`${errorMessage(error)} Snapshot outcome is uncertain. A retry will reuse the same idempotency key.`);}catch{if(!current())return;setUncertain(true);setMessage('Snapshot request outcome is uncertain. Recheck history or retry with the same idempotency key.');}}finally{if(current()){await invalidateReports(user.id,generation);setBusy(false);}}}
 async function findSnapshots(intent:Intent,body:{report_type:string;filters:Record<string,string>}){const found:ReportSnapshot[]=[];for(let p=1;p<=100;p++){if(!current())return[];const response=await reportRepository.snapshots(p,100);for(const row of response.results){if(row.reportType===body.report_type&&signature(row.parameters)===signature(body.filters)&&row.requestedAt&&Date.parse(row.requestedAt)>=intent.createdAt-10_000)found.push(row);}if(!response.next)break;}return found;}
 async function createExport(snapshot:ReportSnapshot,format:'CSV'|'JSON'){if(!user)return;const body={source_snapshot_id:snapshot.id,format};const sig=signature(body);const intent=getIntent(exportIntent.current,'export',sig,user.id,generation);exportIntent.current=intent;setBusy(true);setMessage('');setUncertain(false);try{const result=await reportRepository.createExport({...body,idempotency_key:intent.key});if(!current())return;exportIntent.current=null;clearIntent('export',user.id,generation);setSelectedExportId(result.id);setTab('exports');setExportPage(1);setMessage(`Django queued ${format} export ${result.id} from completed snapshot ${snapshot.id}.`);}catch(error){if(!current())return;try{const match=await findExportByKey(intent.key);if(!current())return;if(match){exportIntent.current=null;clearIntent('export',user.id,generation);setSelectedExportId(match.id);setTab('exports');setExportPage(1);setMessage(`Django confirmed export ${match.id} from request history (${match.status}).`);}else{setUncertain(true);setMessage(`${errorMessage(error)} Export outcome is uncertain. A retry will reuse the same idempotency key.`);}}catch{if(!current())return;setUncertain(true);setMessage('Export request outcome is uncertain. Recheck history or retry with the same idempotency key.');}}finally{if(current()){await invalidateReports(user.id,generation);setBusy(false);}}}
 async function findExportByKey(key:string):Promise<ReportExport|null>{for(let p=1;p<=100;p++){if(!current())return null;const response=await reportRepository.exports(p,100);const match=response.results.find(item=>item.idempotencyKey===key);if(match)return match;if(!response.next)break;}return null;}
 async function downloadExport(item:ReportExport){if(!user)return;if(item.status!=='COMPLETED'||Date.parse(item.expiresAt)<=Date.now()||item.schemaVersion!==1){setMessage('Only supported, completed, unexpired exports can be downloaded.');return;}setBusy(true);setMessage('');try{const response=await reportRepository.downloadExport(item.id);if(!current())return;if(response.blob.size!==item.byteSize)throw new Error('Downloaded size does not match Django integrity metadata.');const digest=await crypto.subtle.digest('SHA-256',await response.blob.arrayBuffer());if(!current())return;const hash=[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');if(hash!==item.sha256)throw new Error('Downloaded file hash does not match Django integrity metadata.');const filename=safeReportFilename(response.contentDisposition,`assetflow-report-${item.id}.${item.format.toLowerCase()}`);const url=URL.createObjectURL(response.blob);try{const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.rel='noopener';anchor.click();setMessage(`Authenticated ${item.format} download verified against Django size and SHA256 metadata.`);}finally{window.setTimeout(()=>URL.revokeObjectURL(url),0);}}catch(error){if(!current())return;setMessage(error instanceof Error&&error.message.includes('integrity metadata')?error.message:`${errorMessage(error)} The export remains available only if Django confirms it is completed and unexpired.`);}finally{if(current()){await invalidateReports(user.id,generation);setBusy(false);}}}

 if(!authorized)return <section className="p-6"><h1 className="text-xl font-bold">Reports</h1><p role="alert" className="mt-3 rounded border bg-white p-4">Your role cannot access reporting.</p></section>;
 return <main className="space-y-5 p-4 md:p-6" aria-busy={busy}>
  <header className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Django reporting API</p><h1 className="mt-1 text-2xl font-bold">Reports Center</h1><p className="mt-2 text-sm text-slate-600">Live reports query current scoped data. Snapshots are durable captures at a point in time; their “Captured at” timestamp is not a historical reconstruction.</p></header>
  <nav aria-label="Reporting sections" className="flex flex-wrap gap-2">{(['live','snapshots','exports'] as const).map(value=><button key={value} aria-current={tab===value?'page':undefined} className={`rounded px-4 py-2 text-sm font-semibold ${tab===value?'bg-[#00288e] text-white':'border bg-white'}`} onClick={()=>setTab(value)}>{value==='live'?'Live reports':value==='snapshots'?'Snapshots':'Exports'}</button>)}</nav>
  {catalog.isPending?<LoadingState label="Loading report catalog…"/>:catalog.isError?<ErrorState error={catalog.error} retry={()=>void catalog.refetch()}/>:tab==='live'&&<>
   <section className="rounded-xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-[minmax(16rem,1fr)_2fr]"><label className="text-sm font-medium">Report<select className="mt-1 block w-full rounded border p-2" value={selectedDefinition?.id??''} onChange={event=>changeReport(event.target.value)}>{catalog.data?.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><p className="self-end text-sm text-slate-600">{selectedDefinition?.columns.length??0} columns · Django role and department scope apply.</p></div>
    {selectedDefinition&&<div className="mt-4 flex flex-wrap items-end gap-3">{supportedFilters.includes('department')&&role!=='DEPARTMENT_MANAGER'&&<label className="text-sm">Department<select className="mt-1 block rounded border p-2" value={filters.department??''} onChange={event=>setFilter('department',event.target.value)}><option value="">All in scope</option>{departments.data?.map((item:ReferenceRecord)=><option key={item.id} value={item.id}>{item.name} · {item.code}</option>)}</select></label>}{supportedFilters.map(filter=>filter==='department'?null:filter==='date_from'||filter==='date_to'?<label key={filter} className="text-sm">{filter==='date_from'?'From':'To'}<input type="date" className="mt-1 block rounded border p-2" value={filters[filter]??''} onChange={event=>setFilter(filter,event.target.value)}/></label>:<label key={filter} className="text-sm">{filter.replaceAll('_',' ')}<input className="mt-1 block rounded border p-2" maxLength={200} value={filters[filter]??''} onChange={event=>setFilter(filter,event.target.value)} /></label>)}</div>}
   </section>
   <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Live result · {selectedDefinition?.label}</h2><p className="text-sm text-slate-600">Current Django query result. Request a separate durable snapshot to preserve these rows.</p></div>{selectedDefinition?.snapshotSupported&&<button disabled={busy||uncertain||!selectedDefinition} onClick={()=>void createSnapshot()} className="rounded bg-[#00288e] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?'Working…':'Capture snapshot'}</button>}</div>
   {live.isPending?<LoadingState label="Loading live report…"/>:live.isError?<ErrorState error={live.error} retry={()=>void live.refetch()}/>:!live.data?.results.length?<p role="status" className="py-8 text-center text-slate-600">No rows match the current report filters.</p>:selectedDefinition&&<><ReportTable columns={selectedDefinition.columns} rows={live.data.results}/><Pager page={page} count={live.data.count} next={live.data.next} previous={live.data.previous} setPage={setPage}/></>}</section>
  </>}
  {tab==='snapshots'&&<section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Durable report snapshots</h2><p className="text-sm text-slate-600">Snapshots capture report rows using request-time role and department scope. “As of” is the database capture time.</p></div><button className="rounded border px-3 py-2 text-sm" onClick={()=>void snapshots.refetch()}>Refresh</button></div>{snapshots.isPending?<LoadingState label="Loading snapshots…"/>:snapshots.isError?<ErrorState error={snapshots.error} retry={()=>void snapshots.refetch()}/>:snapshots.data?.results.length===0?<p role="status" className="py-8 text-center text-slate-600">No snapshots have been requested.</p>:<div className="mt-4 space-y-3">{snapshots.data?.results.map(item=><article key={item.id} className={`rounded border p-4 ${item.id===selectedSnapshotId?'border-blue-700 ring-1 ring-blue-700':''}`}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{labelFor(catalog.data,item.reportType)} · {item.status}</h3><p className="mt-1 text-sm">Requested {dateTime(item.requestedAt)} · {item.asOf?`Captured at ${dateTime(item.asOf)}`:'Not captured yet'} · schema v{item.schemaVersion} · {item.rowCount} rows</p><p className="mt-1 text-xs text-slate-500">Snapshot {item.id}{item.scopeDepartmentId?` · department scope ${item.scopeDepartmentId}`:''}{item.generatedAt?` · generated ${dateTime(item.generatedAt)}`:''}</p>{item.status==='FAILED'&&<p className="mt-1 text-sm text-rose-700">Snapshot generation failed. No completed rows are available.</p>}{item.status==='COMPLETED'&&item.schemaVersion!==1&&<p role="alert" className="mt-1 text-sm text-amber-800">Snapshot schema v{item.schemaVersion} is unsupported by this frontend; rows and exports are withheld.</p>}</div>{item.status==='COMPLETED'&&item.schemaVersion===1&&<div className="flex gap-2"><button className="rounded border px-3 py-1.5 text-sm" onClick={()=>{setSelectedSnapshotId(item.id);setRowPage(1)}}>Inspect rows</button><button className="rounded border px-3 py-1.5 text-sm" onClick={()=>{setSelectedSnapshotId(item.id);setTab('exports');setSelectedExportId('')}}>Create export</button></div>}</div></article>)}</div>}{snapshots.data&&<Pager page={snapshotPage} count={snapshots.data.count} next={snapshots.data.next} previous={snapshots.data.previous} setPage={setSnapshotPage}/>}</section>}
  {tab==='snapshots'&&selectedSnapshot&&selectedSnapshot.status==='COMPLETED'&&selectedSnapshot.schemaVersion===1&&<section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Captured rows · {labelFor(catalog.data,selectedSnapshot.reportType)}</h2><p className="mb-3 text-sm text-slate-600">Snapshot created at {dateTime(selectedSnapshot.asOf)} · immutable captured rows, schema v1.</p>{snapshotRows.isPending?<LoadingState label="Loading captured rows…"/>:snapshotRows.isError?<ErrorState error={snapshotRows.error} retry={()=>void snapshotRows.refetch()}/>:!snapshotRows.data?.results.length?<p className="py-4 text-sm">This completed snapshot contains no rows.</p>:catalog.data?.find(x=>x.id===selectedSnapshot.reportType)&&snapshotRows.data.results.some(row=>!sameColumns(Object.keys(row.payload),catalog.data!.find(x=>x.id===selectedSnapshot.reportType)!.columns))?<p role="alert" className="text-sm text-rose-700">Snapshot rows do not match the registered report columns. Rendering is withheld.</p>:<><ReportTable columns={catalog.data?.find(x=>x.id===selectedSnapshot.reportType)?.columns??Object.keys(snapshotRows.data.results[0].payload)} rows={snapshotRows.data.results.map(row=>row.payload)}/><Pager page={rowPage} count={snapshotRows.data.count} next={snapshotRows.data.next} previous={snapshotRows.data.previous} setPage={setRowPage}/></>}</section>}
  {tab==='exports'&&<><section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Durable exports</h2><p className="text-sm text-slate-600">Exports render only completed snapshot rows. Django publishes completion only after private storage readback and integrity verification.</p></div><button className="rounded border px-3 py-2 text-sm" onClick={()=>void exports.refetch()}>Refresh</button></div>{exports.isPending?<LoadingState label="Loading exports…"/>:exports.isError?<ErrorState error={exports.error} retry={()=>void exports.refetch()}/>:exports.data?.results.length===0?<p role="status" className="py-8 text-center text-slate-600">No export jobs have been requested.</p>:<div className="mt-4 space-y-3">{exports.data?.results.map(item=><article key={item.id} className={`rounded border p-4 ${item.id===selectedExportId?'border-blue-700 ring-1 ring-blue-700':''}`}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{item.format} export · {item.status}</h3><p className="mt-1 text-sm">Source snapshot {item.sourceSnapshotId} · requested {dateTime(item.requestedAt)}{item.completedAt?` · completed ${dateTime(item.completedAt)}`:''}</p><p className="mt-1 text-sm">schema v{item.schemaVersion} · {item.rowCount} rows{item.byteSize!==null?` · ${item.byteSize.toLocaleString()} bytes`:''}{item.sha256?` · SHA256 ${item.sha256}`:''}</p><p className="mt-1 text-xs text-slate-500">Expires {dateTime(item.expiresAt)} · export {item.id}</p>{item.status==='FAILED'&&<p className="mt-1 text-sm text-rose-700">Export failed. Request a new export from the completed snapshot.</p>}{item.schemaVersion!==1&&<p role="alert" className="mt-1 text-sm text-amber-800">Export schema v{item.schemaVersion} is unsupported; download is disabled.</p>}</div>{item.status==='COMPLETED'&&item.schemaVersion===1&&Date.parse(item.expiresAt)>Date.now()&&<button disabled={busy} onClick={()=>void downloadExport(item)} className="h-fit rounded bg-[#00288e] px-3 py-2 text-sm text-white disabled:opacity-50">Authenticated download</button>}</div></article>)}</div>}{exports.data&&<Pager page={exportPage} count={exports.data.count} next={exports.data.next} previous={exports.data.previous} setPage={setExportPage}/>}</section>
   {selectedSnapshot&&selectedSnapshot.status==='COMPLETED'&&selectedSnapshot.schemaVersion===1&&<section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Export completed snapshot · {labelFor(catalog.data,selectedSnapshot.reportType)}</h2><p className="mt-1 text-sm text-slate-600">Source snapshot {selectedSnapshot.id}, captured at {dateTime(selectedSnapshot.asOf)} · {selectedSnapshot.rowCount} rows.</p><div className="mt-3 flex gap-2">{(['CSV','JSON'] as const).map(format=><button key={format} disabled={busy||uncertain} onClick={()=>void createExport(selectedSnapshot,format)} className="rounded border px-4 py-2 text-sm font-semibold disabled:opacity-50">Request {format}</button>)}</div></section>}</>}
  {message&&<div role={uncertain?'alert':'status'} className="rounded border bg-white p-3 text-sm">{message}{uncertain&&<button className="ml-3 rounded border px-3 py-1" onClick={()=>{setUncertain(false);setMessage('Recheck completed. If the request is still uncertain, retrying will reuse its idempotency key.');void Promise.all([snapshots.refetch(),exports.refetch()]);}}>Recheck history</button>}</div>}
 </main>;
}

export function safeReportFilename(header:string|null,fallback:string){if(!header)return fallback;const extended=header.match(/filename\*=UTF-8''([^;]+)/i);const plain=header.match(/filename="?([^";]+)"?/i);let value=extended?decodeURIComponent(extended[1]):plain?.[1];if(!value)return fallback;value=value.split(/[\\/]/).at(-1)??'';value=value.replace(/[\u0000-\u001f<>:"|?*]/g,'_').trim();return value&&value!=='.'&&value!=='..'?value.slice(0,180):fallback;}
function labelFor(catalog:ReportDefinition[]|undefined,type:string){return catalog?.find(item=>item.id===type)?.label??type.replaceAll('_',' ');}
function sameColumns(actual:string[],expected:string[]){return actual.length===expected.length&&new Set(actual).size===actual.length&&expected.every(column=>actual.includes(column));}
function dateTime(value:string|null){return value?new Date(value).toLocaleString():'—';}
function valueText(key:string,value:SafeReportValue){if(value===null)return '—';if(typeof value==='boolean')return value?'Yes':'No';if(typeof value==='object')return JSON.stringify(value);if(typeof value==='string'&&/(?:_at|_date|^timestamp$)$/.test(key)&&!Number.isNaN(Date.parse(value)))return new Date(value).toLocaleString();if(typeof value==='string'&&/^-?\d[\d,]*(?:\.\d+)?$/.test(value)&&/(?:cost|value|amount|price|proceeds|depreciation|quantity|gain|loss|carrying|purchase)/i.test(key))return exactGrouped(value);return String(value);}
function exactGrouped(value:string){const negative=value.startsWith('-'),raw=negative?value.slice(1):value,[whole,fraction]=raw.split('.');const grouped=whole.replace(/\B(?=(\d{3})+(?!\d))/g,',');return `${negative?'-':''}${grouped}${fraction===undefined?'':`.${fraction}`}`;}
function ReportTable({columns,rows}:{columns:string[];rows:Record<string,SafeReportValue>[]}){const displayColumns=columns.filter(column=>column!=='id'&&!column.endsWith('_id'));const actual=displayColumns.length?displayColumns:columns;return <div className="overflow-x-auto"><table className="min-w-full border-collapse text-left text-sm"><thead className="bg-[#eff4ff] text-xs uppercase text-slate-600"><tr>{actual.map(column=><th key={column} scope="col" className="whitespace-nowrap border-b px-3 py-2">{column.replaceAll('_',' ')}</th>)}</tr></thead><tbody className="divide-y">{rows.map((row,index)=><tr key={String(row.id??row.ordinal??index)} className="hover:bg-slate-50">{actual.map(column=><td key={column} className="max-w-80 whitespace-nowrap border-b px-3 py-2" title={typeof row[column]==='string'?row[column]??undefined:undefined}>{valueText(column,row[column]??null)}</td>)}</tr>)}</tbody></table></div>;}
function Pager({page,count,next,previous,setPage}:{page:number;count:number;next:string|null;previous:string|null;setPage:(n:number)=>void}){return <div className="mt-4 flex items-center justify-between"><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={!previous} onClick={()=>setPage(page-1)}>Previous</button><span className="text-sm">{count} records · Page {page}</span><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={!next} onClick={()=>setPage(page+1)}>Next</button></div>;}
