import { useState } from 'react';
import { useAuth } from '../auth/AuthProvider';
import { ErrorState, LoadingState } from '../components/common/AsyncState';
import { useAllAssets } from '../services/assetQueries';
import { errorMessage } from '../services/apiError';
import { useDisposals } from '../services/disposalQueries';
import { useDisposalAction } from '../services/disposalMutations';
import { disposalRepository } from '../services/runtime';
import { DisposalRecord, formatDisposalMoney } from '../services/disposalDtos';
import { canManageAssets } from '../services/acquisitionQueries';

const pageSize=25;
export function BackendDisposalsView({onNavigate,onSelectAsset,initialAssetId=''}:{onNavigate:(route:string)=>void;onSelectAsset:(id:string)=>void;initialAssetId?:string}){
  const {user,role,generation,isCurrent}=useAuth();const writable=canManageAssets(role);const [page,setPage]=useState(1);const [status,setStatus]=useState('');const [search,setSearch]=useState('');const [assetId,setAssetId]=useState(initialAssetId);const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10));const [method,setMethod]=useState('SALE');const [proceeds,setProceeds]=useState('0.00');const [reason,setReason]=useState('');const [message,setMessage]=useState('');const [uncertain,setUncertain]=useState(false);
  const rows=useDisposals({page,pageSize,status:status||undefined,search:search||undefined,ordering:'-disposal_date'});const assets=useAllAssets({pageSize:100,search:'',status:'ACTIVE',category:'',department:'',location:'',ordering:'tag'},writable);const action=useDisposalAction();
  const canReconcile=()=>isCurrent(generation);
  const withTransition=async(record:DisposalRecord,operation:()=>Promise<DisposalRecord>,expected:string)=>{setMessage('');setUncertain(false);const completionMayCommit=expected==='COMPLETED';try{const result=await action.run(operation,completionMayCommit);if(!canReconcile())return;setMessage(`Disposal ${result.id} is now ${result.status}.`);}catch(error){if(!canReconcile())return;try{const current=await disposalRepository.get(record.id);if(!canReconcile())return;if(current.status===expected){setMessage(`Disposal ${current.id} is now ${current.status}.`);}else{setMessage(`${errorMessage(error)} Current status: ${current.status}. Review it before trying again.`);}}catch{if(!canReconcile())return;setUncertain(true);setMessage('The outcome is uncertain. Reload disposal history before taking another action.');}}};
  const create=async()=>{setMessage('');setUncertain(false);if(!assetId||!reason.trim()){setMessage('Choose an active asset and enter a reason.');return;}const input={asset_id:assetId,disposal_date:date,disposal_method:method,reason:reason.trim(),proceeds};try{const before=await disposalRepository.list({page:1,pageSize:100,asset:assetId,status:'DRAFT',ordering:'-created_at'});if(!canReconcile())return;const known=new Set(before.results.map(row=>row.id));try{const created=await action.run(()=>disposalRepository.create(input));if(!canReconcile())return;setMessage(`Draft disposal ${created.id} created. Submit it for approval when ready.`);setReason('');}catch(error){if(!canReconcile())return;try{const after=await disposalRepository.list({page:1,pageSize:100,asset:assetId,status:'DRAFT',ordering:'-created_at'});if(!canReconcile())return;const created=after.results.filter(row=>!known.has(row.id)&&row.status==='DRAFT'&&row.assetId===input.asset_id&&row.disposalDate===input.disposal_date&&row.method===input.disposal_method&&row.proceeds===input.proceeds&&row.reason===input.reason&&row.requestedByEmail.toLowerCase()===(user?.email??'').toLowerCase());if(created.length===1){setMessage(`Draft disposal ${created[0].id} was created. Submit it for approval when ready.`);}else if(created.length>1){setUncertain(true);setMessage('Multiple matching drafts were found. Review history before acting.');}else{setMessage(errorMessage(error));}}catch{if(!canReconcile())return;setUncertain(true);setMessage('The outcome is uncertain. Reload disposal history before attempting another disposal.');}}}catch(error){if(!canReconcile())return;setMessage(errorMessage(error));}};
  return <section className="space-y-5 p-4 md:p-6" aria-busy={rows.isFetching||action.pending}>
    <header className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Django API · Disposal workflow</p><h1 className="mt-1 text-2xl font-bold">Disposals & derecognition</h1><p className="mt-2 text-sm text-slate-600">Django calculates and records carrying amount and gain or loss at completion. Proceeds are captured as an exact decimal amount.</p></header>
    {writable&&<section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Create disposal draft</h2><p className="mt-1 text-sm text-slate-600">A draft does not derecognize the asset. Submission, a separate approval, and completion are required.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
      <label className="text-sm">Active asset<select className="mt-1 w-full rounded border p-2" value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">Select asset</option>{assets.data?.data.filter(asset=>asset.status==='ACTIVE').map(asset=><option key={asset.id} value={asset.id}>{asset.tag} · {asset.name}</option>)}</select></label>
      <label className="text-sm">Disposal date<input type="date" className="mt-1 w-full rounded border p-2" value={date} onChange={e=>setDate(e.target.value)}/></label>
      <label className="text-sm">Method<select className="mt-1 w-full rounded border p-2" value={method} onChange={e=>setMethod(e.target.value)}>{['SALE','SCRAP','DONATION','WRITE_OFF','TRANSFER_OUT'].map(v=><option key={v}>{v}</option>)}</select></label>
      <label className="text-sm">Proceeds<input inputMode="decimal" className="mt-1 w-full rounded border p-2" value={proceeds} onChange={e=>setProceeds(e.target.value)} aria-describedby="disposal-proceeds-help"/><span id="disposal-proceeds-help" className="text-xs text-slate-500">Nonnegative amount, two decimals</span></label>
      <label className="text-sm">Reason<input className="mt-1 w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)} maxLength={4000}/></label>
    </div>{assets.isPending&&<p role="status" className="mt-3 text-sm text-slate-600">Loading active assets…</p>}{assets.isError&&<ErrorState error={assets.error} retry={()=>void assets.refetch()}/ >}{assets.data?.total===0&&<p role="status" className="mt-3 text-sm text-slate-600">No active assets are eligible for disposal.</p>}<button disabled={action.pending||uncertain||!assetId||!assets.data?.data.some(asset=>asset.id===assetId&&asset.status==='ACTIVE')||!reason.trim()||!/^\d{1,18}\.\d{2}$/.test(proceeds)} onClick={()=>void create()} className="mt-4 rounded bg-rose-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{action.pending?'Saving…':'Create draft'}</button></section>}
    <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Disposal history</h2><p className="text-sm text-slate-600">{rows.data?`${rows.data.count} records`:'Records returned by Django'}</p></div><div className="flex gap-2"><label className="text-sm">Status<select className="ml-2 rounded border p-2" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{['DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','CANCELLED','COMPLETED'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">Search<input className="ml-2 rounded border p-2" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Asset or reason"/></label></div></div>
      {rows.isPending ? <LoadingState label="Loading disposal history…"/> : rows.isError ? <ErrorState error={rows.error} retry={()=>void rows.refetch()}/> : rows.data.results.length===0 ? <p role="status" className="py-8 text-center text-slate-600">No disposal records match these filters.</p> : (
        <div className="mt-4 space-y-3">{rows.data.results.map(record => {
          const operations={submit:()=>disposalRepository.submit(record.id),approve:()=>disposalRepository.approve(record.id),complete:()=>disposalRepository.complete(record.id),cancel:()=>disposalRepository.cancel(record.id,''),reject:()=>disposalRepository.reject(record.id,'')};
          return <DisposalCard key={record.id} record={record} writable={writable} currentEmail={user?.email??''} pending={action.pending||uncertain} onAsset={()=>onSelectAsset(record.assetId)} onAction={kind=>void withTransition(record,operations[kind],({submit:'PENDING_APPROVAL',approve:'APPROVED',complete:'COMPLETED',cancel:'CANCELLED',reject:'REJECTED'} as const)[kind])}/>;
        })}</div>
      )}
      {!rows.isError&&rows.data&&<div className="mt-4 flex items-center justify-between"><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={page<=1||!rows.data.previous} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="text-sm">Page {page}</span><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={!rows.data.next} onClick={()=>setPage(p=>p+1)}>Next</button></div>}
    </section>
    {message&&<div role={uncertain?'alert':'status'} className="flex flex-wrap items-center justify-between gap-3 rounded border bg-white p-3 text-sm"><span>{message}</span>{uncertain&&<button onClick={()=>void rows.refetch().then(result=>{if(result.isSuccess){setUncertain(false);setMessage('Disposal history refreshed. Review the current statuses before continuing.');}})} className="rounded border px-3 py-1.5">Recheck history</button>}</div>}
  </section>;
}
function DisposalCard({record,writable,currentEmail,pending,onAsset,onAction}:{record:DisposalRecord;writable:boolean;currentEmail:string;pending:boolean;onAsset:()=>void;onAction:(kind:'submit'|'approve'|'complete'|'cancel'|'reject')=>void}){
  const requesterIsSelf=record.requestedByEmail.toLowerCase()===currentEmail.toLowerCase();return <article className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{record.status}</span><span className="rounded bg-slate-100 px-2 py-1 text-xs">{record.method}</span><span className="text-sm text-slate-600">{record.disposalDate}</span></div><button onClick={onAsset} className="mt-1 text-left font-semibold text-blue-800 underline">{record.assetTag} · {record.assetName}</button><p className="mt-1 text-sm">{record.reason}</p><p className="mt-1 text-xs text-slate-500">Requested by {record.requestedByEmail}{record.approvedByEmail?` · Approved by ${record.approvedByEmail}`:''}{record.completedAt?` · Completed ${record.completedAt}`:''}</p></div><div className="grid grid-cols-2 gap-x-5 gap-y-1 text-right text-sm"><span className="text-slate-500">Proceeds</span><b>{record.currency} {formatDisposalMoney(record.proceeds)}</b>{record.carryingAmount!==null&&<><span className="text-slate-500">Carrying amount</span><b>{record.currency} {formatDisposalMoney(record.carryingAmount)}</b></>}{record.gainOrLoss!==null&&<><span className="text-slate-500">Gain / (loss)</span><b>{record.currency} {formatDisposalMoney(record.gainOrLoss)}</b></>}</div></div>
    {writable&&<div className="mt-3 flex flex-wrap gap-2">{record.status==='DRAFT'&&<button disabled={pending} onClick={()=>onAction('submit')} className="rounded bg-blue-800 px-3 py-1.5 text-sm text-white disabled:opacity-50">Submit for approval</button>}{record.status==='PENDING_APPROVAL'&&!requesterIsSelf&&<><button disabled={pending} onClick={()=>onAction('approve')} className="rounded bg-blue-800 px-3 py-1.5 text-sm text-white disabled:opacity-50">Approve</button><button disabled={pending} onClick={()=>onAction('reject')} className="rounded border px-3 py-1.5 text-sm disabled:opacity-50">Reject</button></>}{record.status==='APPROVED'&&<button disabled={pending} onClick={()=>onAction('complete')} className="rounded bg-rose-700 px-3 py-1.5 text-sm text-white disabled:opacity-50">Complete derecognition</button>}{['DRAFT','PENDING_APPROVAL','APPROVED'].includes(record.status)&&<button disabled={pending} onClick={()=>onAction('cancel')} className="rounded border px-3 py-1.5 text-sm disabled:opacity-50">Cancel</button>}</div>}
    {record.status==='COMPLETED'&&<p className="mt-2 text-xs text-slate-600">Backend snapshot · capitalized cost {record.capitalizedCost===null?'—':`${record.currency} ${formatDisposalMoney(record.capitalizedCost)}`} · accumulated depreciation {record.accumulatedDepreciation===null?'—':`${record.currency} ${formatDisposalMoney(record.accumulatedDepreciation)}`}</p>}
  </article>;
}
