import { useState } from 'react';
import { useAuth } from '../auth/AuthProvider';
import { ErrorState, LoadingState } from '../components/common/AsyncState';
import { useVerificationCampaigns } from '../services/verificationQueries';
import { AssuranceFinding, AssuranceRun } from '../services/assuranceDtos';
import { canManageAssets } from '../services/acquisitionQueries';
import { AssuranceFilters } from '../services/assuranceRepository';
import { invalidateAssurance, useAssuranceFindings, useAssuranceRun, useAssuranceRunFindings, useAssuranceRuns } from '../services/assuranceQueries';
import { assuranceRepository } from '../services/runtime';
import { errorMessage } from '../services/apiError';

const pageSize=25;
const terminalRuns=['COMPLETED','FAILED','CANCELLED'];
const readableRoles=['ADMIN','ASSET_MANAGER','ACCOUNTANT','DEPARTMENT_MANAGER'];
export function BackendAssuranceView({onSelectAsset}:{onSelectAsset:(id:string)=>void}){
 const{user,role,generation,isCurrent}=useAuth();const manager=canManageAssets(role);
 const[tab,setTab]=useState<'runs'|'findings'>('runs'),[runPage,setRunPage]=useState(1),[findingPage,setFindingPage]=useState(1),[runFindingPage,setRunFindingPage]=useState(1),[runStatus,setRunStatus]=useState(''),[runTypeFilter,setRunTypeFilter]=useState(''),[findingStatus,setFindingStatus]=useState(''),[findingType,setFindingType]=useState(''),[severity,setSeverity]=useState(''),[source,setSource]=useState(''),[search,setSearch]=useState(''),[selectedRunId,setSelectedRunId]=useState('');
 const[createType,setCreateType]=useState('FULL'),[campaignId,setCampaignId]=useState(''),[staleDays,setStaleDays]=useState(365),[resolutionNotes,setResolutionNotes]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[message,setMessage]=useState('');
 const runFilters:AssuranceFilters={page:runPage,pageSize,run_type:runTypeFilter||undefined,status:runStatus||undefined};
 const findingFilters:AssuranceFilters={page:findingPage,pageSize,search:search||undefined,status:findingStatus||undefined,finding_type:findingType||undefined,severity:severity||undefined,source:source||undefined};
 const authorized=readableRoles.includes(role??'');const runs=useAssuranceRuns(runFilters,authorized),findings=useAssuranceFindings(findingFilters,tab==='findings'&&authorized);
 const campaigns=useVerificationCampaigns({page:1,pageSize:100,status:'COMPLETED'},manager);
 const selectedRun=useAssuranceRun(selectedRunId,!!selectedRunId);
 const runFindingFilters:AssuranceFilters={page:runFindingPage,pageSize};
 const runFindings=useAssuranceRunFindings(selectedRunId,runFindingFilters,!!selectedRunId&&selectedRun.data?.status==='COMPLETED');
 const current=()=>isCurrent(generation);
 async function allPendingRuns(runType:string,campaign:string){const all:AssuranceRun[]=[];for(let page=1;page<=1000;page++){if(!current())throw new Error('Session changed.');const result=await assuranceRepository.runs({page,pageSize:100,run_type:runType,status:'PENDING',verification_campaign:campaign||undefined});all.push(...result.results);if(!result.next)return all;}throw new Error('Run history is too large to safely recheck.');}
 async function createRun(){setMessage('');setUncertain(false);setBusy(true);let before:AssuranceRun[]=[];let submitted=false;const started=Date.now();const input={run_type:createType,stale_after_days:staleDays,...(createType==='PHYSICAL'||campaignId?{verification_campaign_id:campaignId}: {})};try{if(createType==='PHYSICAL'&&!campaignId){setMessage('Physical runs require a completed verification campaign.');return;}before=await allPendingRuns(createType,campaignId);if(!current())return;submitted=true;const created=await assuranceRepository.createRun(input);if(!current())return;setSelectedRunId(created.id);setMessage(`Run ${created.id} created in ${created.status}. Execution starts only when you select Execute.`);}catch(error){if(!current())return;if(!submitted){setMessage(errorMessage(error));return;}try{const after=await allPendingRuns(createType,campaignId);if(!current())return;const prior=new Set(before.map(run=>run.id));const matches=after.filter(run=>!prior.has(run.id)&&run.runType===createType&&run.verificationCampaignId===(input.verification_campaign_id??null)&&run.staleAfterDays===staleDays&&run.startedByEmail?.toLowerCase()===(user?.email??'').toLowerCase()&&Date.parse(run.createdAt)>=started-10_000);if(matches.length===1){setSelectedRunId(matches[0].id);setMessage(`Run ${matches[0].id} was created; Django confirmed it in run history.`);}else{setUncertain(true);setMessage(matches.length?'Several new runs match this request. Review run history before creating another.':'Run creation could not be confirmed. Recheck run history before retrying.');}}catch{if(!current())return;setUncertain(true);setMessage('Run creation outcome is uncertain. Recheck run history before creating another.');}}finally{if(current()){await invalidateAssurance(user!.id,generation);setBusy(false);}}}
 async function runAction(run:AssuranceRun,action:'execute'|'cancel'){setMessage('');setUncertain(false);setBusy(true);try{const updated=action==='execute'?await assuranceRepository.executeRun(run.id):await assuranceRepository.cancelRun(run.id);if(!current())return;setSelectedRunId(updated.id);setMessage(action==='execute'&&updated.status==='RUNNING'?'Execution was accepted; Django reports RUNNING. Background processing will continue.':`Run status is ${updated.status}.`);}catch(error){if(!current())return;try{const actual=await assuranceRepository.run(run.id);if(!current())return;setSelectedRunId(actual.id);if(action==='execute'&&actual.status==='RUNNING')setMessage('Django confirms the run is RUNNING. Do not dispatch it again.');else if(action==='execute'&&actual.status==='COMPLETED')setMessage('Django confirms the run completed.');else if(action==='cancel'&&actual.status==='CANCELLED')setMessage('Django confirms the run was cancelled.');else if(actual.status==='PENDING')setMessage(`${errorMessage(error)} Django still reports PENDING; execution may be attempted again after reviewing this state.`);else setMessage(`${errorMessage(error)} Current Django status: ${actual.status}.`);}catch{if(!current())return;setUncertain(true);setMessage('The run action outcome is uncertain. Recheck the authoritative run state before another action.');}}finally{if(current()){await invalidateAssurance(user!.id,generation);setBusy(false);}}}
 async function findingAction(finding:AssuranceFinding,action:'review'|'resolve'|'accept'|'reject'){setMessage('');setUncertain(false);setBusy(true);try{const updated=await assuranceRepository.findingAction(finding.id,action,resolutionNotes.trim());if(!current())return;setMessage(`Finding ${updated.id} is now ${updated.status}. Resolving a finding does not change the asset register.`);setResolutionNotes('');}catch(error){if(!current())return;try{const actual=await assuranceRepository.finding(finding.id);if(!current())return;const expected=({review:'UNDER_REVIEW',resolve:'RESOLVED',accept:'ACCEPTED',reject:'REJECTED'} as const)[action];setMessage(actual.status===expected?`Django confirms finding status ${actual.status}.`:`${errorMessage(error)} Current Django status: ${actual.status}.`);}catch{if(!current())return;setUncertain(true);setMessage('Finding action outcome is uncertain. Recheck the finding and its occurrence history before another action.');}}finally{if(current()){await invalidateAssurance(user!.id,generation);setBusy(false);}}}
 if(!readableRoles.includes(role??''))return <section className="p-6"><h1 className="text-xl font-bold">Assurance</h1><p role="alert" className="mt-3 rounded border bg-white p-4">Your role cannot access assurance records.</p></section>;
 return <section className="space-y-5 p-4 md:p-6" aria-busy={busy}>
  <header className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Django API · Deterministic assurance</p><h1 className="mt-1 text-2xl font-bold">Assurance & reconciliation</h1><p className="mt-2 text-sm text-slate-600">Django captures frozen inputs, evaluates deterministic controls, and atomically publishes findings. Findings are control records; resolving one never edits an asset.</p></header>
  <nav aria-label="Assurance sections" className="flex gap-2">{(['runs','findings'] as const).map(item=><button key={item} onClick={()=>setTab(item)} aria-current={tab===item?'page':undefined} className={`rounded px-4 py-2 text-sm font-semibold ${tab===item?'bg-[#00288e] text-white':'border bg-white'}`}>{item==='runs'?'Runs':'Public findings'}</button>)}</nav>
  {tab==='runs'&&<>
   {role==='DEPARTMENT_MANAGER'&&<p role="status" className="rounded border bg-white p-4 text-sm">Your role can review department-scoped findings. Run history is restricted by the assurance API.</p>}
   {manager&&<section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Create assurance run</h2><p className="mt-1 text-sm text-slate-600">Creation stores a pending run. Execution is a separate background-dispatched action.</p><div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-sm">Run type<select className="mt-1 block rounded border p-2" value={createType} onChange={e=>setCreateType(e.target.value)}>{['FULL','PHYSICAL','FINANCIAL','OPERATIONAL'].map(value=><option key={value}>{value}</option>)}</select></label>{(createType==='PHYSICAL'||campaignId)&&<label className="text-sm">Completed verification campaign<select className="mt-1 block rounded border p-2" value={campaignId} onChange={e=>setCampaignId(e.target.value)}><option value="">{createType==='PHYSICAL'?'Select completed campaign':'No campaign context'}</option>{campaigns.data?.results.map(c=><option key={c.id} value={c.id}>{c.name} · {c.completedAt??c.startDate}</option>)}</select></label>}<label className="text-sm">Stale after days<input type="number" min={1} max={32767} className="mt-1 block w-36 rounded border p-2" value={staleDays} onChange={e=>setStaleDays(Number(e.target.value))}/></label><button disabled={busy||uncertain||staleDays<1||staleDays>32767||(createType==='PHYSICAL'&&!campaignId)} onClick={()=>void createRun()} className="rounded bg-[#00288e] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?'Saving…':'Create pending run'}</button></div>{campaigns.isError&&createType==='PHYSICAL'&&<ErrorState error={campaigns.error} retry={()=>void campaigns.refetch()}/>}</section>}
   <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Run history</h2><p className="text-sm text-slate-600">Progress and state are returned by Django. Active runs refresh every five seconds.</p></div><div className="flex gap-2"><label className="text-sm">Type<select className="ml-2 rounded border p-2" value={runTypeFilter} onChange={e=>{setRunTypeFilter(e.target.value);setRunPage(1)}}><option value="">All</option>{['FULL','PHYSICAL','FINANCIAL','OPERATIONAL'].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-sm">Status<select className="ml-2 rounded border p-2" value={runStatus} onChange={e=>{setRunStatus(e.target.value);setRunPage(1)}}><option value="">All</option>{['PENDING','RUNNING','COMPLETED','FAILED','CANCELLED'].map(value=><option key={value}>{value}</option>)}</select></label></div></div>
   {runs.isPending?<LoadingState label="Loading assurance runs…"/>:runs.isError?<ErrorState error={runs.error} retry={()=>void runs.refetch()}/>:runs.data.results.length===0?<p role="status" className="py-8 text-center text-slate-600">No assurance runs match these filters.</p>:<div className="mt-4 space-y-3">{runs.data.results.map(run=><article key={run.id} className={`rounded-lg border p-4 ${selectedRunId===run.id?'border-blue-700 ring-1 ring-blue-700':''}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{run.runType} <span className="ml-2 rounded bg-slate-100 px-2 py-1 text-xs">{run.status}</span> · {run.id}</h3><p className="mt-1 text-sm text-slate-600">Created {new Date(run.createdAt).toLocaleString()} · actor {run.startedByEmail??'system'}{run.verificationCampaignId?` · campaign ${run.verificationCampaignId}`:''}{run.scheduledFor?` · scheduled ${run.scheduledFor}`:''}</p><p className="mt-1 text-sm">Phase {run.phase} · evaluator v{run.executorVersion} · input schema v{run.inputSchemaVersion}{run.capturedAt?` · captured ${new Date(run.capturedAt).toLocaleString()}`:''}{run.sealedAt?` · inputs sealed ${new Date(run.sealedAt).toLocaleString()}`:''}</p>{run.status==='RUNNING'&&<p className="mt-1 text-sm" role="status">{run.unitsCompleted}/{run.unitCount} work units complete · frozen population {run.populationCount}. Findings publish together after all units succeed.</p>}{run.status==='COMPLETED'&&<p className="mt-1 text-sm">Completed {run.completedAt?new Date(run.completedAt).toLocaleString():''} · assets evaluated {run.assetsEvaluated} · backend detections {run.findingsGenerated} · open at publication {run.findingsOpen} · resolved at publication {run.findingsResolved}</p>}{run.status==='FAILED'&&<p className="mt-1 text-sm text-rose-700">Evaluation failed. Django did not publish public findings from this run. Create a new run to retry.</p>}{run.status==='CANCELLED'&&<p className="mt-1 text-sm">Cancelled {run.completedAt?new Date(run.completedAt).toLocaleString():''}</p>}{run.status==='RUNNING'&&run.executorVersion===0&&<p role="alert" className="mt-1 text-sm text-rose-700">Legacy execution requires operator review and is not automatically resumed.</p>}</div><div className="flex flex-wrap gap-2">{manager&&run.status==='PENDING'&&<><button disabled={busy||uncertain} onClick={()=>void runAction(run,'execute')} className="rounded bg-blue-800 px-3 py-1.5 text-sm text-white">Execute</button><button disabled={busy||uncertain} onClick={()=>void runAction(run,'cancel')} className="rounded border px-3 py-1.5 text-sm">Cancel</button></>}{run.status==='COMPLETED'&&<button onClick={()=>{setSelectedRunId(selectedRunId===run.id?'':run.id);setRunFindingPage(1)}} className="rounded border px-3 py-1.5 text-sm">{selectedRunId===run.id?'Hide':'Public findings from run'}</button>}</div></div></article>)}</div>}
   {runs.data&&<Pager page={runPage} data={runs.data} setPage={setRunPage}/>}</section>
   {selectedRunId&&selectedRun.isPending&&<LoadingState label="Refreshing the selected run from Django…"/>}
   {selectedRun.data?.status==='RUNNING'&&<section role="status" className="rounded-xl border border-blue-200 bg-blue-50 p-4"><h2 className="font-semibold">Django reports this run is RUNNING</h2><p className="mt-1 text-sm">Phase {selectedRun.data.phase} · {selectedRun.data.unitsCompleted}/{selectedRun.data.unitCount} work units complete · captured population {selectedRun.data.populationCount}. Public findings appear only after atomic publication.</p></section>}
   {selectedRun.data?.status==='FAILED'&&<section role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4"><h2 className="font-semibold">Django reports this run FAILED</h2><p className="mt-1 text-sm">No public findings or occurrences were published by this run. Create a new run to repeat execution.</p></section>}
   {selectedRunId&&selectedRun.data?.status==='COMPLETED'&&<section className="rounded-xl border bg-white p-5"><h2 className="text-lg font-semibold">Public findings from completed run</h2>{runFindings.isPending?<LoadingState label="Loading published findings…"/>:runFindings.isError?<ErrorState error={runFindings.error} retry={()=>void runFindings.refetch()}/>:runFindings.data.results.length===0?<p role="status" className="py-5 text-slate-600">Django published no findings for this run.</p>:<div className="mt-3 space-y-3">{runFindings.data.results.map(finding=><FindingCard key={finding.id} finding={finding} manager={manager} busy={busy||uncertain} notes={resolutionNotes} setNotes={setResolutionNotes} onAction={action=>void findingAction(finding,action)} onAsset={onSelectAsset}/>)}</div>}{runFindings.data&&<Pager page={runFindingPage} data={runFindings.data} setPage={setRunFindingPage}/>}</section>}
  </>}
  {tab==='findings'&&<section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Public assurance findings</h2><p className="text-sm text-slate-600">Only Django-published findings appear here. Occurrence snapshots are backend history, not browser-inferred recurrence.</p></div><div className="flex flex-wrap gap-2"><label className="text-sm">Status<select className="ml-1 rounded border p-2" value={findingStatus} onChange={e=>{setFindingStatus(e.target.value);setFindingPage(1)}}><option value="">All</option>{['OPEN','UNDER_REVIEW','RESOLVED','ACCEPTED','REJECTED'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">Severity<select className="ml-1 rounded border p-2" value={severity} onChange={e=>{setSeverity(e.target.value);setFindingPage(1)}}><option value="">All</option>{['LOW','MEDIUM','HIGH','CRITICAL'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">Type<select className="ml-1 rounded border p-2" value={findingType} onChange={e=>{setFindingType(e.target.value);setFindingPage(1)}}><option value="">All</option>{['LOCATION_MISMATCH','DEPARTMENT_MISMATCH','CUSTODY_MISMATCH','MISSING_PHYSICAL_VERIFICATION','ASSET_NOT_FOUND','UNREGISTERED_ASSET','TAG_MISMATCH','DUPLICATE_TAG','CONDITION_EXCEPTION','LIFECYCLE_MISMATCH','DISPOSAL_STATUS_MISMATCH','DEPRECIATION_EXCEPTION','BOOK_VALUE_EXCEPTION','STALE_RECORD','OPEN_WORKFLOW','MISSING_EVIDENCE'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">Source<select className="ml-1 rounded border p-2" value={source} onChange={e=>{setSource(e.target.value);setFindingPage(1)}}><option value="">All</option>{['ASSET_MASTER','PHYSICAL_VERIFICATION','DEPRECIATION','DISPOSAL','MAINTENANCE','ASSIGNMENT','TRANSFER','EVIDENCE'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm">Search<input className="ml-1 rounded border p-2" value={search} onChange={e=>{setSearch(e.target.value);setFindingPage(1)}} placeholder="Asset, finding, rule"/></label></div></div>
   {findings.isPending?<LoadingState label="Loading public findings…"/>:findings.isError?<ErrorState error={findings.error} retry={()=>void findings.refetch()}/>:findings.data.results.length===0?<p role="status" className="py-8 text-center text-slate-600">No published findings match these filters.</p>:<div className="mt-4 space-y-3">{findings.data.results.map(finding=><FindingCard key={finding.id} finding={finding} manager={manager} busy={busy||uncertain} notes={resolutionNotes} setNotes={setResolutionNotes} onAction={action=>void findingAction(finding,action)} onAsset={onSelectAsset}/>)}</div>}
   {findings.data&&<Pager page={findingPage} data={findings.data} setPage={setFindingPage}/>}</section>}
  {message&&<div role={uncertain?'alert':'status'} className="flex flex-wrap items-center justify-between gap-3 rounded border bg-white p-3 text-sm"><span>{message}</span>{uncertain&&<button className="rounded border px-3 py-1.5" onClick={()=>void Promise.all([runs.refetch(),findings.refetch(),selectedRunId?selectedRun.refetch():Promise.resolve(),selectedRunId&&selectedRun.data?.status==='COMPLETED'?runFindings.refetch():Promise.resolve()]).then(()=>{setUncertain(false);setMessage('Authoritative assurance history refreshed. Review current state before another action.');})}>Recheck assurance state</button>}</div>}
 </section>;
}
function FindingCard({finding,manager,busy,notes,setNotes,onAction,onAsset}:{finding:AssuranceFinding;manager:boolean;busy:boolean;notes:string;setNotes:(value:string)=>void;onAction:(action:'review'|'resolve'|'accept'|'reject')=>void;onAsset:(id:string)=>void}){return <article className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{finding.type} <span className="ml-2 rounded bg-slate-100 px-2 py-1 text-xs">{finding.status}</span></h3><p className="mt-1 text-sm">{finding.assetId?<button className="text-blue-800 underline" onClick={()=>onAsset(finding.assetId!)}>{finding.assetTag??'Asset'} · {finding.assetName??''}</button>:<span>Unregistered physical item · observation {finding.physicalVerificationId}</span>} · {finding.source}</p><p className="mt-1 text-sm">{finding.description}</p><p className="mt-1 text-sm">Expected: {finding.expectedValue||'—'} · Observed: {finding.observedValue||'—'}</p><p className="mt-1 text-xs text-slate-500">{finding.departmentName??'No department'} · {finding.locationName??'No location'} · first {new Date(finding.firstDetectedAt).toLocaleString()} · last {new Date(finding.lastDetectedAt).toLocaleString()} · {finding.occurrenceCount} occurrences</p><p className="mt-1 text-xs text-slate-500">Created in run {finding.assuranceRunId} · last detected run {finding.lastDetectedRunId}{finding.resolvedAt?` · ${finding.status.toLowerCase()} by ${finding.resolvedByEmail} at ${new Date(finding.resolvedAt).toLocaleString()}`:''}</p>{finding.resolutionNotes&&<p className="mt-1 text-sm">Resolution notes: {finding.resolutionNotes}</p>}</div><span className={`h-fit rounded px-2 py-1 text-sm font-semibold ${finding.severity==='CRITICAL'?'bg-rose-100 text-rose-900':finding.severity==='HIGH'?'bg-orange-100 text-orange-900':'bg-amber-50 text-amber-900'}`}>{finding.severity}</span></div>
  {finding.occurrences.length>0&&<details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">Occurrence history ({finding.occurrenceCount}; showing {finding.occurrences.length})</summary><ol className="mt-2 space-y-2 border-l pl-4">{finding.occurrences.map(row=><li key={row.id} className="text-sm"><b>{new Date(row.detectedAt).toLocaleString()}</b> · run {row.assuranceRunId}<p>{row.description}</p><p className="text-xs text-slate-600">Expected {row.expectedValue||'—'} · observed {row.observedValue||'—'}</p></li>)}</ol></details>}
  {manager&&finding.status==='OPEN'&&<button disabled={busy} onClick={()=>onAction('review')} className="mt-3 rounded bg-blue-800 px-3 py-1.5 text-sm text-white disabled:opacity-50">Start review</button>}
  {manager&&finding.status==='UNDER_REVIEW'&&<div className="mt-3 flex flex-wrap items-end gap-2"><label className="text-sm">Resolution notes<input className="ml-2 rounded border p-2" value={notes} maxLength={4000} onChange={event=>setNotes(event.target.value)}/></label>{(['resolve','accept','reject'] as const).map(action=><button key={action} disabled={busy||!notes.trim()} onClick={()=>onAction(action)} className="rounded border px-3 py-1.5 text-sm disabled:opacity-50">{action[0].toUpperCase()+action.slice(1)}</button>)}</div>}</article>;}
function Pager<T>({page,data,setPage}:{page:number;data:{count:number;next:string|null;previous:string|null}|undefined;setPage:(page:number)=>void}){return data?<div className="mt-4 flex items-center justify-between"><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={page<=1||!data.previous} onClick={()=>setPage(page-1)}>Previous</button><span className="text-sm">{data.count} records · Page {page}</span><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={!data.next} onClick={()=>setPage(page+1)}>Next</button></div>:null;}
