import { useState } from 'react';
import { useAllAssets } from '../services/assetQueries';
import { useReferences } from '../services/referenceQueries';
import { useTransfers } from '../services/movementQueries';
import { useMovementAction } from '../services/movementMutations';
import { useAuth } from '../auth/AuthProvider';
import { canManageAssets } from '../services/acquisitionQueries';
import { EmptyState,ErrorState,LoadingState } from '../components/common/AsyncState';
import { errorMessage } from '../services/apiError';
import { djangoRepository, movementRepository } from '../services/runtime';
import { useQueryClient } from '@tanstack/react-query';
import { assetKeys } from '../services/assetQueries';

export function BackendTransfersView({onNavigate,onSelectAsset}:{onNavigate:(route:string)=>void;onSelectAsset:(id:string)=>void}){
 const {role,user,generation,isCurrent}=useAuth();const writable=canManageAssets(role);const [status,setStatus]=useState('');const [assetId,setAssetId]=useState('');const [departmentId,setDepartmentId]=useState('');const [locationId,setLocationId]=useState('');const [reason,setReason]=useState('');const [notes,setNotes]=useState('');const [message,setMessage]=useState('');
 const rows=useTransfers({status:status||undefined});const assets=useAllAssets({pageSize:100,search:'',status:'',category:'',department:'',location:'',ordering:'tag'});const departments=useReferences('departments');const locations=useReferences('locations');const action=useMovementAction('transfers');const client=useQueryClient();
 const reconcile=async(refreshPlacement=false)=>{await Promise.all([rows.refetch(),...(refreshPlacement?[client.invalidateQueries({queryKey:assetKeys.scope(user?.id,generation)})]:[])]);};
 const selectedAsset=assets.data?.data.find(asset=>asset.id===assetId);
 const submit=async()=>{if(!assetId||!departmentId||!locationId||!reason.trim())return;if(departmentId===selectedAsset?.department?.id&&locationId===selectedAsset?.location?.id){setMessage('Choose a destination different from the current asset placement.');return;}setMessage('');try{await action.run(()=>movementRepository.createTransfer({asset_id:assetId,to_department_id:departmentId,to_location_id:locationId,reason:reason.trim(),notes}));if(!isCurrent(generation))return;setMessage('Transfer request saved. Placement remains unchanged until completion.');setAssetId('');setReason('');setNotes('');}catch(error){if(!isCurrent(generation))return;const [current,asset]=await Promise.all([movementRepository.transfers({asset:assetId}).catch(()=>null),djangoRepository.getAssetById(assetId).catch(()=>null)]);if(!isCurrent(generation))return;await reconcile();if(!isCurrent(generation))return;const open=current?.find(row=>row.status==='REQUESTED'||row.status==='APPROVED');setMessage(current===null||asset===null?`${errorMessage(error)} Transfer state is uncertain; do not submit another request until connectivity returns.`:open?`The backend confirms transfer ${open.status.toLowerCase()}; placement is still ${asset.department?.name??'—'} / ${asset.location?.name??'—'}.`:`${errorMessage(error)} No open transfer is present in the latest backend read; retry is available.`);}};
 const transition=async(id:string,kind:'approve'|'reject'|'cancel'|'complete')=>{setMessage('');try{await action.run(()=>movementRepository.transition(id,kind),kind==='complete');if(!isCurrent(generation))return;if(kind==='complete')await reconcile(true);if(!isCurrent(generation))return;setMessage(kind==='complete'?'Transfer completed; authoritative placement has been refreshed.':'Transfer state updated; placement has not changed.');}catch(error){if(!isCurrent(generation))return;const [current,asset]=await Promise.all([movementRepository.transfer(id).catch(()=>null),djangoRepository.getAssetById(rows.data?.find(row=>row.id===id)?.assetId??'').catch(()=>null)]);if(!isCurrent(generation))return;await reconcile(kind==='complete');if(!isCurrent(generation))return;setMessage(current===null||asset===null?`${errorMessage(error)} Workflow and placement could not be confirmed; do not repeat the action until state can be refreshed.`:`Backend state is ${current.status}; asset placement is ${asset.department?.name??'—'} / ${asset.location?.name??'—'}. ${errorMessage(error)}`);}};
 return <section className="p-4 md:p-6 space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><button onClick={()=>onNavigate('all-assets')} className="text-sm text-blue-800 underline">Asset Register</button><h1 className="mt-2 text-2xl font-bold">Asset Transfers</h1><p className="text-sm text-slate-600">Transfers change department or location only on backend completion; custody remains independent.</p></div><button className="border rounded px-3 py-2" onClick={()=>void rows.refetch()} disabled={rows.isFetching}>Refresh</button></header>
 {message&&<p role="status" className="rounded border bg-blue-50 p-3 text-sm">{message}</p>}
 {writable&&<section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-semibold">Request placement transfer</h2>{assets.isError&&<ErrorState error={assets.error} retry={()=>void assets.refetch()} />}{departments.isError&&<ErrorState error={departments.error} retry={()=>void departments.refetch()} />}{locations.isError&&<ErrorState error={locations.error} retry={()=>void locations.refetch()} />}<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3"><label className="text-sm">Asset<select value={assetId} onChange={e=>setAssetId(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Select asset</option>{assets.data?.data.map(a=><option key={a.id} value={a.id}>{a.tag} — {a.name} · {a.department?.name??'—'} / {a.location?.name??'—'}</option>)}</select></label><label className="text-sm">Destination department<select value={departmentId} onChange={e=>setDepartmentId(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Select department</option>{departments.data?.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="text-sm">Destination location<select value={locationId} onChange={e=>setLocationId(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Select location</option>{locations.data?.filter(l=>l.active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label className="text-sm">Reason<input value={reason} onChange={e=>setReason(e.target.value)} maxLength={240} className="mt-1 w-full rounded border p-2"/></label><label className="text-sm">Notes<input value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 w-full rounded border p-2"/></label></div><p className="text-xs text-slate-600">Source placement is derived and locked by Django. Request and approval leave Asset department/location unchanged.</p><button disabled={!assetId||!departmentId||!locationId||!reason.trim()||action.pending||assets.isPending||departments.isPending||locations.isPending||assets.isError||departments.isError||locations.isError} onClick={()=>void submit()} className="rounded bg-blue-900 px-4 py-2 text-white disabled:opacity-50">{action.pending?'Working…':'Request transfer'}</button></section>}
 <label className="text-sm">Status filter<select className="ml-2 rounded border bg-white p-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['REQUESTED','APPROVED','COMPLETED','REJECTED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select></label>
 {rows.isPending?<LoadingState label="Loading transfer workflow…"/>:rows.isError?<ErrorState error={rows.error} retry={()=>void rows.refetch()}/>:!rows.data.length?<EmptyState label="No transfers match this state."/>:<div className="space-y-3">{rows.data.map(t=><article key={t.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><button onClick={()=>onSelectAsset(t.assetId)} className="font-semibold text-blue-900 underline">{t.assetTag} — {t.assetName}</button><p className="mt-1 text-sm">{t.fromDepartmentName??'—'} / {t.fromLocationName??'—'} <span aria-hidden="true">→</span> {t.toDepartmentName??'—'} / {t.toLocationName??'—'}</p><p className="mt-1 text-xs text-slate-600">{t.status} · Requested {t.requestedAt} by {t.requestedByEmail}</p><p className="mt-1 text-sm">{t.reason}{t.notes?` · ${t.notes}`:''}</p>{t.approvedAt&&<p className="text-xs text-slate-500">Approved {t.approvedAt} by {t.approvedByEmail}</p>}{t.completedAt&&<p className="text-xs text-slate-500">Completed {t.completedAt} by {t.completedByEmail}</p>}</div><div className="flex flex-wrap gap-2">{writable&&t.status==='REQUESTED'&&<><button disabled={action.pending} onClick={()=>void transition(t.id,'approve')} className="rounded bg-blue-900 px-3 py-2 text-white disabled:opacity-50">Approve</button><button disabled={action.pending} onClick={()=>void transition(t.id,'reject')} className="rounded border px-3 py-2 disabled:opacity-50">Reject</button><button disabled={action.pending} onClick={()=>void transition(t.id,'cancel')} className="rounded border px-3 py-2 disabled:opacity-50">Cancel</button></>}{writable&&t.status==='APPROVED'&&<button disabled={action.pending} onClick={()=>void transition(t.id,'complete')} className="rounded bg-emerald-800 px-3 py-2 text-white disabled:opacity-50">Complete transfer</button>}</div></div></article>)}</div>}
 </section>
}
