import { useState } from 'react';
import { useAllAssets } from '../services/assetQueries';
import { useAssignments,useCustodians } from '../services/movementQueries';
import { useMovementAction } from '../services/movementMutations';
import { useAuth } from '../auth/AuthProvider';
import { canManageAssets } from '../services/acquisitionQueries';
import { EmptyState,ErrorState,LoadingState } from '../components/common/AsyncState';
import { errorMessage } from '../services/apiError';
import { movementRepository } from '../services/runtime';
import { djangoRepository } from '../services/runtime';

export function BackendAssignmentsView({onNavigate,onSelectAsset}:{onNavigate:(route:string)=>void;onSelectAsset:(id:string)=>void}){
 const {role,generation,isCurrent}=useAuth();const writable=canManageAssets(role);const [active,setActive]=useState(true);const [assetId,setAssetId]=useState('');const [custodianId,setCustodianId]=useState('');const [notes,setNotes]=useState('');const [message,setMessage]=useState('');
 const records=useAssignments({active});const custodians=useCustodians(writable);const assets=useAllAssets({pageSize:100,search:'',status:'',category:'',department:'',location:'',ordering:'tag'});const action=useMovementAction('assignments');
 const submit=async()=>{if(!assetId)return;setMessage('');try{await action.run(()=>movementRepository.createAssignment({asset_id:assetId,assigned_to_id:custodianId?Number(custodianId):null,notes}));if(!isCurrent(generation))return;setAssetId('');setCustodianId('');setNotes('');setMessage('Custody assignment saved. Asset placement is unchanged.');}catch(error){if(!isCurrent(generation))return;const [current,asset]=await Promise.all([movementRepository.assignments({asset:assetId,active:true}).catch(()=>null),djangoRepository.getAssetById(assetId).catch(()=>null)]);if(!isCurrent(generation))return;setMessage(current?.length?`An active assignment is confirmed for this asset. Placement remains ${asset?.department?.name??'—'} / ${asset?.location?.name??'—'}.`:current===null?`${errorMessage(error)} The assignment state could not be confirmed; do not repeat until connectivity returns.`:`${errorMessage(error)} No active assignment is present in the latest backend read; retry is available.`);}};
 const doReturn=async(id:string)=>{setMessage('');try{await action.run(()=>movementRepository.returnAssignment(id));if(!isCurrent(generation))return;setMessage('Assignment returned; history retained and asset placement unchanged.');}catch(error){if(!isCurrent(generation))return;const current=await movementRepository.assignments({asset:records.data?.find(row=>row.id===id)?.assetId,active:true}).catch(()=>null);if(!isCurrent(generation))return;setMessage(current===null?`${errorMessage(error)} Return state is uncertain; do not repeat until the assignment can be refreshed.`:current.some(row=>row.id===id)?`${errorMessage(error)} The assignment remains active in the backend and can be returned again.`:`Assignment return is confirmed by the backend. History is retained and placement is unchanged.`);}};
 return <section className="p-4 md:p-6 space-y-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><button onClick={()=>onNavigate('all-assets')} className="text-sm text-blue-800 underline">Asset Register</button><h1 className="mt-2 text-2xl font-bold">Assignments & Custody</h1><p className="text-sm text-slate-600">Custody records the responsible holder. It does not change department or location placement.</p></div><button className="border rounded px-3 py-2" onClick={()=>void records.refetch()} disabled={records.isFetching}>Refresh</button></header>
 {message&&<p role="status" className="rounded border bg-blue-50 p-3 text-sm">{message}</p>}
 {writable&&<section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-semibold">Assign asset custody</h2>{assets.isError&&<ErrorState error={assets.error} retry={()=>void assets.refetch()}/>}<div className="grid md:grid-cols-3 gap-3"><label className="text-sm">Asset<select className="mt-1 w-full border rounded p-2" value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">Select asset</option>{assets.data?.data.map(asset=><option key={asset.id} value={asset.id}>{asset.tag} — {asset.name}</option>)}</select></label><label className="text-sm">Custodian<select className="mt-1 w-full border rounded p-2" value={custodianId} onChange={e=>setCustodianId(e.target.value)}><option value="">Unassigned custody</option>{custodians.data?.map(user=><option key={user.id} value={user.id}>{user.email} · {user.role}</option>)}</select></label><label className="text-sm">Notes<input className="mt-1 w-full border rounded p-2" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></label></div>{custodians.isError&&<ErrorState error={custodians.error} retry={()=>void custodians.refetch()}/>}<button onClick={()=>void submit()} disabled={!assetId||action.pending||assets.isPending||assets.isError||custodians.isPending||custodians.isError} className="rounded bg-blue-900 px-4 py-2 text-white disabled:opacity-50">{action.pending?'Saving…':'Assign custody'}</button></section>}
 <nav className="flex gap-2" aria-label="Assignment state"><button onClick={()=>setActive(true)} aria-pressed={active} className={`rounded px-3 py-2 ${active?'bg-blue-900 text-white':'border bg-white'}`}>Active custody</button><button onClick={()=>setActive(false)} aria-pressed={!active} className={`rounded px-3 py-2 ${!active?'bg-blue-900 text-white':'border bg-white'}`}>History</button></nav>
 {records.isPending?<LoadingState label="Loading custody records…"/>:records.isError?<ErrorState error={records.error} retry={()=>void records.refetch()}/>:!records.data.length?<EmptyState label={active?'No active custody records.':'No returned custody history.'}/>:<div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><caption className="sr-only">Backend assignment and custody records</caption><thead className="bg-slate-50"><tr>{['Asset','Custodian','Placement snapshot','Assigned','Returned','Notes','Action'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{records.data.map(row=><tr key={row.id} className="border-t"><td className="p-3"><button className="text-blue-900 underline" onClick={()=>onSelectAsset(row.assetId)}>{row.assetTag}</button><div>{row.assetName}</div></td><td className="p-3">{row.custodianEmail??'Unassigned'}</td><td className="p-3">{row.departmentName??'—'}<br/>{row.locationName??'—'}</td><td className="p-3">{row.assignedAt}</td><td className="p-3">{row.returnedAt??'Active'}</td><td className="p-3">{row.notes||'—'}</td><td className="p-3">{active&&writable&&<button disabled={action.pending} onClick={()=>void doReturn(row.id)} className="rounded border px-3 py-1 disabled:opacity-50">Return</button>}</td></tr>)}</tbody></table></div>}
 </section>
}
