import {FormEvent,useEffect,useState} from 'react';
import {useAuth} from '../auth/AuthProvider';
import {ErrorState,LoadingState} from '../components/common/AsyncState';
import {errorMessage} from '../services/apiError';
import {AdminReference,AdminUser,OrganizationRole,organizationRoles} from '../services/organizationAdminRepository';
import {useAdminDepartments,useAdminLocations,useAdminUsers,useEphemeralAdminAction,useOrganizationAdminAction} from '../services/organizationAdminQueries';
import {organizationAdminRepository} from '../services/runtime';
import {useReferences} from '../services/referenceQueries';

type Section='departments'|'locations'|'users';
const pageSize=25;
const labels:Record<OrganizationRole,string>={ADMIN:'Administrator',ASSET_MANAGER:'Asset Manager',ACCOUNTANT:'Accountant',DEPARTMENT_MANAGER:'Department Manager',EMPLOYEE:'Employee'};
const input='mt-1 w-full rounded border border-slate-300 p-2 text-sm';
const blankRef={name:'',code:'',address:'',city:'',state:'',country:'Nigeria',is_active:true};
export function BackendOrganizationAdminView({section}:{section:Section}){
 const{user,role}=useAuth();const admin=role==='ADMIN';const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [roleFilter,setRoleFilter]=useState<OrganizationRole|''>('');const [activeFilter,setActiveFilter]=useState('');const [message,setMessage]=useState('');const [uncertain,setUncertain]=useState(false);const action=useOrganizationAdminAction();const credentialAction=useEphemeralAdminAction();
 const filters={page,pageSize,search};const departments=useAdminDepartments(filters,section==='departments'&&admin);const departmentReferences=useReferences('departments',section==='users'&&admin);const departmentOptions=section==='users'?(departmentReferences.data??[]).map(row=>({id:row.id,name:row.name,code:row.code,isActive:row.active})):departments.data?.results??[];const locations=useAdminLocations(filters,section==='locations'&&admin);const userFilters={...filters,...(roleFilter?{role:roleFilter}:{}),...(activeFilter?{is_active:activeFilter==='true'}:{})};const users=useAdminUsers(userFilters,section==='users'&&admin);
 const query=section==='departments'?departments:section==='locations'?locations:users;
 const onSearch=(value:string)=>{setSearch(value);setPage(1);};
 const run=async(work:()=>Promise<unknown>,invalidateCustodians=false)=>{setMessage('');setUncertain(false);try{await action.run(work,invalidateCustodians);setMessage('Changes saved. Django has recorded the administrative event.');}catch(error){setMessage(errorMessage(error));setUncertain((error as {kind?:string})?.kind==='conflict');} };
 const createUser=(payload:{email:string;password:string;role:OrganizationRole;department_id:string|null})=>{setMessage('');setUncertain(false);void credentialAction.run(async()=>{try{return await organizationAdminRepository.createUser(payload);}finally{payload.password='';}},true).then(()=>setMessage('User created. Django has recorded the administrative event.')).catch(error=>{setMessage(errorMessage(error));setUncertain((error as {kind?:string})?.kind==='conflict');});};
 return <main className="space-y-5 p-4 md:p-6" aria-busy={query.isFetching}>
  <header><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Organization / Administration</p><h1 className="mt-1 text-2xl font-bold">{section==='departments'?'Departments':section==='locations'?'Locations':'Users & roles'}</h1><p className="mt-1 text-sm text-slate-600">Organization is derived from your authenticated Django session. Administrative writes are restricted by Django to tenant administrators.</p></header>
  {!admin?<p role="status" className="rounded-xl border bg-white p-8 text-center text-slate-600">Organization administration is available to tenant administrators. Your current role does not have access.</p>:<>
   <form onSubmit={e=>{e.preventDefault();setPage(1);}} className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4"><label className="min-w-56 flex-1 text-sm">Search<input className={input} value={search} onChange={e=>onSearch(e.target.value)} placeholder={section==='users'?'Email or department':'Name or code'}/></label>{section==='users'&&<><label className="text-sm">Role<select className={input} value={roleFilter} onChange={e=>{setRoleFilter(e.target.value as OrganizationRole|'');setPage(1);}}><option value="">All roles</option>{organizationRoles.map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></label><label className="text-sm">Status<select className={input} value={activeFilter} onChange={e=>{setActiveFilter(e.target.value);setPage(1);}}><option value="">All users</option><option value="true">Active</option><option value="false">Inactive</option></select></label></>}<span className="text-xs text-slate-500">Search, filters, and pagination are applied by the server.</span></form>
   {section==='departments'?<ReferenceEditor kind="department" rows={departments.data?.results??[]} busy={action.pending||uncertain} onSave={payload=>void run(()=>payload.id?organizationAdminRepository.updateDepartment(payload.id,payload):organizationAdminRepository.createDepartment(payload))} />:null}
   {section==='locations'?<ReferenceEditor kind="location" rows={locations.data?.results??[]} busy={action.pending||uncertain} onSave={payload=>void run(()=>payload.id?organizationAdminRepository.updateLocation(payload.id,{name:payload.name,code:payload.code,address:payload.address??'',city:payload.city??'',state:payload.state??'',country:payload.country??'Nigeria',is_active:payload.is_active}):organizationAdminRepository.createLocation({name:payload.name,code:payload.code,address:payload.address??'',city:payload.city??'',state:payload.state??'',country:payload.country??'Nigeria',is_active:payload.is_active}))} />:null}
   {section==='users'?<UserCreate departments={departmentOptions} busy={action.pending||credentialAction.pending||uncertain} onCreate={createUser}/>:null}
   {query.isPending?<LoadingState label={`Loading ${section}…`}/>:query.isError?<ErrorState error={query.error} retry={()=>void query.refetch()}/>:section==='users'?<UserTable rows={users.data?.results??[]} departmentRows={departmentOptions} currentUserId={user?.id} busy={action.pending||uncertain} onSave={(id,payload)=>void run(()=>organizationAdminRepository.updateUser(id,payload),true)}/>:<ReferenceTable kind={section} rows={(section==='departments'?departments.data?.results:locations.data?.results)??[]} />}
   {query.data&&<nav className="flex items-center justify-between rounded-xl border bg-white p-3" aria-label={`${section} pages`}><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={page<=1||!query.data.previous} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="text-sm">{query.data.count} records · Page {page}</span><button className="rounded border px-3 py-2 disabled:opacity-50" disabled={!query.data.next} onClick={()=>setPage(p=>p+1)}>Next</button></nav>}
   {section==='users'&&<section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Role reference</h2><p className="mt-1 text-sm text-slate-600">Informational only. Effective access is determined by Django permissions and object/department scope. Tenant administrators may assign organization roles to other users. They cannot change their own role or department, grant Django staff/superuser access, or remove the last active administrator.</p><ul className="mt-3 grid gap-2 text-sm sm:grid-cols-2">{organizationRoles.map(r=><li key={r} className="rounded bg-slate-50 p-2"><b>{labels[r]}</b> <span className="text-slate-600">({r})</span></li>)}</ul></section>}
   {message&&<div role={uncertain?'alert':'status'} className="flex flex-wrap items-center gap-3 rounded border bg-white p-3 text-sm"><span>{message}{uncertain&&' Inspect the refreshed server state before submitting another change.'}</span>{uncertain&&<button type="button" className="rounded border px-3 py-1.5" onClick={()=>void query.refetch().then(result=>{if(!result.isError){setUncertain(false);setMessage('Authoritative state refreshed. Review the record before making another change.');}})}>Recheck state</button>}</div>}
  </>}
  <p className="text-xs text-slate-500">Signed in as {user?.email}. Passwords and authentication secrets are never displayed. Department/location edits do not transfer assets.</p>
 </main>;
}
type RefInput={id?:string;name:string;code:string;address?:string;city?:string;state?:string;country?:string;is_active:boolean};
function ReferenceEditor({kind,rows,busy,onSave}:{kind:'department'|'location';rows:AdminReference[];busy:boolean;onSave:(input:RefInput)=>void}){
 const [value,setValue]=useState<RefInput>(blankRef);const [editId,setEditId]=useState<string|undefined>();const begin=(row:AdminReference)=>{setEditId(row.id);setValue({id:row.id,name:row.name,code:row.code,address:row.address??'',city:row.city??'',state:row.state??'',country:row.country??'Nigeria',is_active:row.isActive});};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!value.name.trim()||!value.code.trim())return;const basic={name:value.name.trim(),code:value.code.trim(),is_active:value.is_active};const body=kind==='location'?{...basic,address:value.address??'',city:value.city??'',state:value.state??'',country:value.country??'Nigeria'}:basic;onSave(editId?{...body,id:editId}:body);setValue(blankRef);setEditId(undefined);};
 return <form onSubmit={submit} className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-4"><h2 className="font-semibold sm:col-span-2 lg:col-span-4">{editId?'Edit':'Add'} {kind}</h2><label className="text-sm">Name<input required maxLength={160} className={input} value={value.name} onChange={e=>setValue(v=>({...v,name:e.target.value}))}/></label><label className="text-sm">Code<input required maxLength={32} className={input} value={value.code} onChange={e=>setValue(v=>({...v,code:e.target.value}))}/></label>{kind==='location'&&<>{(['address','city','state','country'] as const).map(k=><label key={k} className="text-sm capitalize">{k}<input maxLength={k==='address'?1000:100} className={input} value={value[k]} onChange={e=>setValue(v=>({...v,[k]:e.target.value}))}/></label>)}</>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.is_active} onChange={e=>setValue(v=>({...v,is_active:e.target.checked}))}/>Active</label><div className="flex gap-2"><button disabled={busy} className="rounded bg-[#00288e] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{editId?'Save changes':`Create ${kind}`}</button>{editId&&<button type="button" className="rounded border px-4 py-2 text-sm" onClick={()=>{setEditId(undefined);setValue(blankRef);}}>Cancel</button>}</div><div className="sm:col-span-2 lg:col-span-4"><ReferenceTable kind={kind==='department'?'departments':'locations'} rows={rows} onEdit={begin}/></div></form>;
}
function ReferenceTable({kind,rows,onEdit}:{kind:'departments'|'locations';rows:AdminReference[];onEdit?:(row:AdminReference)=>void}){return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Code</th><th className="p-3">Name</th>{kind==='locations'&&<th className="p-3">City / State</th>}<th className="p-3">Status</th>{onEdit&&<th className="p-3">Action</th>}</tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.id}><td className="p-3 font-mono">{row.code}</td><td className="p-3">{row.name}</td>{kind==='locations'&&<td className="p-3">{[row.city,row.state].filter(Boolean).join(', ')||'—'}</td>}<td className="p-3">{row.isActive?'Active':'Inactive'}</td>{onEdit&&<td className="p-3"><button type="button" className="rounded border px-3 py-1" onClick={()=>onEdit(row)}>Edit</button></td>}</tr>)}{rows.length===0&&<tr><td className="p-5 text-center text-slate-500" colSpan={onEdit?5:4}>No {kind} found.</td></tr>}</tbody></table></div>;}
type DepartmentOption=Pick<AdminReference,'id'|'name'|'code'|'isActive'>;
function UserCreate({departments,busy,onCreate}:{departments:DepartmentOption[];busy:boolean;onCreate:(input:{email:string;password:string;role:OrganizationRole;department_id:string|null})=>void}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<OrganizationRole>('EMPLOYEE'),[department,setDepartment]=useState('');
 const submit=(e:FormEvent)=>{e.preventDefault();if(!password)return;onCreate({email,password,role,department_id:department||null});setEmail('');setPassword('');setRole('EMPLOYEE');setDepartment('');};
 return <form onSubmit={submit} autoComplete="off" className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><h2 className="font-semibold sm:col-span-2 lg:col-span-5">Create user</h2><label className="text-sm">Email<input required type="email" autoComplete="off" className={input} value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="text-sm">Initial password<input required type="password" autoComplete="new-password" className={input} value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="text-sm">Role<select className={input} value={role} onChange={e=>setRole(e.target.value as OrganizationRole)}>{organizationRoles.map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></label><label className="text-sm">Department<select className={input} value={department} onChange={e=>setDepartment(e.target.value)}><option value="">No department</option>{departments.filter(d=>d.isActive).map(d=><option key={d.id} value={d.id}>{d.code} · {d.name}</option>)}</select></label><button disabled={busy} className="self-end rounded bg-[#00288e] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Create user</button><p className="text-xs text-slate-500 sm:col-span-2 lg:col-span-5">The password is sent once to Django over the authenticated API, is hashed by Django, and is cleared from this form after submission. No invitation email is sent.</p></form>;
}
function UserTable({rows,departmentRows,currentUserId,busy,onSave}:{rows:AdminUser[];departmentRows:DepartmentOption[];currentUserId:number|undefined;busy:boolean;onSave:(id:number,input:{role:OrganizationRole;department_id:string|null;is_active:boolean})=>void}){return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Email</th><th className="p-3">Role</th><th className="p-3">Department</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3">Update</th></tr></thead><tbody className="divide-y">{rows.map(user=><UserRow key={user.id} user={user} departments={departmentRows} currentUser={user.id===currentUserId} busy={busy} onSave={onSave}/>)}</tbody>{rows.length===0&&<tbody><tr><td className="p-5 text-center text-slate-500" colSpan={6}>No users found.</td></tr></tbody>}</table></div>;}
function UserRow({user,departments,currentUser,busy,onSave}:{user:AdminUser;departments:DepartmentOption[];currentUser:boolean;busy:boolean;onSave:(id:number,input:{role:OrganizationRole;department_id:string|null;is_active:boolean})=>void}){const[role,setRole]=useState(user.role),[department,setDepartment]=useState(user.departmentId??''),[active,setActive]=useState(user.isActive);useEffect(()=>{setRole(user.role);setDepartment(user.departmentId??'');setActive(user.isActive);},[user.role,user.departmentId,user.isActive]);return <tr><td className="p-3">{user.email}{currentUser&&<span className="ml-2 text-xs text-slate-500">(you · changes restricted)</span>}{user.lastLogin&&<span className="block text-xs text-slate-500">Last login {new Date(user.lastLogin).toLocaleString()}</span>}</td><td className="p-3"><select disabled={currentUser} aria-label={`Role for ${user.email}`} className="rounded border p-2 disabled:bg-slate-100" value={role} onChange={e=>setRole(e.target.value as OrganizationRole)}>{organizationRoles.map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></td><td className="p-3"><select disabled={currentUser} aria-label={`Department for ${user.email}`} className="rounded border p-2 disabled:bg-slate-100" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">No department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.code} · {d.name}{d.isActive?'':' (inactive)'}</option>)}</select></td><td className="p-3"><label className="flex items-center gap-2"><input type="checkbox" disabled={currentUser} checked={active} onChange={e=>setActive(e.target.checked)}/>{active?'Active':'Inactive'}</label></td><td className="p-3">{new Date(user.createdAt).toLocaleDateString()}</td><td className="p-3"><button disabled={currentUser||busy||user.role===role&&user.departmentId===(department||null)&&user.isActive===active} className="rounded border px-3 py-1.5 disabled:opacity-50" onClick={()=>onSave(user.id,{role,department_id:department||null,is_active:active})}>Save</button></td></tr>;}
