# Generated by Django 5.2.17 on 2026-10-08 10:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_ratebucket_user_is_platform_operator_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=24)),
                ('reference', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=80)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('requirements', models.TextField(max_length=4000)),
                ('kind', models.CharField(choices=[('DEMO', 'Demo'), ('SALES', 'Sales')], max_length=12)),
                ('notice_version', models.CharField(default='contact-v1', max_length=32)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CONTACTED', 'CONTACTED'), ('QUALIFIED', 'QUALIFIED'), ('CLOSED', 'CLOSED')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=80)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_users', models.PositiveIntegerField(null=True)),
                ('registered_assets', models.PositiveIntegerField(null=True)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('is_public', models.BooleanField(default=True)),
                ('is_sandbox', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='unique_plan_version')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=160)),
                ('currency', models.CharField(max_length=3)),
                ('timezone', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.identityticket')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='organizations.organization')),
                ('state', models.CharField(choices=[('MANAGED', 'MANAGED'), ('TRIAL', 'TRIAL'), ('ACTIVE', 'ACTIVE'), ('PAST_DUE', 'PAST_DUE'), ('CANCELED', 'CANCELED'), ('SUSPENDED', 'SUSPENDED')], default='TRIAL', max_length=16)),
                ('trial_ends_at', models.DateTimeField(null=True)),
                ('period_ends_at', models.DateTimeField(null=True)),
                ('grace_ends_at', models.DateTimeField(null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('billing_email', models.EmailField(max_length=254)),
                ('provider', models.CharField(default='local_sandbox', max_length=24)),
                ('provider_customer', models.CharField(blank=True, max_length=120)),
                ('provider_subscription', models.CharField(blank=True, max_length=120)),
                ('last_event_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('provider', models.CharField(max_length=24)),
                ('provider_reference', models.CharField(max_length=120, unique=True)),
                ('provider_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(null=True)),
                ('sandbox_status', models.CharField(default='PENDING', max_length=16)),
                ('sandbox_sequence', models.PositiveIntegerField(default=0)),
                ('sandbox_updated_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'request_key'), name='checkout_idempotency_per_org')],
            },
        ),
    ]
