# Generated by Django 5.2.17 on 2026-10-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_sandbox_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='entitlement_checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitled_subscriptions', to='commercial.checkout'),
        ),
    ]
