# Generated by Django 5.2.17 on 2026-10-10 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_subscription_entitlement_checkout'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingevent',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='checkout',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='ProviderCustomer',
            fields=[
                ('code', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='commercial.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('code', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=24)),
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='commercial.checkout')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.providercustomer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.plan')),
            ],
        ),
    ]
