# Generated by Django 5.2.17 on 2026-09-25 09:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_available_for_use_date_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='organizations.department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments', to='organizations.organization')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignments_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assigned_at', '-created_at'),
                'indexes': [models.Index(fields=['organization', 'asset', 'returned_at'], name='assign_org_asset_idx'), models.Index(fields=['organization', 'assigned_to'], name='assign_org_user_idx'), models.Index(fields=['organization', 'department'], name='assign_org_dept_idx'), models.Index(fields=['organization', 'location'], name='assign_org_loc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('asset',), name='uniq_active_assign_asset'), models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('assigned_at')), _connector='OR'), name='assign_dates_valid'), models.CheckConstraint(condition=models.Q(models.Q(('returned_at__isnull', True), ('returned_by__isnull', True)), models.Q(('returned_at__isnull', False), ('returned_by__isnull', False)), _connector='OR'), name='assign_return_actor_valid')],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=10)),
                ('reason', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='assets.asset')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_cancelled', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_completed', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_from', to='organizations.department')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_from', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers', to='organizations.organization')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_to', to='organizations.department')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfers_to', to='organizations.location')),
            ],
            options={
                'ordering': ('-requested_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='transfer_org_status_idx'), models.Index(fields=['organization', 'asset'], name='transfer_org_asset_idx'), models.Index(fields=['organization', 'requested_at'], name='transfer_org_req_idx'), models.Index(fields=['organization', 'completed_at'], name='transfer_org_done_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('REQUESTED', 'APPROVED'))), fields=('asset',), name='uniq_open_transfer_asset'), models.CheckConstraint(condition=models.Q(('status__in', ['REQUESTED', 'APPROVED', 'COMPLETED', 'REJECTED', 'CANCELLED'])), name='transfer_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('from_department__isnull', True), ('to_department__isnull', False)), models.Q(('from_department__isnull', False), ('to_department__isnull', True)), models.Q(('from_department__isnull', False), ('to_department__isnull', False), models.Q(('from_department', models.F('to_department')), _negated=True)), models.Q(('from_location__isnull', True), ('to_location__isnull', False)), models.Q(('from_location__isnull', False), ('to_location__isnull', True)), models.Q(('from_location__isnull', False), ('to_location__isnull', False), models.Q(('from_location', models.F('to_location')), _negated=True)), _connector='OR'), name='transfer_destination_differs'), models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('completed_at__isnull', True), ('completed_by__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'REQUESTED')), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('completed_at__isnull', True), ('completed_by__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'APPROVED')), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('completed_at__isnull', False), ('completed_by__isnull', False), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'COMPLETED')), models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('completed_at__isnull', True), ('completed_by__isnull', True), ('rejected_at__isnull', False), ('rejected_by__isnull', False), ('status', 'REJECTED')), models.Q(('approved_at__isnull', True), ('approved_by__isnull', True), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('completed_at__isnull', True), ('completed_by__isnull', True), ('rejected_at__isnull', True), ('rejected_by__isnull', True), ('status', 'CANCELLED')), _connector='OR'), name='transfer_state_fields_valid'), models.CheckConstraint(condition=models.Q(('approved_at__isnull', True), ('approved_at__gte', models.F('requested_at')), _connector='OR'), name='transfer_approve_time_valid'), models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('requested_at')), _connector='OR'), name='transfer_complete_time_valid'), models.CheckConstraint(condition=models.Q(('rejected_at__isnull', True), ('rejected_at__gte', models.F('requested_at')), _connector='OR'), name='transfer_reject_time_valid'), models.CheckConstraint(condition=models.Q(('cancelled_at__isnull', True), ('cancelled_at__gte', models.F('requested_at')), _connector='OR'), name='transfer_cancel_time_valid')],
            },
        ),
    ]
