"""Frozen M10.8 curated output contract and financial field declarations."""

CONTRACT_VERSION = 1
TRANSFORM_VERSION = 1
MONEY_TYPE = "decimal(28,2)"
QUANTITY_TYPE = "decimal(18,6)"

CURATED_SCHEMAS = {
    "asset_financial_position": (
        ("organization_id", "string"),
        ("asset_id", "string"),
        ("asset_tag", "string"),
        ("asset_name", "string"),
        ("status", "string"),
        ("condition", "string"),
        ("category", "string"),
        ("department", "string"),
        ("department_id", "string"),
        ("location", "string"),
        ("capitalized_cost", MONEY_TYPE),
        ("accumulated_depreciation", MONEY_TYPE),
        ("current_book_value", MONEY_TYPE),
        ("acquisition_id", "string"),
        ("acquisition_date", "date"),
        ("acquisition_currency", "string"),
        ("acquisition_total_cost", MONEY_TYPE),
        ("capitalization_date", "date"),
        ("available_for_use_date", "date"),
        ("source_as_of", "timestamp"),
        ("source_generated_at", "timestamp"),
        ("source_snapshot_id", "string"),
        ("source_logical_record_id", "string"),
    ),
    "depreciation_analytics": (
        ("organization_id", "string"),
        ("depreciation_entry_id", "string"),
        ("asset_tag", "string"),
        ("department", "string"),
        ("department_id", "string"),
        ("accounting_year", "integer"),
        ("accounting_month", "integer"),
        ("period_start", "date"),
        ("opening_book_value", MONEY_TYPE),
        ("depreciation_expense", MONEY_TYPE),
        ("accumulated_depreciation", MONEY_TYPE),
        ("closing_book_value", MONEY_TYPE),
        ("posted_at", "timestamp"),
        ("source_as_of", "timestamp"),
        ("source_snapshot_id", "string"),
        ("source_logical_record_id", "string"),
    ),
    "maintenance_analytics": (
        ("organization_id", "string"),
        ("record_kind", "string"),
        ("record_id", "string"),
        ("work_order_number", "string"),
        ("asset_tag", "string"),
        ("department", "string"),
        ("department_id", "string"),
        ("maintenance_type", "string"),
        ("priority", "string"),
        ("status", "string"),
        ("cost_type", "string"),
        ("event_at", "timestamp"),
        ("quantity", QUANTITY_TYPE),
        ("unit_cost", MONEY_TYPE),
        ("total_cost", MONEY_TYPE),
        ("source_as_of", "timestamp"),
        ("source_snapshot_id", "string"),
        ("source_logical_record_id", "string"),
    ),
    "asset_lifecycle_events": (
        ("organization_id", "string"),
        ("event_id", "string"),
        ("source_dataset", "string"),
        ("source_record_id", "string"),
        ("event_type", "string"),
        ("asset_tag", "string"),
        ("event_at", "timestamp"),
        ("status", "string"),
        ("source_entity_type", "string"),
        ("source_entity_id", "string"),
        ("amount_kind", "string"),
        ("amount", MONEY_TYPE),
        ("source_as_of", "timestamp"),
        ("source_snapshot_id", "string"),
    ),
    "assurance_analytics": (
        ("organization_id", "string"),
        ("record_kind", "string"),
        ("record_id", "string"),
        ("finding_id", "string"),
        ("asset_tag", "string"),
        ("finding_type", "string"),
        ("severity", "string"),
        ("status", "string"),
        ("source", "string"),
        ("occurrence_count", "long"),
        ("detected_at", "timestamp"),
        ("description", "string"),
        ("source_as_of", "timestamp"),
        ("source_snapshot_id", "string"),
    ),
    "executive_asset_summary": (
        ("organization_id", "string"),
        ("asset_register_as_of", "timestamp"),
        ("asset_count", "long"),
        ("active_asset_count", "long"),
        ("disposed_asset_count", "long"),
        ("capitalized_cost", MONEY_TYPE),
        ("accumulated_depreciation", MONEY_TYPE),
        ("current_book_value", MONEY_TYPE),
        ("depreciation_expense_total", MONEY_TYPE),
        ("maintenance_cost_total", MONEY_TYPE),
        ("disposal_proceeds", MONEY_TYPE),
        ("disposal_gain_or_loss", MONEY_TYPE),
        ("open_assurance_findings", "long"),
        ("critical_assurance_findings", "long"),
        ("source_manifest_sha256", "string"),
    ),
}

REQUIRED_SOURCE_DATASETS = frozenset({"asset_register"})
