import assert from 'node:assert/strict';
import { ApiClient } from '../src/services/apiClient';
import { ApiError } from '../src/services/apiError';
import { DjangoDashboardRepository } from '../src/services/dashboardRepository';
import { Session } from '../src/services/session';
import { DjangoAssetRepository } from '../src/services/djangoApiBridge';

let stage = 'session setup';
async function run() {
  const storage = new Map<string, string>();
  const api = new ApiClient(process.env.F1_SMOKE_URL!);
  const session = new Session(api, { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value), removeItem: key => storage.delete(key) }, () => {});
  await session.initialize();
  stage = 'authorized asset manager login';
  await session.login(process.env.F1_SMOKE_EMAIL!, process.env.F1_SMOKE_PASSWORD!);
  const dashboard = new DjangoDashboardRepository(api), assets = new DjangoAssetRepository(api);
  stage = 'initial organization-scoped dashboard';
  const initial = await dashboard.metrics();
  assert.equal(initial.portfolio.registeredAssets, 2);
  assert.equal(initial.portfolio.currentlyHeldAssets, 2);
  assert.equal(initial.financial.capitalizedCost, '300.30');
  assert.equal(initial.financial.accumulatedDepreciation, '30.15');
  assert.equal(initial.financial.bookValue, '270.15');
  assert.equal(initial.financial.currentMonthPostedDepreciation, '30.15');
  assert.ok(initial.trends.postedDepreciation.some(row => row.amount === '30.15'));
  assert.ok(initial.trends.capitalizations.some(row => row.period === '2026-01' && row.amount === '300.30'));
  assert.equal(initial.operations.openWorkOrders, 2);
  assert.equal(initial.scope, 'organization');
  assert.equal(initial.currency, 'NGN');
  stage = 'legitimate domain mutation and dashboard refresh';
  const categories = await assets.getCategories();
  assert.ok(categories.length);
  await assets.createAsset({ asset_tag: 'F13-NEW-DRAFT', name: 'F13 post-read draft', description: '', category_id: categories[0].id, department_id: null, location_id: null, manufacturer: '', model_number: '', serial_number: '', acquisition_date: '2026-10-06', available_for_use_date: null, purchase_cost: '55.00', residual_value: '0.00', useful_life_months: 36, depreciation_method: 'SLM' });
  const refreshed = await dashboard.metrics();
  assert.equal(refreshed.portfolio.registeredAssets, 3);
  assert.equal(refreshed.portfolio.currentlyHeldAssets, 2);
  assert.equal(refreshed.financial.capitalizedCost, '300.30');
  stage = 'department manager scope';
  session.logout();
  await session.login('f13-dept@example.test', process.env.F1_SMOKE_PASSWORD!);
  const department = await dashboard.metrics();
  assert.equal(department.scope, 'department');
  assert.equal(department.portfolio.registeredAssets, 1);
  assert.equal(department.financial.capitalizedCost, '100.10');
  assert.equal(department.financial.bookValue, '90.05');
  stage = 'employee permission denial';
  session.logout();
  await session.login('f13-employee@example.test', process.env.F1_SMOKE_PASSWORD!);
  await assert.rejects(dashboard.metrics(), error => error instanceof ApiError && error.status === 403);
  stage = 'logout';
  session.logout();
  assert.equal(storage.size, 0);
  console.log('PASS: isolated TypeScript → authenticated HTTP → Django/PostgreSQL F13 exact Decimal totals 300.30 / 30.15 / 270.15; child-work-order rows did not multiply asset value; second tenant excluded; post-mutation registered count refreshed 2→3; department scope and employee 403 verified.');
}
void run().catch(error => {
  const detail = error instanceof ApiError ? `${error.kind}${error.status ? ` HTTP ${error.status}` : ''}` : error instanceof AssertionError ? error.message.slice(0, 250) : error instanceof Error ? error.name : 'runtime failure';
  console.log(`SMOKE: failed at ${stage}; ${detail}`);
  process.exitCode = 1;
});
