// Run only from f1-smoke.py against its random, disposable PostgreSQL database.
import assert from 'node:assert/strict';
import { ApiClient, } from '../src/services/apiClient';
import { ApiError } from '../src/services/apiError';
import { Session } from '../src/services/session';
import { AcquisitionWorkflow } from '../src/services/acquisitionWorkflow';
import { emptyAcquisitionForm } from '../src/services/acquisitionForm';
import { DjangoAssetRepository } from '../src/services/djangoApiBridge';
import { DjangoMovementRepository } from '../src/services/movementRepository';

let stage='session setup';
async function run(){
 const storage=new Map<string,string>();const api=new ApiClient(process.env.F1_SMOKE_URL!);const session=new Session(api,{getItem:key=>storage.get(key)??null,setItem:(key,value)=>{storage.set(key,value);},removeItem:key=>{storage.delete(key);}},()=>{});
 await session.initialize();stage='JWT login';await session.login(process.env.F1_SMOKE_EMAIL!,process.env.F1_SMOKE_PASSWORD!);assert.equal(session.getSnapshot().user?.role,'ASSET_MANAGER');
 const assets=new DjangoAssetRepository(api);const moves=new DjangoMovementRepository(api);
 stage='load tenant references and custodian';const [categories,departments,locations,custodians]=await Promise.all([assets.getCategories(),assets.getReferences('departments'),assets.getReferences('locations'),moves.custodians()]);
 const department=departments.find(row=>row.code==='OPS')!;const destinationDepartment=departments.find(row=>row.code==='OPS-DST')!;const location=locations.find(row=>row.code==='PLANT')!;const destinationLocation=locations.find(row=>row.code==='PLANT-DST')!;const custodian=custodians.find(row=>row.role==='EMPLOYEE')!;assert.ok(department&&destinationDepartment&&location&&destinationLocation&&custodian);
 stage='capitalize disposable active asset';const form={...emptyAcquisitionForm,tag:'F4-SMOKE-001',name:'Disposable F4 movement asset',description:'Isolated custody and placement integration smoke',categoryId:categories[0].id,departmentId:department.id,locationId:location.id,acquisitionDate:'2026-02-01',capitalizationDate:'2026-02-02',usefulLifeMonths:'36',residualValue:'100.00',purchase:'1000.01',freight:'0.99'};const workflow=new AcquisitionWorkflow(assets,()=>session.getSnapshot().user!==null,async()=>{});await workflow.create(form);await workflow.record(form);await workflow.capitalize();const assetId=workflow.getSnapshot().asset!.id;
 stage='create custody assignment and confirm active state';const before=await assets.getAssetById(assetId);const assignment=await moves.createAssignment({asset_id:assetId,assigned_to_id:custodian.id,notes:'F4 integration smoke'});assert.equal(assignment.custodianId,custodian.id);assert.equal(assignment.returnedAt,null);const activeAssignments=await moves.assignments({asset:assetId,active:true});assert.equal(activeAssignments.length,1);assert.equal(activeAssignments[0].id,assignment.id);const afterAssign=await assets.getAssetById(assetId);assert.deepEqual([afterAssign.department?.id,afterAssign.location?.id],[before.department?.id,before.location?.id]);assert.deepEqual([assignment.departmentId,assignment.locationId],[before.department?.id,before.location?.id]);
 stage='request and approve backend transfer';const transfer=await moves.createTransfer({asset_id:assetId,to_department_id:destinationDepartment.id,to_location_id:destinationLocation.id,reason:'F4 smoke placement transfer',notes:'Backend derives the source placement'});assert.equal(transfer.status,'REQUESTED');assert.deepEqual([transfer.fromDepartmentId,transfer.fromLocationId],[before.department?.id,before.location?.id]);assert.deepEqual([(await assets.getAssetById(assetId)).department?.id,(await assets.getAssetById(assetId)).location?.id],[before.department?.id,before.location?.id]);const approved=await moves.transition(transfer.id,'approve');assert.equal(approved.status,'APPROVED');const afterApproval=await assets.getAssetById(assetId);assert.deepEqual([afterApproval.department?.id,afterApproval.location?.id],[before.department?.id,before.location?.id]);
 stage='complete transfer and verify placement/custody separation';const completed=await moves.transition(transfer.id,'complete');assert.equal(completed.status,'COMPLETED');const finalTransfer=await moves.transfer(transfer.id);assert.equal(finalTransfer.status,'COMPLETED');const finalAsset=await assets.getAssetById(assetId);assert.deepEqual([finalAsset.department?.id,finalAsset.location?.id],[destinationDepartment.id,destinationLocation.id]);const custodyAfterTransfer=await moves.assignments({asset:assetId,active:true});assert.equal(custodyAfterTransfer.length,1);assert.equal(custodyAfterTransfer[0].id,assignment.id);assert.equal(custodyAfterTransfer[0].custodianId,custodian.id);
 stage='return custody and retain history';const returned=await moves.returnAssignment(assignment.id);assert.ok(returned.returnedAt);const history=await moves.assignments({asset:assetId});assert.equal(history.length,1);assert.ok(history[0].returnedAt);const afterReturn=await assets.getAssetById(assetId);assert.deepEqual([afterReturn.department?.id,afterReturn.location?.id],[destinationDepartment.id,destinationLocation.id]);
 stage='reject repeated completion';await assert.rejects(moves.transition(transfer.id,'complete'),(error:unknown)=>error instanceof ApiError&&error.kind==='validation');assert.equal((await moves.transfers({asset:assetId}))[0].status,'COMPLETED');
 stage='logout';session.logout();assert.equal(storage.size,0);assert.equal(session.getSnapshot().user,null);console.log('PASS: isolated TypeScript-to-Django-to-PostgreSQL F4 workflow; assignment creation preserves placement, active custody survives transfer completion, request and approval preserve placement, completion changes placement, return preserves destination placement and history, repeated completion is rejected.');
}
void run().catch(error=>{console.log(`SMOKE: failed at ${stage}; ${error instanceof ApiError?`${error.kind}, HTTP ${error.status??'none'}`:'assertion or runtime failure'}`);process.exitCode=1;});
