// Run only from f1-smoke.py against its random, disposable PostgreSQL database.
import assert from 'node:assert/strict';
import { ApiClient } from '../src/services/apiClient';
import { ApiError } from '../src/services/apiError';
import { Session } from '../src/services/session';
import { AcquisitionWorkflow } from '../src/services/acquisitionWorkflow';
import { emptyAcquisitionForm } from '../src/services/acquisitionForm';
import { DjangoAssetRepository } from '../src/services/djangoApiBridge';
import { DjangoDepreciationRepository } from '../src/services/depreciationRepository';
import { DjangoMaintenanceRepository } from '../src/services/maintenanceRepository';

let stage='session setup';
async function run(){
 const storage=new Map<string,string>();const api=new ApiClient(process.env.F1_SMOKE_URL!);const session=new Session(api,{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},()=>{});
 await session.initialize();stage='JWT login';await session.login(process.env.F1_SMOKE_EMAIL!,process.env.F1_SMOKE_PASSWORD!);assert.equal(session.getSnapshot().user?.role,'ASSET_MANAGER');
 const assets=new DjangoAssetRepository(api), depreciation=new DjangoDepreciationRepository(api), maintenance=new DjangoMaintenanceRepository(api);
 stage='fetch references and capitalize isolated asset';const[categories,departments,locations]=await Promise.all([assets.getCategories(),assets.getReferences('departments'),assets.getReferences('locations')]);const form={...emptyAcquisitionForm,tag:'F5-SMOKE-001',name:'Disposable F5 maintenance asset',description:'Isolated maintenance accounting boundary smoke',categoryId:categories[0].id,departmentId:departments[0].id,locationId:locations[0].id,acquisitionDate:'2026-02-01',capitalizationDate:'2026-02-02',usefulLifeMonths:'36',residualValue:'100.00',purchase:'1000.01',freight:'0.99'};const workflow=new AcquisitionWorkflow(assets,()=>session.getSnapshot().user!==null,async()=>{});await workflow.create(form);await workflow.record(form);await workflow.capitalize();const assetId=workflow.getSnapshot().asset!.id;
 stage='capture authoritative asset and depreciation state';const before=await assets.getAssetById(assetId);const beforeSchedules=await depreciation.getSchedules();const beforeEntries=await depreciation.getEntries({asset:assetId});const financial=(a:typeof before)=>[a.purchaseCost,a.residualValue,a.usefulLifeMonths,a.depreciationMethod,a.accumulatedDepreciation,a.bookValue];const beforeFinancial=financial(before);
 stage='read, create and deactivate maintenance plan';const initialPlans=await maintenance.plans({asset:assetId});assert.equal(initialPlans.count,0);const plan=await maintenance.createPlan({asset_id:assetId,maintenance_type:'PREVENTIVE',frequency_value:3,frequency_unit:'MONTHS',next_due_date:'2026-05-02',active:true,instructions:'Isolated smoke plan'});assert.equal(plan.active,true);assert.equal((await maintenance.plans({asset:assetId})).results[0].id,plan.id);await maintenance.updatePlan(plan.id,{active:false});assert.equal((await maintenance.plans({asset:assetId,active:false})).results[0].active,false);
 stage='create and assign work order';const order=await maintenance.createWorkOrder({asset_id:assetId,maintenance_type:'CORRECTIVE',priority:'HIGH',description:'F5 disposable bearing service',due_date:'2026-03-01',diagnosis:'Bearing noise'});assert.match(order.number,/^WO-/);assert.equal(order.status,'OPEN');assert.equal((await maintenance.workOrders({page:1,pageSize:25,asset:assetId})).results[0].id,order.id);const assigned=await maintenance.assign(order.id,session.getSnapshot().user!.id);assert.equal(assigned.status,'ASSIGNED');assert.equal(assigned.assignedToId,session.getSnapshot().user!.id);
 stage='start work order and verify only lifecycle state changes';const started=await maintenance.start(order.id);assert.equal(started.status,'IN_PROGRESS');assert.equal((await assets.getAssetById(assetId)).status,'IN_MAINTENANCE');assert.deepEqual(financial(await assets.getAssetById(assetId)),beforeFinancial);
 stage='create exact Decimal maintenance cost';const cost=await maintenance.createCost({work_order_id:order.id,cost_type:'PARTS',description:'Replacement bearing',quantity:'2.500',unit_cost:'13.37',vendor_reference:'F5-INV-001',incurred_at:'2026-02-03T10:00:00Z'});assert.deepEqual([cost.quantity,cost.unitCost,cost.totalCost],['2.500','13.37','33.43']);assert.equal((await maintenance.costs({work_order:order.id})).results.length,1);
 stage='complete order and verify generated record';const completed=await maintenance.complete(order.id,{resolution:'Bearing replaced',completion_notes:'Operational test passed',downtime_minutes:45,maintenance_date:'2026-02-03'});assert.equal(completed.workOrder.status,'COMPLETED');assert.equal(completed.record.totalCost,'33.43');assert.equal((await maintenance.records({asset:assetId})).results.length,1);assert.equal((await maintenance.workOrder(order.id)).status,'COMPLETED');
 stage='verify repeated completion is rejected and reconciled';await assert.rejects(maintenance.complete(order.id,{resolution:'Duplicate',completion_notes:'',downtime_minutes:null,maintenance_date:'2026-02-03'}),(e:unknown)=>e instanceof ApiError&&e.kind==='validation');assert.equal((await maintenance.records({asset:assetId})).results.length,1);
 stage='verify accounting invariance';const after=await assets.getAssetById(assetId);assert.deepEqual(financial(after),beforeFinancial);assert.equal(after.status,'ACTIVE');assert.deepEqual((await depreciation.getSchedules()).filter(x=>x.assetId===assetId),beforeSchedules.filter(x=>x.assetId===assetId));assert.deepEqual(await depreciation.getEntries({asset:assetId}),beforeEntries);
 stage='logout';session.logout();assert.equal(storage.size,0);assert.equal(session.getSnapshot().user,null);console.log('PASS: isolated TypeScript → Django → PostgreSQL F5 plan create/deactivate, work-order create/assign/start, exact Decimal cost, completion-generated history, repeated completion rejection, logout and unchanged asset/depreciation accounting state.');
}
void run().catch(error=>{console.log(`SMOKE: failed at ${stage}; ${error instanceof ApiError?`${error.kind}, HTTP ${error.status??'none'}`:'assertion or runtime failure'}`);process.exitCode=1;});
