// Run only from f1-smoke.py against its random, disposable PostgreSQL database.
import assert from 'node:assert/strict';
import { ApiClient } from '../src/services/apiClient';
import { ApiError } from '../src/services/apiError';
import { Session } from '../src/services/session';
import { AcquisitionWorkflow } from '../src/services/acquisitionWorkflow';
import { emptyAcquisitionForm } from '../src/services/acquisitionForm';
import { DjangoAssetRepository } from '../src/services/djangoApiBridge';
import { DjangoDepreciationRepository } from '../src/services/depreciationRepository';
import { DjangoDisposalRepository } from '../src/services/disposalRepository';

let stage='session setup';
async function run(){
 const storage=new Map<string,string>();const api=new ApiClient(process.env.F1_SMOKE_URL!);const session=new Session(api,{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},()=>{});
 await session.initialize();stage='JWT login';await session.login(process.env.F1_SMOKE_EMAIL!,process.env.F1_SMOKE_PASSWORD!);assert.equal(session.getSnapshot().user?.role,'ASSET_MANAGER');
 const assets=new DjangoAssetRepository(api),depreciation=new DjangoDepreciationRepository(api),disposals=new DjangoDisposalRepository(api);
 stage='create and capitalize disposable asset';const[categories,departments,locations]=await Promise.all([assets.getCategories(),assets.getReferences('departments'),assets.getReferences('locations')]);const form={...emptyAcquisitionForm,tag:'F6-SMOKE-001',name:'Disposable F6 derecognition asset',description:'Isolated disposal carrying amount smoke',categoryId:categories[0].id,departmentId:departments[0].id,locationId:locations[0].id,acquisitionDate:'2026-02-01',capitalizationDate:'2026-02-02',usefulLifeMonths:'36',residualValue:'100.00',purchase:'1000.01',freight:'0.99'};const workflow=new AcquisitionWorkflow(assets,()=>session.getSnapshot().user!==null,async()=>{});await workflow.create(form);await workflow.record(form);await workflow.capitalize();const assetId=workflow.getSnapshot().asset!.id;
 stage='post one depreciation period before disposal';const schedule=await depreciation.createSchedule(assetId);assert.equal(schedule.assetId,assetId);const period=await depreciation.createPeriod(2026,2);const posted=await depreciation.post(assetId,period.id);assert.equal(posted.depreciationAmount,'25.03');
 stage='capture authoritative pre-disposal state';const before=await assets.getAssetById(assetId);const beforeEntries=await depreciation.getEntries({asset:assetId});const beforeAccounting=[before.purchaseCost,before.residualValue,before.usefulLifeMonths,before.depreciationMethod,before.accumulatedDepreciation,before.bookValue];assert.deepEqual(beforeAccounting,['1001.00','100.00',36,'SLM','25.03','975.97']);assert.equal(before.status,'ACTIVE');assert.equal(beforeEntries.length,1);
 stage='read eligibility/history and create disposal draft';assert.equal((await disposals.list({page:1,pageSize:25,asset:assetId})).count,0);const draft=await disposals.create({asset_id:assetId,disposal_date:'2026-02-03',disposal_method:'SALE',reason:'F6 isolated smoke sale',proceeds:'1200.00'});assert.equal(draft.status,'DRAFT');assert.equal(draft.carryingAmount,null);assert.deepEqual((await assets.getAssetById(assetId)).status,'ACTIVE');
 stage='submit and approve with a separate user';const submitted=await disposals.submit(draft.id);assert.equal(submitted.status,'PENDING_APPROVAL');const approverStorage=new Map<string,string>();const approverApi=new ApiClient(process.env.F1_SMOKE_URL!);const approverSession=new Session(approverApi,{getItem:key=>approverStorage.get(key)??null,setItem:(key,value)=>approverStorage.set(key,value),removeItem:key=>approverStorage.delete(key)},()=>{});await approverSession.initialize();await approverSession.login(process.env.F1_SMOKE_APPROVER_EMAIL!,process.env.F1_SMOKE_PASSWORD!);assert.equal(approverSession.getSnapshot().user?.role,'ADMIN');const approverDisposals=new DjangoDisposalRepository(approverApi);assert.equal((await approverDisposals.approve(draft.id)).status,'APPROVED');
 stage='complete and verify backend derecognition snapshot';const completed=await disposals.complete(draft.id);assert.equal(completed.status,'COMPLETED');assert.deepEqual([completed.capitalizedCost,completed.accumulatedDepreciation,completed.carryingAmount,completed.proceeds,completed.gainOrLoss],['1001.00','25.03','975.97','1200.00','224.03']);assert.equal((await disposals.get(draft.id)).status,'COMPLETED');const history=await disposals.list({page:1,pageSize:25,asset:assetId,status:'COMPLETED'});assert.equal(history.count,1);assert.equal(history.results[0].id,draft.id);
 stage='verify authoritative asset and depreciation invariance';const after=await assets.getAssetById(assetId);assert.equal(after.status,'DISPOSED');assert.deepEqual([after.purchaseCost,after.residualValue,after.usefulLifeMonths,after.depreciationMethod,after.accumulatedDepreciation,after.bookValue],beforeAccounting);assert.deepEqual(await depreciation.getEntries({asset:assetId}),beforeEntries);
 stage='verify repeated disposal/completion and post-disposal depreciation are rejected';await assert.rejects(disposals.create({asset_id:assetId,disposal_date:'2026-02-03',disposal_method:'SALE',reason:'Repeated F6 smoke',proceeds:'0.00'}),(e:unknown)=>e instanceof ApiError);await assert.rejects(disposals.complete(draft.id),(e:unknown)=>e instanceof ApiError);const nextPeriod=await depreciation.createPeriod(2026,3);await assert.rejects(depreciation.post(assetId,nextPeriod.id),(e:unknown)=>e instanceof ApiError);assert.equal((await disposals.list({page:1,pageSize:25,asset:assetId})).count,1);
 stage='logout';approverSession.logout();session.logout();assert.equal(storage.size,0);assert.equal(session.getSnapshot().user,null);assert.equal(approverSession.getSnapshot().user,null);
 console.log('PASS: isolated TypeScript → Django → PostgreSQL F6 workflow; capitalized asset 1001.00, one posted depreciation entry 25.03, backend carrying amount 975.97, proceeds 1200.00, backend gain 224.03, DISPOSED status, preserved asset/depreciation balances, separate approval, duplicate disposal/completion and post-disposal depreciation rejected, logout.');
}
void run().catch(error=>{console.log(`SMOKE: failed at ${stage}; ${error instanceof ApiError?`${error.kind}, HTTP ${error.status??'none'}`:'assertion or runtime failure'}`);process.exitCode=1;});
