import assert from 'node:assert/strict';
import { ApiClient } from '../src/services/apiClient';
import { Session } from '../src/services/session';
import { DjangoAssetRepository } from '../src/services/djangoApiBridge';
import { DjangoMovementRepository } from '../src/services/movementRepository';
import { DjangoVerificationRepository } from '../src/services/verificationRepository';

let stage='session setup';
async function run(){
 const storage=new Map<string,string>(),api=new ApiClient(process.env.F1_SMOKE_URL!);const session=new Session(api,{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},()=>{});
 await session.initialize();stage='JWT login';await session.login(process.env.F1_SMOKE_EMAIL!,process.env.F1_SMOKE_PASSWORD!);assert.equal(session.getSnapshot().user?.role,'ASSET_MANAGER');
 const assets=new DjangoAssetRepository(api),movement=new DjangoMovementRepository(api),verification=new DjangoVerificationRepository(api);
 stage='read isolated department reference data';const departments=await assets.getReferences('departments');stage='read isolated location reference data';const locations=await assets.getReferences('locations');stage='read two isolated registered assets';const allAssets=await assets.getAllAssets({pageSize:100,search:'',status:'',category:'',department:'',location:'',ordering:'tag'});assert.equal(allAssets.total,2);const departmentA=departments.find(x=>x.name==='Operations')!,departmentB=departments.find(x=>x.name==='Finance')!,locationA=locations.find(x=>x.name==='Main Plant')!,locationB=locations.find(x=>x.name==='Remote Plant')!;assert.ok(departmentA&&departmentB&&locationA&&locationB);
 const first=allAssets.data.find(x=>x.tag==='F7-SMOKE-01')!,second=allAssets.data.find(x=>x.tag==='F7-SMOKE-02')!;assert.ok(first&&second);
 stage='capture authoritative before-state for the mismatch asset';const before=await assets.getAssetById(second.id),beforeAssignments=await movement.assignments({asset:second.id,active:true});const snapshot=(a:typeof before)=>({tag:a.tag,department:a.department?.id??null,location:a.location?.id??null,status:a.status,condition:a.condition,acquisitionDate:a.acquisitionDate,capitalizationDate:a.capitalizationDate,availableForUseDate:a.availableForUseDate,depreciationMethod:a.depreciationMethod,usefulLifeMonths:a.usefulLifeMonths,purchaseCost:a.purchaseCost,residualValue:a.residualValue,accumulatedDepreciation:a.accumulatedDepreciation,bookValue:a.bookValue});const beforeMaster=snapshot(before);
 stage='create and open authoritative organization campaign';const campaign=await verification.createCampaign({name:'F7 isolated physical verification',description:'Disposable PostgreSQL integration smoke',scope_type:'ORGANIZATION',start_date:'2026-10-05'});assert.equal(campaign.status,'DRAFT');assert.equal(campaign.expected,2);const opened=await verification.transitionCampaign(campaign.id,'start');assert.equal(opened.status,'OPEN');
 stage='record matching registered observation';const matching=await verification.createObservation({campaign_id:campaign.id,asset_id:first.id,observed_asset_tag:first.tag,observed_description:'Matching physical inspection',observed_location_id:locationA.id,observed_department_id:departmentA.id,observed_condition:'GOOD',notes:'F7 matching registered observation'});assert.equal(matching.assetId,first.id);assert.equal(matching.result,'VERIFIED');assert.equal(matching.exceptions.length,0);
 stage='record deliberately mismatching registered observation';const mismatch=await verification.createObservation({campaign_id:campaign.id,asset_id:second.id,observed_asset_tag:'F7-OBSERVED-WRONG-TAG',observed_description:'Observed mismatch; master data must stay unchanged',observed_location_id:locationB.id,observed_department_id:departmentB.id,observed_condition:'DAMAGED',notes:'F7 mismatch non-overwrite invariant'});assert.equal(mismatch.result,'CONDITION_MISMATCH');assert.deepEqual(new Set(mismatch.exceptions.map(x=>x.type)),new Set(['TAG_MISMATCH','LOCATION_MISMATCH','DEPARTMENT_MISMATCH','CUSTODY_MISMATCH','CONDITION_MISMATCH','DAMAGED_ASSET']));
 stage='record unregistered physical observation';const unregistered=await verification.createObservation({campaign_id:campaign.id,observed_asset_tag:'F7-UNREGISTERED-01',observed_description:'Unregistered found item',observed_location_id:locationA.id,observed_department_id:departmentA.id,observed_condition:'FAIR',notes:'No Asset should be created'});assert.equal(unregistered.assetId,null);assert.equal(unregistered.result,'UNREGISTERED_ASSET');
 stage='record evidence metadata only';const note=await verification.addNote({verification_id:mismatch.id,evidence_type:'NOTE',description:'Observed tag and physical placement differ.',external_reference:'F7-OBS-NOTE'});assert.equal(note.integrity,'METADATA_ONLY');
 stage='reconcile observations, exceptions and evidence from Django';const observations=await verification.observations({page:1,pageSize:100,campaign:campaign.id}),exceptions=await verification.exceptions({page:1,pageSize:100,campaign:campaign.id}),evidence=await verification.evidence(mismatch.id);assert.equal(observations.count,3);assert.equal(exceptions.count,7);assert.equal(evidence.count,1);assert.equal(observations.results.find(x=>x.id===unregistered.id)?.assetId,null);
 stage='complete campaign';const completed=await verification.transitionCampaign(campaign.id,'complete');assert.equal(completed.status,'COMPLETED');assert.equal(completed.verified,2);assert.equal(completed.exceptionCount,exceptions.count);
 stage='prove observation left master data and custody untouched';const after=await assets.getAssetById(second.id),afterAssignments=await movement.assignments({asset:second.id,active:true});assert.deepEqual(snapshot(after),beforeMaster);assert.deepEqual(afterAssignments,beforeAssignments);const finalAssets=await assets.getAllAssets({pageSize:100,search:'',status:'',category:'',department:'',location:'',ordering:'tag'});assert.equal(finalAssets.total,2);assert.equal(observations.results.find(x=>x.id===mismatch.id)?.assetTag,before.tag);
 stage='logout';session.logout();assert.equal(storage.size,0);assert.equal(session.getSnapshot().user,null);
 console.log('PASS: isolated TypeScript → Django → PostgreSQL F7 campaign DRAFT→OPEN→IN_PROGRESS→COMPLETED; matching VERIFIED; mismatch CONDITION_MISMATCH with tag/location/department/custody/condition/damage exceptions; unregistered remains unlinked; NOTE metadata only; asset tag/department/location/status/custodian/financial values and 2-asset count unchanged; authoritative history and logout verified.');
}
void run().catch(error=>{const safe=error instanceof Error?error.name:'runtime failure';const detail=error instanceof Error&&'kind' in error?`${String((error as {kind:unknown}).kind)}${'status' in error?` HTTP ${String((error as {status:unknown}).status)}`:''}${'message' in error?`; ${String((error as {message:unknown}).message)}`:''}${'fields' in error?`; fields ${Object.keys((error as {fields:Record<string,unknown>}).fields).join(',')}`:''}`:'';console.log(`SMOKE: failed at ${stage}; ${safe}${detail?`; ${detail}`:''}`);process.exitCode=1;});
