import assert from 'node:assert/strict';
import {ApiClient} from '../src/services/apiClient';
import {Session} from '../src/services/session';
import {DjangoAssetRepository} from '../src/services/djangoApiBridge';
import {DjangoMovementRepository} from '../src/services/movementRepository';
import {DjangoAssuranceRepository} from '../src/services/assuranceRepository';

let stage='session setup';
async function run(){
 const storage=new Map<string,string>(),api=new ApiClient(process.env.F1_SMOKE_URL!);const session=new Session(api,{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},()=>{});
 await session.initialize();stage='JWT login';await session.login(process.env.F1_SMOKE_EMAIL!,process.env.F1_SMOKE_PASSWORD!);assert.equal(session.getSnapshot().user?.role,'ASSET_MANAGER');
 const assets=new DjangoAssetRepository(api),movement=new DjangoMovementRepository(api),assurance=new DjangoAssuranceRepository(api);
 stage='read fixture asset';const list=await assets.getAllAssets({pageSize:100,search:'',status:'',category:'',department:'',location:'',ordering:'tag'});assert.equal(list.total,1);const asset=list.data[0]!;assert.equal(asset.tag,'F8-ASSURANCE-01');
 stage='capture master asset and custody values before run';const before=await assets.getAssetById(asset.id),beforeAssignments=await movement.assignments({asset:asset.id,active:true});assert.equal(beforeAssignments.length,1);
 const snapshot=(row:typeof before)=>({tag:row.tag,department:row.department?.id??null,location:row.location?.id??null,status:row.status,condition:row.condition,acquisitionDate:row.acquisitionDate,capitalizationDate:row.capitalizationDate,availableForUseDate:row.availableForUseDate,depreciationMethod:row.depreciationMethod,usefulLifeMonths:row.usefulLifeMonths,purchaseCost:row.purchaseCost,residualValue:row.residualValue,accumulatedDepreciation:row.accumulatedDepreciation,bookValue:row.bookValue});const beforeMaster=snapshot(before);
 stage='create authoritative pending FULL run';const created=await assurance.createRun({run_type:'FULL',stale_after_days:365});assert.equal(created.status,'PENDING');assert.equal(created.startedByEmail,session.getSnapshot().user?.email);
 stage='dispatch actual assurance Celery task through API';const accepted=await assurance.executeRun(created.id);assert.ok(['RUNNING','COMPLETED'].includes(accepted.status));
 stage='poll authoritative run state until publication completes';let run=accepted;for(let attempt=0;attempt<20&&run.status==='RUNNING';attempt++){await new Promise(resolve=>setTimeout(resolve,150));run=await assurance.run(created.id);}assert.equal(run.status,'COMPLETED');assert.equal(run.phase,'DONE');assert.equal(run.assetsEvaluated,1);assert.equal(run.unitCount,run.unitsCompleted);assert.ok(run.sealedAt);assert.equal(run.executorVersion,1);assert.equal(run.inputSchemaVersion,1);
 stage='read only public findings and occurrence history';const publicPage=await assurance.runFindings(run.id,{page:1,pageSize:100});assert.ok(publicPage.count>=1);assert.ok(publicPage.results.every(finding=>finding.occurrences.some(occurrence=>occurrence.assuranceRunId===run.id)));const bookValue=publicPage.results.find(finding=>finding.type==='BOOK_VALUE_EXCEPTION');assert.ok(bookValue);assert.equal(bookValue.expectedValue,'975.97');assert.equal(bookValue.observedValue,'900.00');assert.equal(bookValue.occurrenceCount,1);assert.equal(bookValue.occurrences.length,1);
 stage='review and resolve public finding using domain actions';const reviewed=await assurance.findingAction(bookValue.id,'review');assert.equal(reviewed.status,'UNDER_REVIEW');const resolved=await assurance.findingAction(bookValue.id,'resolve','Reviewed expected 975.97 against the frozen asset input.');assert.equal(resolved.status,'RESOLVED');assert.equal(resolved.resolvedByEmail,session.getSnapshot().user?.email);assert.ok(resolved.resolvedAt);
 stage='prove evaluation and finding resolution left asset and custody unchanged';const after=await assets.getAssetById(asset.id),afterAssignments=await movement.assignments({asset:asset.id,active:true});assert.deepEqual(snapshot(after),beforeMaster);assert.deepEqual(afterAssignments,beforeAssignments);const finalAssets=await assets.getAllAssets({pageSize:100,search:'',status:'',category:'',department:'',location:'',ordering:'tag'});assert.equal(finalAssets.total,1);const authoritative=await assurance.finding(bookValue.id);assert.equal(authoritative.status,'RESOLVED');assert.equal(authoritative.occurrences.length,1);
 stage='logout';session.logout();assert.equal(storage.size,0);assert.equal(session.getSnapshot().user,null);
 console.log('PASS: isolated TypeScript → Django → PostgreSQL F8 FULL run PENDING→RUNNING→COMPLETED; frozen input versions sealed; public BOOK_VALUE_EXCEPTION and one immutable occurrence; review→resolution through domain actions; asset tag/department/location/custody/lifecycle/financial values and one-asset count unchanged; audit events and logout verified.');
}
void run().catch(error=>{const safe=error instanceof Error?error.name:'runtime failure';const detail=error instanceof Error&&'kind' in error?`${String((error as {kind:unknown}).kind)}${'status' in error?` HTTP ${String((error as {status:unknown}).status)}`:''}${'message' in error?`; ${String((error as {message:unknown}).message)}`:''}${'fields' in error?`; fields ${Object.keys((error as {fields:Record<string,unknown>}).fields).join(',')}`:''}`:'';console.log(`SMOKE: failed at ${stage}; ${safe}${detail?`; ${detail}`:''}`);process.exitCode=1;});
