import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {ApiClient} from '../src/services/apiClient';
import {Session} from '../src/services/session';
import {DjangoReportRepository} from '../src/services/reportRepository';

let stage='session setup';
const snapshotKey='11111111-1111-4111-8111-111111111111';
const csvKey='22222222-2222-4222-8222-222222222222';
const jsonKey='33333333-3333-4333-8333-333333333333';
async function run(){
 const storage=new Map<string,string>(),api=new ApiClient(process.env.F1_SMOKE_URL!);const session=new Session(api,{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},()=>{});
 await session.initialize();stage='JWT login';await session.login(process.env.F1_SMOKE_EMAIL!,process.env.F1_SMOKE_PASSWORD!);assert.equal(session.getSnapshot().user?.role,'ASSET_MANAGER');const reports=new DjangoReportRepository(api);
 stage='read complete role-scoped report catalog';const catalog=await reports.catalog();assert.equal(catalog.length,17);const definition=catalog.find(item=>item.id==='asset_register')!;assert.ok(definition);assert.deepEqual(definition.filters.includes('asset_tag'),true);
 const filters={asset_tag:'F9-REPORT-01'};
 stage='run authoritative live report before source mutation';const initial=await reports.report('asset_register',{page:1,pageSize:25,...filters});assert.equal(initial.count,1);const original=initial.results[0]!;assert.equal(original.asset_tag,'F9-REPORT-01');assert.equal(original.name,'F9 report snapshot original');assert.equal(original.purchase_cost,'1234.56');assert.equal(original.current_book_value,'1200.00');const assetId=String(original.id);
 stage='request durable report snapshot with an idempotency key';const requested=await reports.createSnapshot({report_type:'asset_register',filters,idempotency_key:snapshotKey});const duplicate=await reports.createSnapshot({report_type:'asset_register',filters,idempotency_key:snapshotKey});assert.equal(duplicate.id,requested.id);
 stage='reconcile snapshot generation from authoritative Django status';let snapshot=await reports.snapshot(requested.id);for(let attempt=0;attempt<30&&(snapshot.status==='QUEUED'||snapshot.status==='RUNNING');attempt++){await new Promise(resolve=>setTimeout(resolve,100));snapshot=await reports.snapshot(snapshot.id);}assert.equal(snapshot.status,'COMPLETED');assert.equal(snapshot.schemaVersion,1);assert.ok(snapshot.asOf);assert.equal(snapshot.rowCount,1);
 stage='read versioned durable snapshot rows';const captured=await reports.snapshotRows(snapshot.id,1,25);assert.equal(captured.count,1);assert.equal(captured.results[0]?.payload.name,'F9 report snapshot original');assert.equal(captured.results[0]?.payload.purchase_cost,'1234.56');
 stage='change source asset only after immutable snapshot capture';await api.request(`/assets/${assetId}/`,{method:'PATCH',body:{name:'F9 report snapshot changed after capture'}});
 stage='rerun live query and prove changed source';const changed=await reports.report('asset_register',{page:1,pageSize:25,...filters});assert.equal(changed.results[0]?.name,'F9 report snapshot changed after capture');assert.equal(changed.results[0]?.purchase_cost,'1234.56');
 stage='refetch old snapshot and prove rows stayed immutable';const frozen=await reports.snapshotRows(snapshot.id,1,25);assert.equal(frozen.results[0]?.payload.name,'F9 report snapshot original');assert.equal(frozen.results[0]?.payload.purchase_cost,'1234.56');
 async function exportFromSnapshot(format:'CSV'|'JSON',idempotency_key:string){const accepted=await reports.createExport({source_snapshot_id:snapshot.id,format,idempotency_key});assert.equal(accepted.sourceSnapshotId,snapshot.id);let result=await reports.export(accepted.id);for(let attempt=0;attempt<30&&(result.status==='QUEUED'||result.status==='RUNNING');attempt++){await new Promise(resolve=>setTimeout(resolve,100));result=await reports.export(result.id);}assert.equal(result.status,'COMPLETED');assert.equal(result.schemaVersion,1);assert.equal(result.rowCount,snapshot.rowCount);assert.ok(result.byteSize&&result.sha256);const file=await reports.downloadExport(result.id);assert.ok(file.contentDisposition?.includes('attachment'));const bytes=Buffer.from(await file.blob.arrayBuffer());assert.equal(bytes.byteLength,result.byteSize);assert.equal(createHash('sha256').update(bytes).digest('hex'),result.sha256);return{result,contents:bytes.toString('utf8')};}
 stage='request and authenticated-download private CSV from completed snapshot';const csv=await exportFromSnapshot('CSV',csvKey);assert.ok(csv.contents.includes('F9 report snapshot original'));assert.ok(csv.contents.includes('1234.56'));assert.ok(!csv.contents.includes('snapshot changed after capture'));assert.ok(csv.contents.includes('asset_tag'));
 stage='request and authenticated-download versioned JSON from same completed snapshot';const json=await exportFromSnapshot('JSON',jsonKey);const envelope=JSON.parse(json.contents) as {schema_version:number;snapshot:{id:string;schema_version:number};columns:string[];rows:Record<string,unknown>[]};stage='check JSON export envelope version';assert.equal(envelope.schema_version,1);stage='check JSON source snapshot identity';assert.equal(envelope.snapshot.id,snapshot.id);stage='check JSON frozen row schema version';assert.equal(envelope.snapshot.schema_version,1);stage='check JSON frozen schema-v1 column order';const frozenColumns=['id','asset_tag','name','status','condition','category','department','department_id','location','purchase_cost','accumulated_depreciation','current_book_value','capitalization_date','available_for_use_date'];assert.deepEqual(envelope.columns,frozenColumns);stage='check JSON rows match the corresponding captured snapshot fields';const expectedExportRow=Object.fromEntries(frozenColumns.map(column=>[column,frozen.results[0]!.payload[column]]));assert.deepEqual(envelope.rows,[expectedExportRow]);stage='check exact JSON Decimal value';assert.equal(envelope.rows[0]?.purchase_cost,'1234.56');stage='check JSON excludes changed live row';assert.ok(!json.contents.includes('snapshot changed after capture'));
 stage='logout';session.logout();assert.equal(storage.size,0);assert.equal(session.getSnapshot().user,null);
 console.log('PASS: isolated TypeScript → Django → PostgreSQL F9 live asset_register → idempotent completed snapshot schema v1 → source mutation → changed live row and unchanged captured row → private CSV and JSON exports from the same snapshot → authenticated downloads with matching SHA256/byte size; JSON envelope and CSV source rows verified; logout completed.');
}
void run().catch(error=>{const safe=error instanceof Error?error.name:'runtime failure';const detail=error instanceof Error&&'kind' in error?`${String((error as {kind:unknown}).kind)}${'status' in error?` HTTP ${String((error as {status:unknown}).status)}`:''}${'message' in error?`; ${String((error as {message:unknown}).message)}`:''}${'fields' in error?`; fields ${Object.keys((error as {fields:Record<string,unknown>}).fields).join(',')}`:''}`:error instanceof Error&&error.name==='AssertionError'?`; ${error.message.slice(0,500)}`:'';console.log(`SMOKE: failed at ${stage}; ${safe}${detail?`; ${detail}`:''}`);process.exitCode=1;});
