# Generated by Django 5.2.17 on 2026-09-29 23:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('asset_register', 'Asset register'), ('acquisitions', 'Acquisitions and capitalization'), ('depreciation', 'Depreciation ledger'), ('accounting_periods', 'Accounting periods'), ('assignments', 'Assignments and custody'), ('transfers', 'Transfers'), ('work_orders', 'Maintenance work orders'), ('maintenance_costs', 'Maintenance costs'), ('maintenance_records', 'Maintenance records'), ('disposals', 'Disposals'), ('verification_campaigns', 'Physical verification campaigns'), ('verification_records', 'Physical verification observations'), ('verification_exceptions', 'Physical verification exceptions'), ('assurance_runs', 'Assurance runs'), ('assurance_findings', 'Assurance findings'), ('assurance_occurrences', 'Assurance finding occurrences'), ('lifecycle_history', 'Lifecycle audit history')], max_length=32)),
                ('idempotency_key', models.UUIDField()),
                ('parameters', models.JSONField(default=dict)),
                ('scope_department_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('failure_class', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots_requested', to=settings.AUTH_USER_MODEL)),
                ('requested_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('ASSET_MANAGER', 'Asset Manager'), ('ACCOUNTANT', 'Accountant'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee')], max_length=32)),
            ],
            options={
                'ordering': ('-requested_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveBigIntegerField()),
                ('source_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='reporting.reportsnapshot')),
            ],
            options={
                'ordering': ('ordinal',),
            },
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['organization', 'report_type', 'requested_at'], name='report_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsnapshot',
            index=models.Index(fields=['organization', 'status', 'requested_at'], name='report_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='report_org_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('report_type__in', ['asset_register', 'acquisitions', 'depreciation', 'accounting_periods', 'assignments', 'transfers', 'work_orders', 'maintenance_costs', 'maintenance_records', 'disposals', 'verification_campaigns', 'verification_records', 'verification_exceptions', 'assurance_runs', 'assurance_findings', 'assurance_occurrences', 'lifecycle_history'])), name='report_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING', 'COMPLETED', 'FAILED'])), name='report_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('as_of__isnull', True), ('generated_at__isnull', True), ('started_at__isnull', True), ('status', 'QUEUED')), models.Q(('generated_at__isnull', True), ('started_at__isnull', False), ('status', 'RUNNING')), models.Q(('as_of__isnull', False), ('failure_class', ''), ('generated_at__isnull', False), ('started_at__isnull', False), ('status', 'COMPLETED')), models.Q(('failure_class__gt', ''), ('status', 'FAILED')), _connector='OR'), name='report_status_timestamps_valid'),
        ),
        migrations.AddIndex(
            model_name='reportsnapshotrow',
            index=models.Index(fields=['snapshot', 'ordinal'], name='report_row_page_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshotrow',
            constraint=models.UniqueConstraint(fields=('snapshot', 'ordinal'), name='report_row_ordinal_uniq'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshotrow',
            constraint=models.UniqueConstraint(fields=('snapshot', 'source_id'), name='report_row_source_uniq'),
        ),
    ]
