# Generated by Django 5.2.17 on 2026-09-29 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reportsnapshot',
            name='report_status_timestamps_valid',
        ),
        migrations.AddField(
            model_name='reportsnapshot',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('as_of__isnull', True), ('failed_at__isnull', True), ('generated_at__isnull', True), ('started_at__isnull', True), ('status', 'QUEUED')), models.Q(('failed_at__isnull', True), ('generated_at__isnull', True), ('started_at__isnull', False), ('status', 'RUNNING')), models.Q(('as_of__isnull', False), ('failed_at__isnull', True), ('failure_class', ''), ('generated_at__isnull', False), ('started_at__isnull', False), ('status', 'COMPLETED')), models.Q(('failed_at__isnull', False), ('failure_class__gt', ''), ('generated_at__isnull', True), ('status', 'FAILED')), _connector='OR'), name='report_status_timestamps_valid'),
        ),
    ]
