# Generated by Django 5.2.17 on 2026-09-30 10:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('reporting', '0002_remove_reportsnapshot_report_status_timestamps_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON')], max_length=8)),
                ('idempotency_key', models.UUIDField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='QUEUED', max_length=10)),
                ('generation_token', models.UUIDField(blank=True, null=True)),
                ('cleanup_storage_keys', models.JSONField(blank=True, default=list)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('failure_class', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports_requested', to=settings.AUTH_USER_MODEL)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='reporting.reportsnapshot')),
            ],
            options={
                'ordering': ('-requested_at', '-id'),
                'indexes': [models.Index(fields=['organization', 'status', 'requested_at'], name='report_exp_org_status_idx'), models.Index(fields=['status', 'updated_at'], name='report_exp_status_update_idx'), models.Index(fields=['status', 'expires_at'], name='report_exp_status_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='report_export_org_idem_uniq'), models.CheckConstraint(condition=models.Q(('format__in', ['CSV', 'JSON'])), name='report_export_format_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'EXPIRED'])), name='report_export_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('byte_size__isnull', True), ('completed_at__isnull', True), ('expired_at__isnull', True), ('failed_at__isnull', True), ('sha256', ''), ('started_at__isnull', True), ('status', 'QUEUED'), ('storage_key', '')), models.Q(('byte_size__isnull', True), ('completed_at__isnull', True), ('expired_at__isnull', True), ('failed_at__isnull', True), ('sha256', ''), ('started_at__isnull', False), ('status', 'RUNNING'), ('storage_key', '')), models.Q(('byte_size__gt', 0), ('completed_at__isnull', False), ('expired_at__isnull', True), ('failed_at__isnull', True), ('failure_class', ''), ('sha256__regex', '^[0-9a-f]{64}$'), ('started_at__isnull', False), ('status', 'COMPLETED'), ('storage_key__gt', '')), models.Q(('byte_size__isnull', True), ('completed_at__isnull', True), ('expired_at__isnull', True), ('failed_at__isnull', False), ('failure_class__gt', ''), ('sha256', ''), ('status', 'FAILED'), ('storage_key', '')), models.Q(('completed_at__isnull', False), ('expired_at__isnull', False), ('status', 'EXPIRED')), _connector='OR'), name='report_export_state_valid')],
            },
        ),
    ]
